project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Statistics"
  
  author-meta: "Cheng-Han Yu"
  date-meta: today
  description-meta: |
    This book serves as a main reference book for my MATH 4720 Statistical Methods 
    and MATH 4740 Biostatistical Methods at Marquette University. Some topics can 
    also be discussed in an introductory data science course. You'll learn basic 
    probability and statistical concepts as well as data analysis techniques 
    such as linear regression using R computing software.
    
  page-footer:
    left: |
      Introduction to Statistics was written by Cheng-Han Yu.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  # cover-image:
  # site-url:
  repo-url: https://github.com/chenghanyustats/introstatsbook
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - intro-stats.qmd
        - intro-data.qmd
        - intro-r.qmd
    - part: datasummary.qmd
      chapters:
        - data-graphics.qmd
        - data-numerics.qmd
    - part: prob.qmd
      chapters:
        - prob-define.qmd
        - prob-rule.qmd
        - prob-rv.qmd
        - prob-disc.qmd
        - prob-cont.qmd
        - prob-samdist.qmd
        - prob-llnclt.qmd
    - part: infer.qmd
      chapters:
        - infer-ci.qmd
        - infer-bt.qmd
        - infer-ht.qmd
        - infer-twomean.qmd
        - infer-var.qmd
        - infer-prop.qmd
        - infer-goodnessfit.qmd
        - infer-indep.qmd
        - infer-bayes.qmd
        - infer-nonpar.qmd
    - part: model.qmd
      chapters:
        - model-anova.qmd
        - model-reg.qmd
        - model-logistic.qmd
        - model-bayes.qmd
        - model-survival.qmd
    # - summary.qmd
    - references.qmd
  # chapters:
  #   - index.qmd
  #   - preface.qmd
  #   - part: dice.qmd
  #     chapters: 
  #       - basics.qmd
  #       - packages.qmd
  #   - part: cards.qmd
  #     chapters:
  #       - objects.qmd
  #       - notation.qmd
  #       - modifying.qmd
  #       - environments.qmd
  #   - part: slots.qmd
  #     chapters:
  #       - programs.qmd
  #       - s3.qmd
  #       - loops.qmd
  #       - speed.qmd
  # appendices:
  #   - a1-starting.qmd
  #   - a2-packages.qmd
  #   - a3-updating.qmd
  #   - a4-data.qmd
  #   - a5-debug.qmd 

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    # cover-image: cover.png
    callout-appearance: simple
  pdf:
    documentclass: scrreprt
