project:
  type: book
  output-dir: docs

execute:
  fig-align: center
  
book:
  title: "Introduction to Statistics"
  author: "Dr. Cheng-Han Yu"
  date: today
  site-url: https://chenghanyu-introstatsbook.netlify.app/
  repo-url: https://github.com/chenghanyustats/introstatsbook
  page-navigation: true
  description: An introductory statistical data science book for STEM students.
  page-footer:
    border: false
    background: light
    left: "Copyright 2024, Dr. Cheng-Han Yu"
    right:
      - icon: github
        href: https://github.com/chenghanyustats/introstatsbook
  
  # cover-image:
  # site-url:
  repo-branch: main
  repo-actions: [edit, issue]
  sharing: [twitter, facebook, linkedin]
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - intro-stats.qmd
        - intro-data.qmd
        - intro-r.qmd
    - part: datasummary.qmd
      chapters:
        - data-graphics.qmd
        - data-numerics.qmd
    - part: prob.qmd
      chapters:
        - prob-define.qmd
        - prob-rule.qmd
        - prob-rv.qmd
        - prob-disc.qmd
        - prob-cont.qmd
        - prob-sampling.qmd
        - prob-llnclt.qmd
    - part: infer.qmd
      chapters:
        - infer-ci.qmd
        - infer-bt.qmd
        - infer-ht.qmd
        - infer-twomean.qmd
        - infer-var.qmd
        - infer-prop.qmd
        - infer-cat.qmd
        - infer-p.qmd
        - infer-bayes.qmd
        - infer-nonpar.qmd
    - part: model.qmd
      chapters:
        - model-anova.qmd
        - model-multicomp.qmd
        - model-twoway.qmd
        - model-reg.qmd
        - model-mlr.qmd
        - model-logistic.qmd
        - model-bayes.qmd
        - model-survival.qmd

    # - summary.qmd
    - part: references.qmd
  # chapters:
  #   - index.qmd
  #   - preface.qmd
  #   - part: dice.qmd
  #     chapters: 
  #       - basics.qmd
  #       - packages.qmd
  #   - part: cards.qmd
  #     chapters:
  #       - objects.qmd
  #       - notation.qmd
  #       - modifying.qmd
  #       - environments.qmd
  #   - part: slots.qmd
  #     chapters:
  #       - programs.qmd
  #       - s3.qmd
  #       - loops.qmd
  #       - speed.qmd
  appendices:
    - a-r_prog.qmd
    - a-py_prog.qmd
    # - a3-updating.qmd
    # - a4-data.qmd
    # - a5-debug.qmd

bibliography: references.bib

format:
  html:
    # include-in-header:
    #   - file: macros.html
    theme:
      light: [cosmo, introstatsbook.scss]
      # light: [cosmo, introstatsbook.scss]
      dark: [superhero, dark.scss]
      # dark: [cosmo, darkly]
    code-link: true
    css: custom.css
    # cover-image: cover.png
    # callout-appearance: defualt, simple or minimal
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex

  