## Welcome {.unnumbered}

This is the website for my introductory statistics book. Currently this book serves as a main reference book for my MATH 4720 Statistical Methods and MATH 4740 Biostatistical Methods classes at Marquette University.[^index-1] Some topics can also be discussed in an introductory data science, regression, or other applied statistics courses. You'll learn basic probability and statistical concepts as well as data analysis techniques such as linear regression using [R](https://www.r-project.org/)[^index-2] and [Python](https://www.python.org/). 


The book balances the following aspects of statistics:

-   mathematical formulation and statistical computation
-   distribution-based and simulation-based inferences
-   methodology and applications
-   classical/frequentist and Bayesian approaches

The materials in this book are adapted and modified from several existing statistics books, course websites, notes, and tutorials for best teaching and learning experience at Marquette. Main reference books are:

- [OpenIntro Statsitics (OS)](https://www.openintro.org/book/os/) (data focused)
- [Introduction to Modern Statistics (IMS)](https://openintro-ims.netlify.app/) (simulation-based and computation focused)
- [An Introduction to Statistical Methods & Data Analysis, 7th edition (SMD)](https://www.filepicker.io/api/file/GdeoWEcATWi1pXV1DlPe) (distribution-based and mathematics focused)[^index-3]

The book will continue to be updated, with the next version focusing on the following topics.

- Permutation/randomization test
- Modeling-first approach
- Applets
- Generative AI and Large Language Models (LLMs) integration
- Real data applications

[^index-1]: For some historical reason, the two courses are numbered as senior level courses. However, both are introductory courses mainly taken by undergraduate students in STEM fields.

[^index-2]: This book uses base R (the default R syntax) rather than [tidyverse R](https://www.tidyverse.org/), the meta package ecosystem I teach in my [MATH/COSC 3570 Introduction to Data Science](https://math3570-s24.github.io/website/) course. While tidyverse offers a unified approach to data science and is becoming increasingly popular, I was somewhat persuaded by [Prof. Matloff's TidyverseSkeptic post ](https://github.com/matloff/TidyverseSkeptic) and believe there is value in learning and teaching base R in an introductory statistics course. To be clear, both base R and tidyverse are excellent tools (I use both in my research and teaching). Being proficient in both approaches can only enhance your data science skills.


<!-- [^index-3]: The book includes Python code because it is the most popular programming language at the moment.  -->


[^index-3]: This book has been served as the official textbook for MATH 4720 for years. However, I feel that this book is more suitable for senior undergraduate students or graduate students.



## License

This website is (and will always be) **free to use**, and is licensed under the [Creative Commons Attribution-NonCommercial-NoDerivs 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) License. If you'd like to give back, please consider reporting a typo or leaving a pull request at [github.com/chenghanyustats/introstatsbook](https://github.com/chenghanyustats/introstatsbook).
