# The Issues of $p$-value and Statistical Significance {#sec-infer-p}

> Our brain has this annoying habit to think that [...], if under some hypothesis, results are unlikely, then the hypothesis is unlikely. This is false. 
> -- Christophe Michel (1974 - )

> There are three types of lies: lies, damn lies, and statistics.
> -- Benjamin Disraeli (1804 - 1881)

We have been using the [classical or frequentist approach](https://en.wikipedia.org/wiki/Frequentist_inference) to do a variety of statistical inferences. But Dr. Yu once said he never uses p-value in his own research, and there are many issues with what is taught in Intro Stats (MATH 1700/4720/4740). In fact, the null hypothesis significance testing (NHST) paradigm and the p-value usage have been much criticized and shown to be problematic, misused, and resulting in reproducibility and replication crisis in scientific research.
  
Some references are

  - [Wikipedia: Misuse of p-values](https://en.wikipedia.org/wiki/Misuse_of_p-values)
  
  - [A. Reinhart (2015), "Statistics Done Wrong", *No Starch Press*, San Francisco.](https://www.statisticsdonewrong.com/)
  
  - [R. L. Wasserstein and Nicole A. Lazar (2016), "The ASA Statement on p-Values: Context, Process, and Purpose", *The American Statistician*, 70:2, 129-133.](https://www.tandfonline.com/doi/full/10.1080/00031305.2016.1154108)
  
  - [V. Amrhein, S. Greenland and B. McShane (2019), "Retire statistical significance", *Nature*, 567, 305-307. ](https://www.nature.com/articles/d41586-019-00857-9)
  
  - [B. McShane, D. Gal, A. Gelman, C. Robert and Jennifer L. Tackett (2019), "Abandon Statistical Significance", *The American Statistician*, 73:sup1, 235-245.](https://www.tandfonline.com/doi/full/10.1080/00031305.2018.1527253)
  
  - [A. Gelamn and E. Loken (2014), "The Statistical Crisis in Science", *American Scientist*, 102, 460-465.](http://stat.columbia.edu/~gelman/research/published/ForkingPaths.pdf)
  
  - [R. L. Wasserstein, A. L. Schirm and N. A. Lazar (2019), "Moving to a World Beyond p < 0.05", *The American Statistician*, 73:sup1, 1-19.](https://www.tandfonline.com/doi/full/10.1080/00031305.2019.1583913)

  - [Statistically Discernible by Editorial of Journal of Statistics Education](https://www.tandfonline.com/doi/full/10.1080/10691898.2019.1702415#d1e86)
  
<!-- ## $p$ Hacking -->

<!-- ## Dichonomous Decision Making -->

<!-- ## $p$-value and Statistical Significance Paradigm Just Don't Work -->

