# Probability {#sec-prob}

If we want to describe or quantify the uncertainty about something happening or not, the most formal and rigorous way of doing it is to use **probability**. Therefore, we can view the probability as the language of uncertainty. 

Most of the time, we cannot do statistical inference or prediction using machine learning without probability because we usually assume our data at hand are random realizations from some targeted population that are described by a probability distribution. In other words, we are doing data analysis in the world of uncertainty. As a result, before jumping into statistical inference or data analysis, we need to have basic understanding of probability definitions, rules, and operations that are frequently used in the data science community.

In this part, we are going to learn the following topics:

- Probability definitions

- Probability rules

- Discrete probability distributions

- Continuous probability distributions

- Random sampling and sampling distributions

- Law of large numbers and central limit theorem
