<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="An comprehensive introductory statistical data science book.">
<title>Introduction to Statistics - 13&nbsp; Point and Interval Estimation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./infer-bt.html" rel="next">
<link href="./infer.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Point and Interval Estimation</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Statistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/chenghanyustats/introstatsbook" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="" title="Share" id="sidebar-tool-dropdown-0" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-share"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-0">
<li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
            <i class="bi bi-bi-twitter pe-1"></i>
          Twitter
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
            <i class="bi bi-bi-facebook pe-1"></i>
          Facebook
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
            <i class="bi bi-bi-linkedin pe-1"></i>
          LinkedIn
          </a>
        </li>
    </ul>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./intro.html" class="sidebar-item-text sidebar-link">Statistics and Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-stats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Science of Data and Data Science</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-r.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Tool foR Data</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./datasummary.html" class="sidebar-item-text sidebar-link">Summarizing Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-graphics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-numerics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Sample Statistics</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./prob.html" class="sidebar-item-text sidebar-link">Probability</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-define.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Definition of Probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-rule.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability Rules</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-rv.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Random Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-disc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Discrete Probability Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-cont.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Continuous Probability Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-samdist.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Sampling Distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-llnclt.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Law of Large Numbers and Central Limit Theorem</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./infer.html" class="sidebar-item-text sidebar-link">Statistical Inference</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-ci.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Point and Interval Estimation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-bt.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Bootstrapping</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-ht.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-twomean.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Comparing Two Population Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-var.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Inference About Variances</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-prop.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference About Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-cat.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference about Categorical Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-bayes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Bayesian Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-nonpar.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Nonparametric Methods</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./model.html" class="sidebar-item-text sidebar-link">Statistical Models</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-reg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-logistic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Logistic Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-bayes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Bayesian Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Survival Analysis</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#point-estimator" id="toc-point-estimator" class="nav-link active" data-scroll-target="#point-estimator"><span class="toc-section-number">13.1</span>  Point Estimator</a></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals"><span class="toc-section-number">13.2</span>  Confidence Intervals</a></li>
  <li><a href="#confidence-intervals-for-mu-when-sigma-is-known" id="toc-confidence-intervals-for-mu-when-sigma-is-known" class="nav-link" data-scroll-target="#confidence-intervals-for-mu-when-sigma-is-known"><span class="toc-section-number">13.3</span>  Confidence Intervals for <span class="math inline">\(\mu\)</span> When <span class="math inline">\(\sigma\)</span> is Known</a></li>
  <li><a href="#confidence-intervals-for-mu-when-sigma-is-unknown" id="toc-confidence-intervals-for-mu-when-sigma-is-unknown" class="nav-link" data-scroll-target="#confidence-intervals-for-mu-when-sigma-is-unknown"><span class="toc-section-number">13.4</span>  Confidence Intervals for <span class="math inline">\(\mu\)</span> When <span class="math inline">\(\sigma\)</span> is Unknown</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="toc-section-number">13.5</span>  Summary</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="toc-section-number">13.6</span>  Exercises</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/chenghanyustats/introstatsbook/edit/main/infer-ci.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/chenghanyustats/introstatsbook/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-infer-ci" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Point and Interval Estimation</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><div class="cell">

</div>
<div class="cell">

</div>
<!-- ## Foundations for Inference -->
<!-- <span style="color:blue"> **Inference Framework** </span> -->
<!-- - **Inferential statistics uses sample data to learn about an unknown population**. -->
<!-- - **Idea**: Assume the target population follows some distribution but with **unknown** parameters. -->
<!--   + <span style="color:blue"> Assume the population is normally distributed but its mean and/or variance are unknown. </span> -->
<!-- - **Goal**: Learn the unknown parameters of the assumed population distribution. -->
<!-- ::::{.columns} -->
<!-- :::{.column width="50%"} -->
<!-- ```{r sample, cache=TRUE, echo=FALSE, out.width="80%",fig.align='center'} -->
<!-- #| label: fig-sampling -->
<!-- #| fig-cap: Sampling from a population -->
<!-- par(mar = 0*c(1,1,1,1)) -->
<!-- plot(c(0, 2), -->
<!--      c(0, 1.1), -->
<!--      type = 'n', -->
<!--      axes = FALSE, xlab = "", ylab = "") -->
<!-- temp <- seq(0, 2 * pi, 2 * pi / 100) -->
<!-- x <- 0.5 + 0.5 * cos(temp) -->
<!-- y <- 0.5 + 0.5 * sin(temp) -->
<!-- lines(x, y) -->
<!-- s <- matrix(runif(700), ncol = 2) -->
<!-- S <- matrix(NA, 350, 2) -->
<!-- j <- 0 -->
<!-- for (i in 1:nrow(s)) { -->
<!--   if(sum((s[i, ] - 0.5)^2) < 0.23){ -->
<!--     j <- j + 1 -->
<!--     S[j, ] <- s[i, ] -->
<!--   } -->
<!-- } -->
<!-- points(S, col = COL[1, 3], pch = 20) -->
<!-- text(0.5, 1, 'Population', pos = 3) -->
<!-- set.seed(50) -->
<!-- N <- sample(j, 25) -->
<!-- lines((x - 0.5) / 2 + 1.5, (y - 0.5) / 2 +  0.5, pch = 20) -->
<!-- SS <- (S[N, ] - 0.5) / 2 + 0.5 -->
<!-- these <- c(2, 5, 11, 10, 12) -->
<!-- points(SS[these, 1] + 1, -->
<!--        SS[these, 2], -->
<!--        col = COL[4, 2], -->
<!--        pch = 20, -->
<!--        cex = 1.5) -->
<!-- text(1.5, 0.75, 'Sample', pos = 3) -->
<!-- for (i in these) { -->
<!--   arrows(S[N[i], 1], S[N[i], 2], -->
<!--          SS[i, 1] + 1 - 0.03, SS[i, 2], -->
<!--          length = 0.08, col = COL[5], lwd = 1.5) -->
<!-- } -->
<!-- ``` -->
<!-- ::: -->
<!-- :::{.column width="50%"} -->
<!-- ```{r, echo=FALSE, out.width="77%",fig.align='center'} -->
<!-- #| label: fig-data-generating -->
<!-- #| fig-cap: Relationship between probabiltity and statistical inference -->
<!-- # knitr::include_graphics("./img/data_generating.png") -->
<!-- # fig.cap="Figure 1.1 in All of Statistics (Wasserman 2003)" -->
<!-- par(mar = c(0, 0, 0, 0)) -->
<!-- plot(0, 0, type = "n", axes = FALSE, xlab = "", ylab = "") -->
<!-- plotrix::draw.ellipse(x = -0.56, y = 0, a = 0.52, b = 0.4, lwd = 2) -->
<!-- plotrix::draw.ellipse(x = 0.56, y = 0, a = 0.45, b = 0.34, lwd = 2) -->
<!-- text(x = -0.56, y = 0, labels = "Data Generating Process", cex = 1.5) -->
<!-- text(x = 0.56, y = 0, labels = "Observed Data", cex = 1.5) -->
<!-- diagram::curvedarrow(from = c(-0.56, 0.47), to = c(0.56, 0.47),  -->
<!--                      curve = -0.2, arr.pos = 0.98) -->
<!-- diagram::curvedarrow(from = c(0.56, -0.47), to = c(-0.56, -0.47),  -->
<!--                      curve = -0.2, arr.pos = 0.98) -->
<!-- text(x = 0, y = 0.8, labels = "Probability", cex = 1.5) -->
<!-- text(x = 0, y = -0.8, labels = "Statistical Inference", cex = 1.5) -->
<!-- # plot(0, 0, type = "n", axes = FALSE, xlab = "", ylab = "") -->
<!-- # plotrix::draw.ellipse(x = -0.3, y = 0.5, a = 0.65, b = 0.45, lwd = 2) -->
<!-- # plotrix::draw.ellipse(x = -0.3, y = 0.4, a = 0.35, b = 0.2, lwd = 2, lty = 2) -->
<!-- # text(x = -0.3, y = 0.7, labels = "Set of all measurements: Population", cex = 1.2) -->
<!-- # plotrix::draw.ellipse(x = 0.5, y = -0.5, a = 0.36, b = 0.21, lwd = 2, lty = 1) -->
<!-- # diagram::curvedarrow(from = c(-0.3, 0.4), to = c(0.5, -0.3),  -->
<!-- #                      curve = -0.2, arr.pos = 0.98) -->
<!-- # text(x = 0.5, y = -0.5, labels = "Sample", cex = 1.2) -->
<!-- # text(x = 0, y = -0.4, labels = "Set of data selected from the population:", cex = 1.2) -->
<!-- ``` -->
<!-- ::: -->
<!-- :::: -->
<!-- - There are two approaches in parameter learning. -->
<!--   - **Estimation**  -->
<!--   - **Hypothesis Testing** -->
<p>In this chapter we will be talking about estimation including point and interval estimation. Point estimation uses one single number computed from the sample to estimate our unknown parameter. Interval estimation provides uncertainty quantification and uses a range of plausible numbers to let us know where the truth unknown parameter may be located.</p>
<section id="point-estimator" class="level2" data-number="13.1"><h2 data-number="13.1" class="anchored" data-anchor-id="point-estimator">
<span class="header-section-number">13.1</span> Point Estimator</h2>
<p>Let me ask you a question.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
If you could <strong>only use a single number</strong> to guess the unknown population mean, <span class="math inline">\(\mu\)</span>, what number would you like to use?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>If the single number you use can be computed from of sample data <span class="math inline">\((X_1, X_2, \dots, X_n)\)</span>, then you use a <strong>point estimator</strong> to estimate the unknown parameter <span class="math inline">\(\mu\)</span>. Previously we learned that a sample statistic is any transformation or function of <span class="math inline">\((X_1, X_2, \dots, X_n)\)</span>. Therefore, any statistic is considered a point estimator if it is used to estimate a population parameter.</p>
<p>A <strong>point estimate</strong> is a value of a point estimator used to estimate a population parameter. So here is the subtle difference. A point estimator is a <em>random variable</em> which is a function of sample data <span class="math inline">\((X_1, X_2, \dots, X_n)\)</span> (before actually being collected), and a point estimate is the <em>realized value</em> a point estimator, which is a value calculated from the collected data. For example, <span class="math inline">\(\overline{X} = \frac{1}{n}\sum_{i=1}^nX_i\)</span> is a point estimator, and with the sample data <span class="math inline">\((x_1, x_2, x_3) = (2, 3, 7)\)</span>, the point estimate is <span class="math inline">\(\overline{x} = \frac{1}{3}\sum_{i=1}^3x_i = \frac{1}{3}(2+3+7) = 4.\)</span></p>
<p>Back to the question. If we want to estimate the unknown population mean, which number we use to estimate it? We now have an intuitive answer. The sample mean <span class="math inline">\(\overline{X}\)</span> is a statistic and a point estimator for the population mean <span class="math inline">\(\mu\)</span>.</p>
<!-- considered a point estimator** *(before actually being collected). -->
<!-- A single point used to estimate the unknown parameter is known as a **point estimator**. A **point estimator** is any function of sample data $(X_1, X_2, \dots, X_n)$. -->
<!--   + **Any statistic is considered a point estimator** *(before actually being collected).* -->
<!-- - A **point estimate** is a value of a point estimator used to estimate a population parameter.  -->
<!--   + This is a value calculated from the collected data. -->
<hr>
<p><span style="color:blue"> <strong>Sample Mean as an Point Estimator</strong> </span></p>
<p>Let’s see how the sample mean is used as an point estimator for <span class="math inline">\(\mu.\)</span> Suppose the true population distribution is <span class="math inline">\(N(2, 1)\)</span>. Here the population mean <span class="math inline">\(\mu\)</span> is two, but let’s pretend we don’t know its value and see how the sample mean performs. Such analysis is called simulation study.</p>
<p>We are going to collect a sample of size five, <span class="math inline">\((x_1, x_2, x_3, x_4, x_5)\)</span>. In the simulation, we draw five values from <span class="math inline">\(N(2, 1)\)</span>. The five drawn values are treated as our sample data, and <span class="math inline">\(N(2, 1)\)</span> is the population distribution. In R, we use <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a></code> to generate random numbers from a normal distribution, where the first argument is the number of observations to be generated.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Generate data x1, x2, x3, x4, x5, each from distribution N(2, 1)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span></span>
<span><span class="va">x_data_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5</span>, mean <span class="op">=</span> <span class="fl">2</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The following shows the realized five data points and the sample mean.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead><tr class="header">
<th style="text-align: center;">x1</th>
<th style="text-align: center;">x2</th>
<th style="text-align: center;">x3</th>
<th style="text-align: center;">x4</th>
<th style="text-align: center;">x5</th>
<th style="text-align: center;">sample mean</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: center;">0.79</td>
<td style="text-align: center;">2.28</td>
<td style="text-align: center;">3.08</td>
<td style="text-align: center;">-0.35</td>
<td style="text-align: center;">2.43</td>
<td style="text-align: center;">1.65</td>
</tr></tbody>
</table>
</div>
</div>
<p>Here we use the sample mean <span class="math inline">\(\overline{X} = \frac{1}{5}\sum_{i=1}^5X_i\)</span> as our point estimator for <span class="math inline">\(\mu\)</span>, and given the sample, the point estimate is <span class="math inline">\(\overline{x}=\)</span> 1.65. You can see that the true <span class="math inline">\(\mu\)</span> is two, but the point estimate <span class="math inline">\(\overline{x}\)</span> is not equal to <span class="math inline">\(\mu\)</span>. Why?</p>
<p>As we discussed in <a href="prob-samdist.html"><span>Chapter&nbsp;11</span></a>, due to the randomness nature of drawing a sample value from the population distribution, we do not expect the statistic to be the same as the corresponding parameter. It is possible that most of our sample values happen to be larger or smaller than the true mean, or we may unluckily get an outlier sample value that distorts and drags the sample value toward it. In such cases, the sample mean will be not close to the true population mean. You can think this way. <em>One data point represents one piece of information about the unknown population distribution</em>. With a small sample size, our sample only represents a small part of the unknown distribution. The gap between sample mean and the true population mean is kind of like information lost because of not being able to collect the rest of the subjects in the population.</p>
<p><a href="#fig-sample-mean">Figure&nbsp;<span>13.1</span></a> shows the sample data and the population distribution <span class="math inline">\(N(2, 1)\)</span>. Notice that we have an extreme value <span class="math inline">\(-0.35\)</span> that is two standard deviations below the mean, and this causes the sample mean to be small.</p>
<!-- :::{.callout-note icon=false} -->
<!-- ## Why is $\overline{x}$ not equal to $\mu$? -->
<!-- - Due to its **randomness** nature -->
<!-- ::: -->
<div class="cell" data-layout-align="center" data-fig.asp="0.5">
<div class="cell-output-display">
<div id="fig-sample-mean" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="infer-ci_files/figure-html/fig-sample-mean-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;13.1: Population distribution and sample data.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Well, we could collect a sample again if resources are permitted. In simulation, another sample of size five is drawn from the same population <span class="math inline">\(N(2, 1)\)</span>, and the result is shown below.</p>
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead><tr class="header">
<th style="text-align: center;">x1</th>
<th style="text-align: center;">x2</th>
<th style="text-align: center;">x3</th>
<th style="text-align: center;">x4</th>
<th style="text-align: center;">x5</th>
<th style="text-align: center;">sample mean</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: center;">2.59</td>
<td style="text-align: center;">2.71</td>
<td style="text-align: center;">1.89</td>
<td style="text-align: center;">1.55</td>
<td style="text-align: center;">2.61</td>
<td style="text-align: center;">2.27</td>
</tr></tbody>
</table>
</div>
</div>
<p>The second sample mean, <span class="math inline">\(\overline{x} =\)</span> 2.27, is different from the first one. Why do the first sample and the second sample give us different sample means? Now you see why we want to learn sampling distribution. We use sample mean as the point estimator for <span class="math inline">\(\mu\)</span>, and the sample mean has its own <em>sampling distribution</em>. Therefore, the sample mean varies from sample to sample due to its randomness nature.</p>
<!-- :::{.callout-note icon=false} -->
<!-- ## Why do the first sample and the second sample give us different sample means? -->
<!-- - A point estimator has its own *sampling distribution*. -->
<!-- ::: -->
<p>We have connected sampling distribution to statistical inference, in particular the point estimation together. <a href="#fig-samp-dist">Figure&nbsp;<span>13.2</span></a> shows the sampling distribution of <span class="math inline">\(\overline{X}\)</span> which is <span class="math inline">\(N(2, 1/5)\)</span> and the two sample mean values calculated from the two data sets. Now can you see why we want to use <span class="math inline">\(\overline{X}\)</span> as the point estimator for <span class="math inline">\(\mu\)</span>? It is because the expected value of <span class="math inline">\(\overline{X}\)</span>, <span class="math inline">\(E(\overline{X})\)</span> is exactly equal to <span class="math inline">\(\mu\)</span>, meaning that if we were able to produces a lot of <span class="math inline">\(\overline{x}\)</span>s, the average of these <span class="math inline">\(\overline{x}\)</span>s will be very close to the true unknown <span class="math inline">\(\mu\)</span> although single one <span class="math inline">\(\overline{x}\)</span> may still be distant from <span class="math inline">\(\mu\)</span>. When the expected value of a point estimator is equal to the parameter it estimates, we say it is an <strong>unbiased estimator</strong>. Therefore, the sample mean <span class="math inline">\(\overline{X}\)</span> is an unbiased estimator for the population mean <span class="math inline">\(\mu\)</span> because <span class="math inline">\(E(\overline{X}) = \mu\)</span>.</p>
<div class="cell" data-layout-align="center" data-fig.asp="0.5">
<div class="cell-output-display">
<div id="fig-samp-dist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="infer-ci_files/figure-html/fig-samp-dist-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;13.2: Sampling Distribution of Sampling Mean.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<hr>
<p><span style="color:blue"> <strong>Why Point Estimates Are Not Enough</strong> </span></p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
If you want to estimate <span class="math inline">\(\mu\)</span>, would you prefer to report a range of values the parameter might be in or a single estimate like <span class="math inline">\(\overline{x}\)</span>?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>Since <span class="math inline">\(\overline{X}\)</span> is random and has its own distribution, its value varies from sample to sample. However, in reality we usually have only one data set, and one realized sample mean, and we are not able to replicate other data sets due to limited resources. We don’t know the sample mean we got is close to the true unknown population mean or not. First, the sample mean can go anywhere of its distribution, and the one we got may be far away from <span class="math inline">\(\mu\)</span>. Moreover, we don’t know the value of <span class="math inline">\(\mu\)</span>! It does not make much sense to use just one single number when those uncertainty are there.</p>
<p>If you want to catch a fish, would you prefer to use a spear or a net? I would use a net because I’m not a sharpshooter, and using a net covers a large range of possible locations where the fish can be. Due to the variation of <span class="math inline">\(\overline{X}\)</span>, if we report a point estimate, we probably won’t hit the exact population parameter. If we report a range of plausible values, we have a good shot at capturing the parameter.</p>
<!-- :::{.callout-note icon=false} -->
<!-- ## If you want to catch a fish, would you prefer to use a spear or a net? -->
<!-- ::: -->
<!-- ::::{.columns} -->
<!-- :::{.column width="50%"} -->
<!-- ```{r echo=FALSE, out.width="80%", fig.align='center'} -->
<!-- knitr::include_graphics("./images/img-infer/spear.png") -->
<!-- ``` -->
<!-- ::: -->
<!-- :::{.column width="50%"} -->
<!-- ```{r echo=FALSE, out.width="80%", fig.align='center'} -->
<!-- knitr::include_graphics("./images/img-infer/net.png") -->
<!-- ``` -->
<!-- ::: -->
<!-- :::: -->
<!-- - Due to the variation of $\overline{X}$, if we report a point estimate $\overline{x}$, we probably won't hit the exact $\mu$. -->
<!-- - If we report *a range of plausible values*, we have a better shot at capturing the parameter! -->
</section><section id="confidence-intervals" class="level2" data-number="13.2"><h2 data-number="13.2" class="anchored" data-anchor-id="confidence-intervals">
<span class="header-section-number">13.2</span> Confidence Intervals</h2>
<p>In statistics, a plausible range of values for <span class="math inline">\(\mu\)</span> is called a <strong>confidence interval (CI)</strong>. This range depends on how <em>precise</em> and <em>reliable</em> our statistic is as an estimate of the parameter. To construct a CI for <span class="math inline">\(\mu\)</span>, we first need to quantify the variability of our sample mean. Quantifying this uncertainty requires a measurement of how much we would expect the sample statistic to vary from sample to sample. This is in fact the <em>variance</em> of the sampling distribution of the sample mean! Intuitively speaking, if <span class="math inline">\(\overline{x}\)</span> varies a lot, we are more uncertain about whether the <span class="math inline">\(\overline{x}\)</span> we got is close to the <span class="math inline">\(\mu\)</span> or not. In other words, the precision of the estimation is not that good. In order to make sure that the plausible range of values does capture <span class="math inline">\(\mu\)</span>, we need to include more possible values, and make the range larger. Do we know the variance of <span class="math inline">\(\overline{X}\)</span>? Absolutely. Thanks to CLT, <span class="math inline">\(\overline{X} \sim N(\mu, \sigma^2/n)\)</span> <em>regardless of what the population distribution is</em>.</p>
<p>How <em>confident</em> we are about the CI covering the parameter is called the <strong>level of confidence</strong>. The higher the confidence level is, the more <strong>reliable</strong> the CI is because the CI is more likely to capture the parameter.</p>
<!-- Intuitively speaking, if we want to be pretty sure the net captures the fish we want, the net should be bigger. -->
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>Given the same level of confidence, the larger the variation of <span class="math inline">\(\overline{X}\)</span> is, the wider the CI for <span class="math inline">\(\mu\)</span> will be.</em></p>
</div>
</div>
<hr>
<p><span style="color:blue"> <strong>Precision vs.&nbsp;Reliability</strong> </span></p>
<p>With a fixed sample size, the precision and reliability of a confidence interval are trading off. Here is a question.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
If we want to be very certain that we capture <span class="math inline">\(\mu\)</span>, should we use a wider or a narrower interval? What drawbacks are associated with using a wider interval?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>We use a wider interval because a wider interval is more likely to capture the population parameter value. So a more reliable confidence interval is wider than a less reliable confidence interval. But What drawbacks are associated with using a wider interval?</p>
<p>The precision and reliability trade-off is clearly explained in the cute comic in <a href="#fig-garfield">Figure&nbsp;<span>13.3</span></a>. I can say I am 100% confident that your exam 1 score is between 0 and 100. Am I right? Yes. But do I provide helpful information? Absolutely not, the interval includes every possible score of the exam. The interval is too wide to be helpful. Such interval is 100% reliable but with no precision at all.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-garfield" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="./images/img-infer/garfield.png" class="img-fluid figure-img" width="680"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;13.3: Balance between precision and reliability. Source: https://thestatsninja.com/2019/02/19/how-to-navigate-confidence-intervals-with-confidence/</figcaption><p></p>
</figure>
</div>
</div>
</div>
<!-- - With a fixed sample size, precision and reliability have a trade-off relationship. -->
<p>Narrower intervals are more precise but less reliable, while wider intervals are more reliable but less precise. How can we get best of both worlds – high precision and high reliability/accuracy, meaning short interval with high level of confidence? What we need is larger sample size, given that the sample quality is good. It is a quite easy statement, but sometimes it’s hard to collect more samples.</p>
<hr>
<p><span style="color:blue"> <strong>A Confidence Interval Is for a Parameter</strong> </span></p>
<p>A confidence interval is for a <em>parameter, NOT a statistic.</em> Remember, a confidence interval is a way of doing estimation for a unknown parameter. For example, we use the sample mean to form a confidence interval for the population mean.</p>
<p>We <em>NEVER say</em> <span class="red"><em>“The confidence interval of the sample mean, <span class="math inline">\(\overline{X}\)</span>, is ….”</em></span> We SAY <span class="red"><em>“The confidence interval for the true population mean <span class="math inline">\(\mu\)</span>, is …”</em></span></p>
<p>In general, a confidence interval for <span class="math inline">\(\mu\)</span> has the form</p>
<center>
<span class="math inline">\(\large \overline{x} \pm m = (\overline{x} - m, \overline{x} + m)\)</span>
</center>
<p>The <span class="math inline">\(m\)</span> is called the <strong>margin of error</strong>. It controls the width of the interval <span class="math inline">\(2m\)</span>. The CI is centered at the sample mean, and <span class="math inline">\(\overline{x} - m\)</span> is the <strong>lower bound</strong> and <span class="math inline">\(\overline{x} + m\)</span> is the <strong>upper bound</strong> of the confidence interval. The point estimate, <span class="math inline">\(\overline{x}\)</span>, and margin of error, <span class="math inline">\(m\)</span>, can be obtained from known quantities and our data once sampled.</p>
<hr>
<p><span style="color:blue"> <strong><span class="math inline">\((1 - \alpha)100\%\)</span> Confidence Intervals</strong> </span></p>
<p>Formally, for <span class="math inline">\(0 \le \alpha \le 1\)</span>, we define the <strong>confidence level</strong> <span class="math inline">\(1-\alpha\)</span> as <em>the proportion of times that the CI contains the population parameter, assuming that the estimation process is repeated a large number of times</em>.</p>
<p>The confidence level can be any number between zero and one. Common choices for the confidence level include 90% <span class="math inline">\((\alpha = 0.10)\)</span>, 95% <span class="math inline">\((\alpha = 0.05)\)</span> and 99% <span class="math inline">\((\alpha = 0.01)\)</span>. Keep in mind that confidence level tells us the reliability of the interval. Because precision and reliability have a trade-off relationship, a CI with very high confidence level (high reliability) will have less precision, i.e., larger margin of error and with width of the interval. 95% is the most common level because it has a good balance between precision (width of the CI) and reliability (confidence level).</p>
<ul>
<li>
<span style="color:blue"> <strong>High reliability and Low precision</strong>: I am 100% confident that the mean height of Marquette students is between 3’0” and 8’0”. </span>
<ul>
<li>Duh…🤷</li>
</ul>
</li>
<li>
<span style="color:blue"> <strong>Low reliability and High precision</strong>: I am 20% confident that mean height of Marquette students is between 5’6” and 5’7”. </span>
<ul>
<li>This is far from the truth… 🙅</li>
</ul>
</li>
</ul>
<hr>
<p><span style="color:blue"> <strong><span class="math inline">\(95\%\)</span> Confidence Intervals for <span class="math inline">\(\mu\)</span></strong> </span></p>
<p>We’ve learned the general form of a confidence interval for <span class="math inline">\(\mu\)</span> and defined the confidence level. We now formally derive the form of the <span class="math inline">\((1-\alpha)100\%\)</span> confidence interval for <span class="math inline">\(\mu\)</span>. For simplicity, here we assume <span class="math inline">\(\sigma\)</span> is known to us when the interval is constructed. A confidence interval can be derived from the sampling distribution of the point estimator. Such approach is called the <strong>distribution-based approach</strong>. A confidence interval can also be derived using simulation, and such approach is called <strong>simulation-based approach</strong>, bootstraping method for example. This chapter we build a CI based on the sampling distribution of <span class="math inline">\(\overline{X}\)</span>. We discuss bootstraping in <a href="infer-bt.html"><span>Chapter&nbsp;14</span></a>.</p>
<!-- <span style="color:red"> ***Z-score*** </span> -->
<p>Suppose we want to obtain the <span class="math inline">\(95\%\)</span> confidence interval for <span class="math inline">\(\mu\)</span>. So <span class="math inline">\(\alpha = 0.05\)</span>. We start with the sampling distribution of <span class="math inline">\(\overline{X} \sim N\left(\mu, \frac{\sigma^2}{n}\right)\)</span> shown in <a href="#fig-ci-95">Figure&nbsp;<span>13.4</span></a>. The sampling distribution tells us that the realized value <span class="math inline">\(\overline{x}\)</span> will be within 1.96 SDs of the population mean, <span class="math inline">\(\mu\)</span>, <span class="math inline">\(95\%\)</span> of the time. In other words,</p>
<p><span class="math display">\[P\left(\mu-1.96\frac{\sigma}{\sqrt{n}} &lt; \overline{X} &lt; \mu + 1.96\frac{\sigma}{\sqrt{n}} \right) = 0.95\]</span></p>
<p>Here the <span class="math inline">\(z\)</span>-score of 1.96 is the 97.5% percentile of the standard normal distribution and -1.96 is the 2.5% percentile. The <span class="math inline">\(z\)</span>-score 1.96 is associated with 2.5% area <em>to the right</em> and is called a <strong>critical value</strong> denoted as <strong><span class="math inline">\(z_{0.025} = z_{\alpha/2}\)</span> </strong>. The <span class="math inline">\(z\)</span>-score -1.96 is associated with 2.5% area <em>to the left</em>, and it happens to be the negative value of <span class="math inline">\(z_{0.025}\)</span> because of the symmetry of normal distribution.</p>
<!-- So the middle area under the normal density curve is 95%. -->
<!-- ::::{.columns} -->
<!-- :::{.column width="50%"} -->
<!-- - $\alpha = 0.05$ -->
<!-- - Start with the sampling distribution of $\overline{X} \sim N\left(\mu, \frac{\sigma^2}{n}\right)$ -->
<!-- - $\overline{x}$ will be within 1.96 SDs of the population mean, $\mu$, $95\%$ of the time. -->
<!-- - The $z$-score of 1.96 is associated with 2.5% area *to the right* and is called a **critical value** denoted as **$z_{0.025}$ **. -->
<!-- ::: -->
<!-- :::{.column width="50%"} -->
<div class="cell" data-layout-align="center" data-fig.asp="0.5">
<div class="cell-output-display">
<div id="fig-ci-95" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="infer-ci_files/figure-html/fig-ci-95-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;13.4: Sampling distribution of the sample mean with 95% probability in the middle.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<!-- ::: -->
<!-- :::: -->
<!-- <span style="color:red"> ***Probability*** </span> -->
<!-- ::::{.columns} -->
<!-- :::{.column width="50%"} -->
<p>We learned that <span class="math display">\[P\left(\mu-1.96\frac{\sigma}{\sqrt{n}} &lt; \overline{X} &lt; \mu + 1.96\frac{\sigma}{\sqrt{n}} \right) = 0.95.\]</span> The probability that the variable <span class="math inline">\(\overline{X}\)</span> is in the interval <span class="math inline">\(\left(\mu-1.96\frac{\sigma}{\sqrt{n}}, \mu+1.96\frac{\sigma}{\sqrt{n}} \right)\)</span> is 95%. But is the interval <span class="math inline">\(\left(\mu-1.96\frac{\sigma}{\sqrt{n}}, \mu+1.96\frac{\sigma}{\sqrt{n}} \right)\)</span> our confidence interval?</p>
<p>The answer is No ❌! Remember that we don’t know <span class="math inline">\(\mu\)</span> and we are estimating it. The interval cannot be determined because it involves the unknown quantity <span class="math inline">\(\mu\)</span>. But don’t be too disappointed. We are almost there.</p>
<!-- :::{.callout-note icon=false} -->
<!-- ## Is the interval $\left(\mu-1.96\frac{\sigma}{\sqrt{n}}, \mu+1.96\frac{\sigma}{\sqrt{n}} \right)$ our confidence interval? -->
<!-- - ❌ **No! We don't know $\mu$, which is the quantity we want to estimate, but we're almost there!** -->
<!-- ::: -->
<!-- ::: -->
<!-- :::{.column width="50%"} -->
<!-- ```{r ref.label='ci_95', echo=FALSE, out.width='100%'} -->
<!-- ``` -->
<!-- ::: -->
<!-- :::: -->
<!-- <span style="color:red"> ***Formula*** -->
<!-- ::::{.columns} -->
<!-- :::{.column width=50%} -->
<p>We can arrange the inequality in the probability so that <span class="math inline">\(\mu\)</span> is in the middle and the probability remains unchanged.</p>
<ul>
<li><p><span class="math display">\[ \mu-1.96\frac{\sigma}{\sqrt{n}} &lt; \overline{X} \iff \mu &lt; \overline{X} + 1.96\frac{\sigma}{\sqrt{n}}\]</span></p></li>
<li><p><span class="math display">\[ \overline{X}  &lt; \mu+ 1.96\frac{\sigma}{\sqrt{n}} &lt; \iff \overline{X} - 1.96\frac{\sigma}{\sqrt{n}} &lt; \mu\]</span></p></li>
<li><p><span class="math display">\[\mu-1.96\frac{\sigma}{\sqrt{n}} &lt; \overline{X} &lt; \mu + 1.96\frac{\sigma}{\sqrt{n}} \iff \overline{X}-1.96\frac{\sigma}{\sqrt{n}} &lt; \mu &lt; \overline{X} + 1.96\frac{\sigma}{\sqrt{n}}\]</span></p></li>
</ul>
<p><span class="math display">\[\small \begin{align} P\left(\mu-1.96\frac{\sigma}{\sqrt{n}} &lt; \overline{X} &lt; \mu + 1.96\frac{\sigma}{\sqrt{n}} \right) =
P\left( \boxed{\overline{X}-1.96\frac{\sigma}{\sqrt{n}} &lt; \mu &lt; \overline{X} + 1.96\frac{\sigma}{\sqrt{n}}} \right) = 0.95
\end{align}\]</span></p>
<p>We are done! <span style="color:blue"> With sample data of size <span class="math inline">\(n\)</span>, <span class="math inline">\(\left(\overline{x}-1.96\frac{\sigma}{\sqrt{n}}, \overline{x} + 1.96\frac{\sigma}{\sqrt{n}}\right)\)</span> is our <span class="math inline">\(95\%\)</span> CI for <span class="math inline">\(\mu\)</span>. </span> Note that if <span class="math inline">\(\sigma\)</span> is <strong>known</strong> to us, the interval can be computed from our data because we know the sample size, and we can get the sample mean. The margin of error <span class="math inline">\(m = 1.96\frac{\sigma}{\sqrt{n}}\)</span>. <!-- ::: --></p>
<!-- :::{.column width="50%"} -->
<!-- ::: -->
<!-- :::: -->
</section><section id="confidence-intervals-for-mu-when-sigma-is-known" class="level2" data-number="13.3"><h2 data-number="13.3" class="anchored" data-anchor-id="confidence-intervals-for-mu-when-sigma-is-known">
<span class="header-section-number">13.3</span> Confidence Intervals for <span class="math inline">\(\mu\)</span> When <span class="math inline">\(\sigma\)</span> is Known</h2>
<p>We just obtained the 95% confident interval for <span class="math inline">\(\mu\)</span>. How about the general <span class="math inline">\((1-\alpha)100%\)</span> confident interval for <span class="math inline">\(\mu\)</span> (when <span class="math inline">\(\sigma\)</span> is known)? We first introduce the requirements for constructing the interval, then provide the interval formula.</p>
<p>The requirements for estimating <span class="math inline">\(\mu\)</span> when <span class="math inline">\(\sigma\)</span> is known include</p>
<ul>
<li>👉 The sample should be a <em>random sample</em>, such that all data <span class="math inline">\(X_i\)</span> are drawn from the same population and <span class="math inline">\(X_i\)</span> and <span class="math inline">\(X_j\)</span> are independent. In fact, <span style="color:blue"> any methods in this course are based on the assumption of a random sample </span>
</li>
<li>👉 The population standard deviation, <span class="math inline">\(\sigma\)</span>, is <em>known</em>.</li>
<li>👉 The population is either <em>normally distributed</em>, <span class="math inline">\(n &gt; 30\)</span> or both, i.e., <span class="math inline">\(X_i \sim N(\mu, \sigma^2)\)</span>. <span style="color:blue"> The sample size <span class="math inline">\(n &gt; 30\)</span> allows the central limit theorem to be applied and hence normality is satisfied. </span>
</li>
</ul>
<!-- ------------------------------------------------------------------- --><!-- <span style="color:blue"> **$(1-\alpha)100\%$ Confidence Intervals for $\mu$** </span> --><!-- ::::{.columns} --><!-- :::{.column width="50%"} --><!-- ```{r ref.label='ci_95', echo=FALSE, out.width='100%'} --><!-- ``` --><p>The general <span class="math inline">\((1-\alpha)100\%\)</span> confidence interval for <span class="math inline">\(\mu\)</span> can be borrowed from the <span class="math inline">\(95\%\)</span> confidence interval for <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\left(\overline{x}-z_{0.025}\frac{\sigma}{\sqrt{n}}, \overline{x} + z_{0.025}\frac{\sigma}{\sqrt{n}}\right)\)</span>. The 95% confidence level means <span class="math inline">\(\alpha = 0.05\)</span>. For the general <span class="math inline">\((1-\alpha)100\%\)</span> confidence interval, we just replace <span class="math inline">\(z_{0.025}\)</span> with <span class="math inline">\(z_{\alpha/2}\)</span> for any <span class="math inline">\(\alpha\)</span> between zero and one. Therefore, the general <span class="math inline">\((1-\alpha)100\%\)</span> confidence interval for <span class="math inline">\(\mu\)</span> is</p>
<!-- <center> -->
<!-- <span style="color:red"> $\left(\overline{x}-z_{\alpha/2}\frac{\sigma}{\sqrt{n}},  \overline{x} + z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\right)$ </span> -->
<!-- </center> -->
<!-- <center> -->
<!-- <span style="color:blue"> $\left(\overline{x}-1.96\frac{\sigma}{\sqrt{n}},  \overline{x} + 1.96\frac{\sigma}{\sqrt{n}}\right)$ </span> -->
<!-- <span style="color:blue"> $\left(\overline{x}-z_{0.025}\frac{\sigma}{\sqrt{n}},  \overline{x} + z_{0.025}\frac{\sigma}{\sqrt{n}}\right)$ </span> -->
<!-- </center> -->
<!-- ::: -->
<!-- :::{.column width="50%"} -->
<div class="cell" data-layout-align="center" data-fig.asp="0.5">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="infer-ci_files/figure-html/ci-alpha-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- <center> -->
<!-- <span style="color:red"> $\left(\overline{x}-z_{\alpha/2}\frac{\sigma}{\sqrt{n}},  \overline{x} + z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\right)$ </span> -->
<!-- </center> -->
<!-- ::: -->
<!-- :::: -->
<!-- <br> -->
<p>To sum up, we provide procedures for constructing a confidence interval for <span class="math inline">\(\mu\)</span> when <span class="math inline">\(\sigma\)</span> is known:</p>
<ol type="1">
<li><p>Check that the requirements are satisfied.</p></li>
<li><p>Decide <span class="math inline">\(\alpha\)</span> or the <em>confidence level</em> <span class="math inline">\((1 - \alpha)\)</span>.</p></li>
<li><p>Find the <em>critical value</em>, <span class="math inline">\(z_{\alpha/2}\)</span>.</p></li>
<li><p>Evaluate <em>margin of error</em>, <span class="math inline">\(m = z_{\alpha/2} \cdot \frac{\sigma}{\sqrt{n}}\)</span>.</p></li>
<li><p>Construct the <span class="math inline">\((1 - \alpha)100\%\)</span> CI for <span class="math inline">\(\mu\)</span> using the sample mean, <span class="math inline">\(\overline{x}\)</span>, and margin of error, <span class="math inline">\(m\)</span>:</p></li>
</ol>
<center>
<span style="color:red"> <span class="math display">\[\boxed{\overline{x} \pm z_{\alpha/2}\frac{\sigma}{\sqrt{n}} \text{  or  } \left( \overline{x} -z_{\alpha/2}\frac{\sigma}{\sqrt{n}}, \, \overline{x} + z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\right)}\]</span></span>
</center>
<hr>
<p><span style="color:blue"> <strong>Example</strong> </span></p>
<div class="columns">
<div class="column" style="width:70%;">
<p>Suppose we want to know the <em>mean</em> systolic blood pressure (SBP) of a population. Assume that the population distribution is <em>normal</em> and has a standard deviation of 5 mmHg. We have a <em>random sample</em> of 16 subjects from this population with a mean of 121.5 mmHg. Estimate the mean SBP with a 95% confidence interval.</p>
</div><div class="column" style="width:20%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/img-infer/blood_pressure.jpeg" class="img-fluid figure-img" width="2360"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>We construct the confidence interval step by step using the procedure.</p>
<ol type="1">
<li>Requirements:
<ul>
<li><span style="color:blue"> Normality is assumed, <span class="math inline">\(\sigma = 5\)</span> is known and a random sample is collected.</span></li>
</ul>
</li>
<li>Decide <span class="math inline">\(\alpha\)</span>:
<ul>
<li><span style="color:blue"> <span class="math inline">\(\alpha = 0.05\)</span> </span></li>
</ul>
</li>
<li>Find the <em>critical value</em> <span class="math inline">\(z_{\alpha/2}\)</span>:
<ul>
<li><span style="color:blue"> <span class="math inline">\(z_{\alpha/2} = z_{0.025} = 1.96\)</span> </span></li>
</ul>
</li>
<li>Evaluate <em>margin of error</em> <span class="math inline">\(m = z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\)</span>:
<ul>
<li><span style="color:blue"> <span class="math inline">\(m = (1.96) \frac{5}{\sqrt{16}} = 2.45\)</span> </span></li>
</ul>
</li>
<li>Construct the <span class="math inline">\((1 - \alpha)100\%\)</span> CI:
<ul>
<li><span style="color:blue"> The 95% CI for the mean SBP is <span class="math inline">\(\overline{x} \pm z_{\alpha/2}\frac{\sigma}{\sqrt{n}} = (121.5 -2.45, 121.5 + 2.45) = (119.05, 123.95)\)</span> </span></li>
</ul>
</li>
</ol>
<!-- <span style="color:red"> ***Computation in R*** </span> --><p>Below is a demonstration of how to find the 95% CI for SBP using R.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## save all information we have</span></span>
<span><span class="va">alpha</span> <span class="op">&lt;-</span> <span class="fl">0.05</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">16</span></span>
<span><span class="va">x_bar</span> <span class="op">&lt;-</span> <span class="fl">121.5</span></span>
<span><span class="va">sig</span> <span class="op">&lt;-</span> <span class="fl">5</span></span>
<span></span>
<span><span class="co">## 95% CI</span></span>
<span><span class="co">## z-critical value</span></span>
<span><span class="op">(</span><span class="va">cri_z</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span>p <span class="op">=</span> <span class="va">alpha</span> <span class="op">/</span> <span class="fl">2</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">)</span>  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## margin of error</span></span>
<span><span class="op">(</span><span class="va">m_z</span> <span class="op">&lt;-</span> <span class="va">cri_z</span> <span class="op">*</span> <span class="op">(</span><span class="va">sig</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.449955</code></pre>
</div>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## 95% CI for mu when sigma is known</span></span>
<span><span class="va">x_bar</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span> <span class="op">*</span> <span class="va">m_z</span>  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 119.05 123.95</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Construct a 99% CI for the mean SBP. Do you expect it to have a wider or narrower interval than the 95% CI? Why?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p><span style="color:red"> <strong><em>Interpreting the Confidence Interval</em></strong></span></p>
<p>We have known how to construct a confidence interval. But what on earth is that? How do we interpret the interval correctly? This is pretty important because the interval is usually misinterpreted and inappropriately used in statistical analysis. Don’t blame yourself if you find it hard to understand the meaning. The confidence interval concept is not intuitive, and it does not really answer what we care about the unknown parameter. The confidence interval is a concept in the classical or frequestist point of view. Another way of interval estimation is to use the so called <strong>credible interval</strong> that uses Bayesian philosophy. We will discuss their difference in detail in <a href="infer-bayes.html"><span>Chapter&nbsp;20</span></a>.</p>
<p>Back to a 95% confidence interval. The following statements and interpretations are wrong. Please do not interpret the interval this way.</p>
<ul>
<li><p><strong>WRONG</strong> ❌ <em>“There is a 95% chance/probability that the true population mean will fall between 119.1 mm and 123.9 mm.”</em></p></li>
<li><p><strong>WRONG</strong> ❌ <em>“The probability that the true population mean falls between 119.1 mm and 123.9 mm is 95%.”</em></p></li>
</ul>
<p>Although those statements are often what we want, they are completely wrong. Let’s learn why. <em>The sample mean is a random variable with a sampling distribution, so it makes sense to compute a probability of it being in some interval.</em> <em>The population mean is unknown and FIXED, so we cannot assign or compute any probability of it.</em> If we were using Bayesian inference <a href="infer-bayes.html"><span>Chapter&nbsp;20</span></a>, a different inference method, we could compute a probability associated with <span class="math inline">\(\mu\)</span> because in Bayesian statistics <span class="math inline">\(\mu\)</span> is treated as a random variable.</p>
<p>So how do we correctly interpret a confidence interval? Here is the answer.</p>
<p><span style="color:blue"> <strong><em>“We are 95% confident that the mean SBP lies between 119.1 mm and 123.9 mm.”</em></strong> </span></p>
<p>But still what does “95% confident” really mean? This means if <em>we were able to collect our data many times and build the corresponding CIs, we would expect that about 95% of those intervals would contain the true population parameter</em>, which, in this case, is the mean systolic blood pressure.</p>
<p>Remember that <em><span class="math inline">\(\overline{x}\)</span> varies from sample to sample, so does its corresponding CI</em> because the CI is a function of <span class="math inline">\(\overline{X}\)</span> given <span class="math inline">\(n\)</span> and <span class="math inline">\(\sigma\)</span>. This idea is shown in <a href="#fig-ci">Figure&nbsp;<span>13.5</span></a>. Here we do a simulation assuming <span class="math inline">\(\mu\)</span> is known at 120, and <span class="math inline">\(\sigma = 5\)</span>. Also, assume we were able to repeatedly collect our sample of the same size <span class="math inline">\(n = 16\)</span>. Here 100 data sets are generated, and for each data set, the sample mean and its corresponding 95% CI are computed. Since the confidence level is 95%, 95% of those intervals would contain the true population parameter, 120 in this example. The 36th, 45th, 52nd, 82nd, and 99th data sets have the interval not capturing the true parameter.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-ci" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="infer-ci_files/figure-html/fig-ci-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;13.5: Illustration of 100 95% confidence intervals.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please keep the following ideas in mind.</p>
<ol type="1">
<li><p>A 95% CI does not mean that if 100 data sets are collected, there will be exactly 95 intervals capturing <span class="math inline">\(\mu\)</span>. It is a long-term sampling idea.</p></li>
<li><p>We never know with certainty that 95% of the intervals, or any single interval for that matter, contains the true population parameter because again we never know what the true value of the parameter is.</p></li>
<li><p>In reality, we usually have only one data set, and we are not able to collect more data. We have no idea of whether our 95% confidence interval capture the unknown parameter or not. We are only “95% confident”.</p></li>
</ol>
</div>
</div>
<p>The procedure of generating 100 confidence intervals for <span class="math inline">\(\mu\)</span> when <span class="math inline">\(\sigma\)</span> is known is shown in the algorithm below.</p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">Algorithm</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Simulation Result</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="instructions">
<p><strong>Algorithm</strong></p>
<ol type="1">
<li><p>Generate 100 sampled data of size <span class="math inline">\(n\)</span>: <span class="math inline">\((x_1^1, x_2^1, \dots, x_n^1), \dots (x_1^{100}, x_2^{100}, \dots, x_n^{100})\)</span>, where <span class="math inline">\(x_i^m \sim N(\mu, \sigma^2)\)</span>.</p></li>
<li><p>Obtain 100 sample means <span class="math inline">\((\overline{x}^1, \dots, \overline{x}^{100})\)</span>.</p></li>
<li><p>For each <span class="math inline">\(m = 1, 2, \dots, 100\)</span>, compute the corresponding confidence interval <span class="math display">\[\left(\overline{x}^m - z_{\alpha/2} \frac{\sigma}{\sqrt{n}}, \overline{x}^m + z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\right)\]</span></p></li>
</ol>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell" data-layout-align="center" data-hash="infer-ci_cache/html/unnamed-chunk-14_565f82019d7d15c507f97869877e83b9">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="infer-ci_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mu</span> <span class="op">&lt;-</span> <span class="fl">120</span>; <span class="va">sig</span> <span class="op">&lt;-</span> <span class="fl">5</span> </span>
<span><span class="va">al</span> <span class="op">&lt;-</span> <span class="fl">0.05</span>; <span class="va">M</span> <span class="op">&lt;-</span> <span class="fl">100</span>; <span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">16</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">2023</span><span class="op">)</span></span>
<span><span class="va">x_rep</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">replicate</a></span><span class="op">(</span><span class="va">M</span>, <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span>, <span class="va">mu</span>, <span class="va">sig</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">xbar_rep</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">x_rep</span>, <span class="fl">2</span>, <span class="va">mean</span><span class="op">)</span></span>
<span><span class="va">E</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span>p <span class="op">=</span> <span class="fl">1</span> <span class="op">-</span> <span class="va">al</span> <span class="op">/</span> <span class="fl">2</span><span class="op">)</span> <span class="op">*</span> <span class="va">sig</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span></span>
<span><span class="va">ci_lwr</span> <span class="op">&lt;-</span> <span class="va">xbar_rep</span> <span class="op">-</span> <span class="va">E</span></span>
<span><span class="va">ci_upr</span> <span class="op">&lt;-</span> <span class="va">xbar_rep</span> <span class="op">+</span> <span class="va">E</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="cn">NULL</span>, xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/range.html">range</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">ci_lwr</span>, <span class="va">ci_upr</span><span class="op">)</span><span class="op">)</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">100</span><span class="op">)</span>, </span>
<span>     xlab <span class="op">=</span> <span class="st">"95% CI"</span>, ylab <span class="op">=</span> <span class="st">"Sample"</span>, las <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">mu_out</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">mu</span> <span class="op">&lt;</span> <span class="va">ci_lwr</span> <span class="op">|</span> <span class="va">mu</span> <span class="op">&gt;</span> <span class="va">ci_upr</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/segments.html">segments</a></span><span class="op">(</span>x0 <span class="op">=</span> <span class="va">ci_lwr</span>, y0 <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="va">M</span>, x1 <span class="op">=</span> <span class="va">ci_upr</span>, col <span class="op">=</span> <span class="st">"navy"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/segments.html">segments</a></span><span class="op">(</span>x0 <span class="op">=</span> <span class="va">ci_lwr</span><span class="op">[</span><span class="va">mu_out</span><span class="op">]</span>, y0 <span class="op">=</span> <span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">M</span><span class="op">)</span><span class="op">[</span><span class="va">mu_out</span><span class="op">]</span>, x1 <span class="op">=</span> <span class="va">ci_upr</span><span class="op">[</span><span class="va">mu_out</span><span class="op">]</span>, </span>
<span>         col <span class="op">=</span> <span class="fl">2</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span>v <span class="op">=</span> <span class="va">mu</span>, col <span class="op">=</span> <span class="st">"#FFCC00"</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="confidence-intervals-for-mu-when-sigma-is-unknown" class="level2" data-number="13.4"><h2 data-number="13.4" class="anchored" data-anchor-id="confidence-intervals-for-mu-when-sigma-is-unknown">
<span class="header-section-number">13.4</span> Confidence Intervals for <span class="math inline">\(\mu\)</span> When <span class="math inline">\(\sigma\)</span> is Unknown</h2>
<p>We complete the discussion of confidence intervals for <span class="math inline">\(\mu\)</span> when <span class="math inline">\(\sigma\)</span> is known. Do you see anything unreasonable? Do you think that assuming <span class="math inline">\(\sigma^2\)</span> is known is reasonable? In fact, the population variance is calculated as <span class="math inline">\(\sigma^2 = \frac{\sum_{i=1}^{N}(x_i - \mu)^2}{N}\)</span>, where <span class="math inline">\(N\)</span> is the population size. The formula involves <span class="math inline">\(\mu\)</span>, the unknown parameter we’d like to estimate. It’s rare that we don’t know <span class="math inline">\(\mu\)</span> but know <span class="math inline">\(\sigma\)</span>. What do we do if <span class="math inline">\(\sigma\)</span> is unknown?</p>
<p>When <span class="math inline">\(\sigma\)</span> is unknown to us, we cannot use normal distribution anymore. Instead, we use the <strong>Student’s t</strong> distribution (or <span class="math inline">\(t\)</span>-distribution) to construct a confidence interval for <span class="math inline">\(\mu\)</span> when <span class="math inline">\(\sigma\)</span> is <strong>unknown</strong>. To construct these confidence intervals we still need</p>
<ul>
<li>A random sample</li>
<li>A population that is normally distributed and/or <span class="math inline">\(n &gt; 30\)</span>.</li>
</ul>
<p>The confidence interval when <span class="math inline">\(\sigma\)</span> is known includes <span class="math inline">\(\sigma\)</span> in the formula. When <span class="math inline">\(\sigma\)</span> is unknown, we cannot use the formula and need to find <span class="math inline">\(\sigma\)</span>’s surrogate.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
What is a natural estimator for the unknown <span class="math inline">\(\sigma\)</span>?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>When <span class="math inline">\(\sigma\)</span> is unknown, we use the <em>sample standard deviation</em>, <span class="math inline">\(S = \sqrt{\frac{\sum_{i=1}^{n}(X_i - \overline{X})^2}{n-1}}\)</span>, instead when constructing the CI.</p>
<hr>
<p><span style="color:blue"> <strong>Student’s t Distribution</strong> </span></p>
<p>If the population is normally distributed or <span class="math inline">\(n &gt; 30\)</span>, we know <span class="math inline">\(\overline{X}\)</span> is exactly or approximately <span class="math inline">\(N\left(\mu, \frac{\sigma^2}{n} \right)\)</span>. Therefore <span class="math inline">\(Z = \frac{\overline{X} - \mu}{\color{red}\sigma/\sqrt{n}} \sim N(0, 1)\)</span>. Now if <span class="math inline">\(\sigma\)</span> is replaced with its surrogate <span class="math inline">\(S\)</span>, then the new random variable say <span class="math inline">\(T\)</span> will be student’s t distributed with the <strong>degrees of freedom (df)</strong> <span class="math inline">\(n-1\)</span>:</p>
<p><span style="color:blue"> <span class="math display">\[T = \frac{\overline{X} - \mu}{\color{red}S/\sqrt{n}} \sim t_{n-1}\]</span> </span> <!-- + $t_{n-1}$ denotes the Student t distribution with **degrees of freedom (df)** $n-1$. --></p>
<p>Here the degrees of freedom is the parameter of the student’s t distribution.</p>
<p><span style="color:red"> <strong><em>Properties</em></strong> </span></p>
<p>The student’s t distribution, as shown in <a href="#fig-student-t">Figure&nbsp;<span>13.6</span></a>, looks pretty similar to the standard normal distribution, but they are different. Some of the properties of the student’s t distribution are listed below.</p>
<ul>
<li><p>For any degrees of freedom, the student’s t distribution is symmetric about the mean 0 and bell-shaped like <span class="math inline">\(N(0, 1)\)</span>.</p></li>
<li><p>For any degrees of freedom, the student’s t distribution has more variability than <span class="math inline">\(N(0, 1)\)</span>, meaning that the distribution has heavier tails and lower peak.</p></li>
<li><p>The the student’s t distribution has less variability for larger degrees of freedom (sample size).</p></li>
<li><p>As <span class="math inline">\(n \rightarrow \infty\)</span> <span class="math inline">\((df \rightarrow \infty)\)</span>, the student’s t distribution approaches <span class="math inline">\(N(0, 1)\)</span>.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-student-t" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="infer-ci_files/figure-html/fig-student-t-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;13.6: Student t distributions with various degrees of freedom.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><span style="color:blue"> <strong>Critical Values of <span class="math inline">\(t_{\alpha/2, n-1}\)</span></strong> </span></p>
<p>In the CI formula with known <span class="math inline">\(\sigma\)</span>, we use the critical value <span class="math inline">\(z_{\alpha/2}\)</span>, the standard normal value so that <span class="math inline">\(P(Z &gt; z_{\alpha/2}) = \alpha/2\)</span>. When <span class="math inline">\(\sigma\)</span> is unknown, we use <span class="math inline">\(t_{\alpha/2, n - 1}\)</span> as the critical value, instead of <span class="math inline">\(z_{\alpha/2}\)</span>. Notice that the standard normal has nothing to do with <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> of a general <span class="math inline">\(N(\mu, \sigma^2)\)</span> distribution. <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Therefore no parameter is attached to <span class="math inline">\(z_{\alpha/2}\)</span>. However, the <span class="math inline">\(t\)</span> critical value <span class="math inline">\(t_{\alpha/2, n - 1}\)</span> changes with the degrees of freedom <span class="math inline">\(n - 1\)</span>. With the same logic, the critical value <span class="math inline">\(t_{\alpha/2, n - 1}\)</span> is a Student’s t value with degrees of freedom <span class="math inline">\(n - 1\)</span> so that <span class="math inline">\(P(T_{n-1} &gt; t_{\alpha/2, n - 1}) = \alpha/2\)</span> as shown in <a href="#fig-cv-t">Figure&nbsp;<span>13.7</span></a>.</p>
<div class="cell" data-layout-align="center" data-fig.asp="0.5">
<div class="cell-output-display">
<div id="fig-cv-t" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="infer-ci_files/figure-html/fig-cv-t-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;13.7: Illustration of critical value for Student t distribution.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
With the same <span class="math inline">\(\alpha\)</span>, is <span class="math inline">\(t_{\alpha, n-1}\)</span> or <span class="math inline">\(z_{\alpha}\)</span> larger?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>You should be able to answer this question based on the fact that for any degrees of freedom, the student’s t distribution has more variability than <span class="math inline">\(N(0, 1)\)</span>, or heavier tails. The heavier tail forces <span class="math inline">\(t_{\alpha/2, n-1}\)</span> to be more extreme than <span class="math inline">\(z_{\alpha/2}\)</span>. <a href="#fig-cri-val">Figure&nbsp;<span>13.8</span></a> illustrates this fact. The red <span class="math inline">\(t_{df = 2}\)</span> distribution has heavier tails than the black standard normal distribution.</p>
<div class="cell" data-layout-align="center" data-fig.asp="0.5">
<div class="cell-output-display">
<div id="fig-cri-val" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="infer-ci_files/figure-html/fig-cri-val-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;13.8: z and t critical values.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The table below shows <span class="math inline">\(z\)</span> and <span class="math inline">\(t\)</span> critical values at confidence level 90%, 95% and 99%. The <span class="math inline">\(t\)</span> values are getting closer to the <span class="math inline">\(z\)</span> values as the degree of freedom increases. When the degree of freedom goes to infinity, the <span class="math inline">\(t\)</span> values converge to <span class="math inline">\(z\)</span> values.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 18%">
<col style="width: 17%">
<col style="width: 8%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Level</th>
<th style="text-align: center;">t df = 5</th>
<th style="text-align: center;">t df = 15</th>
<th style="text-align: center;">t df = 30</th>
<th style="text-align: center;">t df = 1000</th>
<th style="text-align: center;">t df = inf</th>
<th style="text-align: center;">z</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">90%</td>
<td style="text-align: center;">2.02</td>
<td style="text-align: center;">1.75</td>
<td style="text-align: center;">1.70</td>
<td style="text-align: center;">1.65</td>
<td style="text-align: center;">1.64</td>
<td style="text-align: center;">1.64</td>
</tr>
<tr class="even">
<td style="text-align: center;">95%</td>
<td style="text-align: center;">2.57</td>
<td style="text-align: center;">2.13</td>
<td style="text-align: center;">2.04</td>
<td style="text-align: center;">1.96</td>
<td style="text-align: center;">1.96</td>
<td style="text-align: center;">1.96</td>
</tr>
<tr class="odd">
<td style="text-align: center;">99%</td>
<td style="text-align: center;">4.03</td>
<td style="text-align: center;">2.95</td>
<td style="text-align: center;">2.75</td>
<td style="text-align: center;">2.58</td>
<td style="text-align: center;">2.58</td>
<td style="text-align: center;">2.58</td>
</tr>
</tbody>
</table>
</div>
</div>
<hr>
<p><span style="color:blue"> <strong><span class="math inline">\((1-\alpha)100\%\)</span> Confidence Intervals for <span class="math inline">\(\mu\)</span> When <span class="math inline">\(\sigma\)</span> is Unknown</strong> </span></p>
<p>We have been equipped with everything we need for constructing <span class="math inline">\((1-\alpha)100\%\)</span> confidence interval for <span class="math inline">\(\mu\)</span> when <span class="math inline">\(\sigma\)</span> is unknown. The interval is <span style="color:blue"> <span class="math display">\[\left(\overline{x} - t_{\alpha/2, n-1} \frac{s}{\sqrt{n}}, \overline{x} + t_{\alpha/2, n-1} \frac{s}{\sqrt{n}}\right)\]</span> </span></p>
<p>The interval form is the same as before. We have the sample mean plus and minus the margin of error. Comparing to the interval with known <span class="math inline">\(\sigma\)</span>, the difference is that <span class="math inline">\(z_{\alpha/2}\)</span> is replaced with <span class="math inline">\(t_{\alpha/2, n-1}\)</span>, and <span class="math inline">\(\sigma\)</span> is replaced with <span class="math inline">\(s\)</span>.</p>
<p>Given the same confidence level <span class="math inline">\(1-\alpha\)</span>, <span class="math inline">\(t_{\alpha/2, n-1} &gt; z_{\alpha/2}\)</span>, leading to a wider interval if <span class="math inline">\(s\)</span> is not too smaller than the true <span class="math inline">\(\sigma\)</span>. The intuition is that we are more uncertain when doing inference about <span class="math inline">\(\mu\)</span> because we don’t have information about both <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>, and replacing <span class="math inline">\(\sigma\)</span> with <span class="math inline">\(s\)</span> adds additional uncertainty.</p>
<!-- and it means that the confidence interval for $\mu$ is wider when $\sigma$ is unknown. -->
<!-- :::{.callout-note} -->
<!-- - We are more "uncertain" when doing inference about $\mu$ because don't have information about $\sigma$ and replacing it with $s$ adds additional uncertainty. -->
<!-- ::: -->
<p><span style="color:red"> <strong><em>Computation in R</em></strong> </span></p>
<p>Back to the systolic blood pressure (SBP) example. We have <span class="math inline">\(n=16\)</span> and <span class="math inline">\(\overline{x} = 121.5\)</span>. Estimate the mean SBP with a 95% confidence interval with <em>unknown <span class="math inline">\(\sigma\)</span> and <span class="math inline">\(s = 5\)</span>.</em> The code for the <span class="math inline">\(t\)</span> interval is pretty similar to the <span class="math inline">\(z\)</span> interval. The main difference is that we are gonna use <code><a href="https://rdrr.io/r/stats/TDist.html">qt()</a></code> to find a quantile or critical value from the Student’s t distribution. In the function, the first argument is still the given probability, then we must specify the degrees of freedom, otherwise R cannot determine which <span class="math inline">\(t\)</span>-distribution is being considered, and will render an error message.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">alpha</span> <span class="op">&lt;-</span> <span class="fl">0.05</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">16</span></span>
<span><span class="va">x_bar</span> <span class="op">&lt;-</span> <span class="fl">121.5</span></span>
<span><span class="va">s</span> <span class="op">&lt;-</span> <span class="fl">5</span>  <span class="co">## sigma is unknown and s = 5</span></span>
<span></span>
<span><span class="co">## t-critical value</span></span>
<span><span class="op">(</span><span class="va">cri_t</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span>p <span class="op">=</span> <span class="va">alpha</span> <span class="op">/</span> <span class="fl">2</span>, df <span class="op">=</span> <span class="va">n</span> <span class="op">-</span> <span class="fl">1</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.13145</code></pre>
</div>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## margin of error</span></span>
<span><span class="op">(</span><span class="va">m_t</span> <span class="op">&lt;-</span> <span class="va">cri_t</span> <span class="op">*</span> <span class="op">(</span><span class="va">s</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.664312</code></pre>
</div>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## 95% CI for mu when sigma is unknown</span></span>
<span><span class="va">x_bar</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span> <span class="op">*</span> <span class="va">m_t</span>  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 118.8357 124.1643</code></pre>
</div>
</div>
<p><span class="math inline">\(z_{0.025} = 1.96 &lt; t_{0.025, 15} = 2.13\)</span>. The interval is wider with <span class="math inline">\(s = 5\)</span>.</p>
</section><section id="summary" class="level2" data-number="13.5"><h2 data-number="13.5" class="anchored" data-anchor-id="summary">
<span class="header-section-number">13.5</span> Summary</h2>
<p>To conclude this chapter, a table that summarizes the confidence interval for <span class="math inline">\(\mu\)</span> is provided.</p>
<table class="table">
<colgroup>
<col style="width: 31%">
<col style="width: 39%">
<col style="width: 29%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Numerical Data, <span class="math inline">\(\sigma\)</span> known</th>
<th style="text-align: center;">Numerical Data, <span class="math inline">\(\sigma\)</span> unknown</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Parameter of Interest</strong></td>
<td style="text-align: center;">Population Mean <span class="math inline">\(\mu\)</span>
</td>
<td style="text-align: center;">Population Mean <span class="math inline">\(\mu\)</span>
</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Confidence Interval</strong></td>
<td style="text-align: center;"><span class="math inline">\(\bar{x} \pm z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{x} \pm t_{\alpha/2, n-1} \frac{s}{\sqrt{n}}\)</span></td>
</tr>
</tbody>
</table>
<p>Remember to check if the population is normally distributed and/or <span class="math inline">\(n&gt;30\)</span>. What if the population is not normal and <span class="math inline">\(n \le 30\)</span>? We could use a simulation-based approach, for example bootstrapping discussed in <a href="infer-bt.html"><span>Chapter&nbsp;14</span></a>.</p>
</section><section id="exercises" class="level2" data-number="13.6"><h2 data-number="13.6" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">13.6</span> Exercises</h2>
<ol type="1">
<li>
<p>Here are summary statistics for randomly selected weights of newborn boys: <span class="math inline">\(n =207\)</span>, <span class="math inline">\(\bar{x} = 30.2\)</span>hg (1hg = 100 grams), <span class="math inline">\(s = 7.3\)</span>hg.</p>
<ol type="a">
<li>Compute a 95% confidence interval for <span class="math inline">\(\mu\)</span>, the mean weight of newborn boys.</li>
<li>Is the result in (a) very different from the 95% confidence interval if <span class="math inline">\(\sigma = 7.3\)</span>?</li>
</ol>
</li>
<li><p>A 95% confidence interval for a population mean <span class="math inline">\(\mu\)</span> is given as (18.635, 21.125). This confidence interval is based on a simple random sample of 32 observations. Calculate the sample mean and standard deviation. Assume that all conditions necessary for inference are satisfied. Use the t-distribution in any calculations.</p></li>
<li><p>A market researcher wants to evaluate car insurance savings at a competing company. Based on past studies he is assuming that the standard deviation of savings is $95. He wants to collect data such that he can get a margin of error of no more than $12 at a 95% confidence level. How large of a sample should he collect?</p></li>
<li>
<p>The 95% confidence interval for the mean rent of one bedroom apartments in Chicago was calculated as ($2400, $3200).</p>
<ol type="a">
<li>Interpret the meaning of the 95% interval.</li>
<li>Find the sample mean rent from the interval.</li>
</ol>
</li>
</ol>


</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>The standard normal random variable <span class="math inline">\(Z \sim N(0, 1)\)</span> is a <strong>pivotal quantity</strong> (or <strong>pivot</strong>) because it is independent of parameters <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./infer.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Statistical Inference</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./infer-bt.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Bootstrapping</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Copyright 2023, Dr.&nbsp;Cheng-Han Yu</div>   
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
<li class="nav-item compact">
    <a class="nav-link" href="https://github.com/chenghanyustats/introstatsbook">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
</div>
  </div>
</footer>


</body></html>