<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="An introductory statistical data science book for STEM students.">
<title>Introduction to Statistics - 28&nbsp; Multiple Linear Regression*</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./model-logistic.html" rel="next">
<link href="./model-reg.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="custom.css">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./model.html">Statistical Models</a></li><li class="breadcrumb-item"><a href="./model-mlr.html"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multiple Linear Regression*</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Statistics</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/chenghanyustats/introstatsbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Introduction-to-Statistics.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistics and Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Science of Data and Data Science</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Collection and Data Type</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">ready fo<em>R</em> data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-py.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title"><em>P</em>repare <em>Y</em>ourself for data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./datasummary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summarizing Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-graphics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-numerics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Numerical Measures of Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-define.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Definition of Probability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-rule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability Rules and Bayes Formula</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-rv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-disc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Discrete Probability Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-cont.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Continuous Probability Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Random Sampling and Sampling Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-llnclt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Law of Large Numbers and Central Limit Theorem</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./infer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Point and Interval Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-bt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Bootstrapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-ht.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-twomean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Comparing Two Population Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-var.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference About Variances</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference About Proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-cat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference about Categorical Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-p.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">The Issues of <span class="math inline">\(p\)</span>-value and Statistical Significance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Bayesian Thinking and Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-nonpar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Nonparametric Tests</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-multicomp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Multiple Comparison*</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-twoway.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Two-Way ANOVA*</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-reg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-mlr.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multiple Linear Regression*</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Bayesian Linear Regression*</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Survival Analysis</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">References</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a-r_prog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">R programming</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a-py_prog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Python Programming</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#why-multiple-regression" id="toc-why-multiple-regression" class="nav-link active" data-scroll-target="#why-multiple-regression"><span class="header-section-number">28.1</span> Why Multiple Regression?</a></li>
  <li><a href="#multiple-linear-regression-mlr-model" id="toc-multiple-linear-regression-mlr-model" class="nav-link" data-scroll-target="#multiple-linear-regression-mlr-model"><span class="header-section-number">28.2</span> Multiple Linear Regression (MLR) Model</a></li>
  <li>
<a href="#estimation-of-model-parameters" id="toc-estimation-of-model-parameters" class="nav-link" data-scroll-target="#estimation-of-model-parameters"><span class="header-section-number">28.3</span> Estimation of Model Parameters</a>
  <ul class="collapse">
<li><a href="#least-squares-estimation-lse" id="toc-least-squares-estimation-lse" class="nav-link" data-scroll-target="#least-squares-estimation-lse"><span class="header-section-number">28.3.1</span> Least Squares Estimation (LSE)</a></li>
  <li><a href="#estimation-of-sigma2" id="toc-estimation-of-sigma2" class="nav-link" data-scroll-target="#estimation-of-sigma2"><span class="header-section-number">28.3.2</span> Estimation of <span class="math inline">\(\sigma^2\)</span></a></li>
  <li><a href="#wald-ci-for-coefficients" id="toc-wald-ci-for-coefficients" class="nav-link" data-scroll-target="#wald-ci-for-coefficients"><span class="header-section-number">28.3.3</span> Wald CI for Coefficients</a></li>
  <li><a href="#ci-for-the-mean-response-ey-mid-bf-x_0" id="toc-ci-for-the-mean-response-ey-mid-bf-x_0" class="nav-link" data-scroll-target="#ci-for-the-mean-response-ey-mid-bf-x_0"><span class="header-section-number">28.3.4</span> CI for the Mean Response <span class="math inline">\(E(y \mid {\bf x}_0)\)</span></a></li>
  <li><a href="#pi-for-new-observations" id="toc-pi-for-new-observations" class="nav-link" data-scroll-target="#pi-for-new-observations"><span class="header-section-number">28.3.5</span> PI for New Observations</a></li>
  <li><a href="#predictor-effect-plots" id="toc-predictor-effect-plots" class="nav-link" data-scroll-target="#predictor-effect-plots"><span class="header-section-number">28.3.6</span> Predictor Effect Plots</a></li>
  </ul>
</li>
  <li>
<a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing"><span class="header-section-number">28.4</span> Hypothesis Testing</a>
  <ul class="collapse">
<li><a href="#test-for-significance-of-regression" id="toc-test-for-significance-of-regression" class="nav-link" data-scroll-target="#test-for-significance-of-regression"><span class="header-section-number">28.4.1</span> Test for Significance of Regression</a></li>
  <li><a href="#r2-and-adjusted-r2" id="toc-r2-and-adjusted-r2" class="nav-link" data-scroll-target="#r2-and-adjusted-r2"><span class="header-section-number">28.4.2</span> <span class="math inline">\(R^2\)</span> and Adjusted <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#tests-on-individual-regression-coefficients" id="toc-tests-on-individual-regression-coefficients" class="nav-link" data-scroll-target="#tests-on-individual-regression-coefficients"><span class="header-section-number">28.4.3</span> Tests on Individual Regression Coefficients</a></li>
  </ul>
</li>
  <li><a href="#inference-pitfalls" id="toc-inference-pitfalls" class="nav-link" data-scroll-target="#inference-pitfalls"><span class="header-section-number">28.5</span> Inference Pitfalls</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/chenghanyustats/introstatsbook/edit/main/model-mlr.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/chenghanyustats/introstatsbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./model.html">Statistical Models</a></li><li class="breadcrumb-item"><a href="./model-mlr.html"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multiple Linear Regression*</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-model-mlr" class="quarto-section-identifier"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multiple Linear Regression*</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="hidden">
<p><span class="math display">\[
\def\cD{{\cal D}}
\def\cL{{\cal L}}
\def\cX{{\cal X}}
\def\cF{{\cal F}}
\def\cH{{\cal H}}
\def\bA{\mathbf{A}}
\def\bB{\mathbf{B}}
\def\bX{\mathbf{X}}
\def\bH{\mathbf{H}}
\def\bI{\mathbf{I}}
\def\bU{\mathbf{U}}
\def\bD{\mathbf{D}}
\def\bV{\mathbf{V}}
\def\bS{\mathbf{S}}
\def\bW{\mathbf{W}}
\def\bY{\mathbf{Y}}
\def\bZ{\mathbf{Z}}
\def\bK{\mathbf{K}}
\def\bx{\mathbf{x}}
\def\by{\mathbf{y}}
\def\bs{\mathbf{s}}
\def\br{\mathbf{r}}
\def\bu{\mathbf{u}}
\def\be{\mathbf{e}}
\def\bv{\mathbf{v}}
\def\bp{\mathbf{p}}
\def\bw{\mathbf{w}}
\def\bz{\mathbf{z}}
\def\bzero{\mathbf{0}}
\def\balpha{\boldsymbol \alpha}
\def\bbeta{\boldsymbol \beta}
\def\btheta{\boldsymbol \theta}
\def\bSigma{\boldsymbol \Sigma}
\def\bxi{\boldsymbol \xi}
\def\bmu{\boldsymbol \mu}
\def\bep{\boldsymbol \epsilon}
\def\T{\text{T}}
\def\Trace{\text{Trace}}
\def\Cov{\text{Cov}}
\def\cov{\text{Cov}}
\def\Corr{\text{Corr}}
\def\cor{\text{Corr}}
\def\Var{\text{Var}}
\def\var{\text{Var}}
\def\E{\text{E}}
\def\pr{\text{pr}}
\def\Prob{\text{P}}
\DeclareMathOperator*{\argmin}{arg\,min}
\DeclareMathOperator*{\argmax}{arg\,max}
\]</span></p>
</div>
<p>When more than one predictors are considered and put in a regression model, we are dealing with <strong>multiple linear regression</strong>. Multiple linear regression (MLR) is pretty similar to simple linear regression (SLR). They share the same idea and concept in terms of prediction and inference.</p>
<section id="why-multiple-regression" class="level2" data-number="28.1"><h2 data-number="28.1" class="anchored" data-anchor-id="why-multiple-regression">
<span class="header-section-number">28.1</span> Why Multiple Regression?</h2>
<p>The first question you may ask is why we want to use multiple regression? In practice, we often have more than one predictor in a given study, and our target response may be affected by several factors. For example, how amount of money spent on advertising on different media affect the total sales of some product? We may need more than one predictors because usually companies will spend money on several different media, not just one.</p>
<ul>
<li><p>Data: total sales <span class="math inline">\((Y)\)</span> and amount of money spent on advertising on TV <span class="math inline">\((X_1)\)</span>, YouTube <span class="math inline">\((X_2)\)</span>, and Instagram <span class="math inline">\((X_3)\)</span>.</p></li>
<li><p>We want to predict sales based on the three advertising expenditures and see which medium is more effective.</p></li>
<li><p>Total sales <span class="math inline">\((Y)\)</span> and amount of money spent on advertising on YouTube (YT) <span class="math inline">\((X_1)\)</span>, Facebook (FB) <span class="math inline">\((X_2)\)</span>, Instagram (IG) <span class="math inline">\((X_3)\)</span>.</p></li>
</ul>
<!-- ![](./img/tv.jpeg) ![](./img/yt.jpeg) --><div class="columns">
<div class="column" style="width:33.3%;">
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/img-model/yt.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:33.3%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/img-model/fb.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:33.3%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/img-model/ig.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<ul>
<li>Predict sales based on the three advertising expenditures and see which medium is more effective.</li>
</ul>
<!-- ## Fit Separate Simple Linear Regression Models --><p>You may wonder, how about we just fit three separate simple linear regression models, one for each predictor. Yes, we could do that. And if we do this, we’ll see that, as shown in the figure below, advertising on the 3 media is valuable because the more the money we put in, the higher sales of products we’ll get. However, fitting a separate SLR model for each predictor is not satisfactory. Let’s see why.</p>
<!-- Fit three separate independent SLR models: -->
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<!-- ## Don't Fit a Separate Simple Linear Regression -->
<ul>
<li>👉 How to make a <em>single</em> prediction of sales given levels of the 3 advertising media budgets?
<ul>
<li>
<p><span style="color:blue"> How to predict the sales when the amount spent on YT is 50, 100 on FB and 30 on IG? </span></p>
<p>It is unclear how to make a single prediction of sales given levels of the three advertising media budgets, since each of the budgets is associated with a separate regression equation.</p>
</li>
</ul>
</li>
<li>👉 Each regression equation ignores the other 2 media in forming coefficient estimates.
<ul>
<li><p><span style="color:blue"> The effect of FB advertising on sales may be increased or decreased when YT and IG advertising are in the model. </span></p></li>
<li>
<p><span style="color:blue"> IG advertising may have no impact on sales when YT and FB advertising are in the model. </span></p>
<p>If the three media budgets are correlated with each other, this can lead to very misleading estimates of the individual media effects on sales.</p>
</li>
</ul>
</li>
<li>👍👍 Better approach: <em>extend the SLR model so that it can <strong>directly accommodate multiple predictors</strong>.</em>
</li>
</ul>
<p><strong>I hope you don’t feel…</strong></p>
<div class="small">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/img-model/mlr_depress.jpeg" class="img-fluid figure-img" style="width:46.0%"></p>
<figcaption>Source: https://memegenerator.net/instance/62248186/first-world-problems-multiple-regression-more-like-multiple-depression</figcaption></figure>
</div>
</div>
</div>
</div>
<p><strong>What I hope is…</strong></p>
<div class="small">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/img-model/mlr_meme.jpeg" class="img-fluid figure-img" style="width:82.0%"></p>
<figcaption>https://www.tldrpharmacy.com/content/how-to-be-awesome-at-biostatistics-and-literature-evaluation-part-iii</figcaption></figure>
</div>
</div>
</div>
</div>
</section><section id="multiple-linear-regression-mlr-model" class="level2" data-number="28.2"><h2 data-number="28.2" class="anchored" data-anchor-id="multiple-linear-regression-mlr-model">
<span class="header-section-number">28.2</span> Multiple Linear Regression (MLR) Model</h2>
<p>Suppose we have <span class="math inline">\(k\)</span> distinct predictors. The (population) multiple linear regression model is <span class="math display">\[Y_i= \beta_0 + \beta_1X_{i1} + \beta_2X_{i2} + \dots + \beta_kX_{ik} + \epsilon_i\]</span></p>
<ul>
<li><p><span class="math inline">\(X_{ij}\)</span>: <span class="math inline">\(j\)</span>-th regressor value on <span class="math inline">\(i\)</span>-th measurement, <span class="math inline">\(j = 1, \dots, k\)</span>.</p></li>
<li><p><span class="math inline">\(\beta_j\)</span>: <span class="math inline">\(j\)</span>-th coefficient quantifying the association between <span class="math inline">\(X_j\)</span> and <span class="math inline">\(Y\)</span>.</p></li>
</ul>
<p>In the advertising example, <span class="math inline">\(k = 3\)</span> and <span class="math display">\[\texttt{sales} = \beta_0 + \beta_1 \times \texttt{YouTube} + \beta_2 \times  \texttt{Facebook} + \beta_3 \times \texttt{Instagram} + \epsilon\]</span> We interpret <span class="math inline">\(\beta_j\)</span>, <span class="math inline">\(j = 1, \dots, p\)</span>, as the average effect on <span class="math inline">\(Y\)</span> of a one unit increase in <span class="math inline">\(X_j\)</span>, <em>holding all other predictors fixed</em>. Later, we will learn how to interpret the coefficients in more detail.</p>
<p>The model assumptions are same same as SLR that <span class="math inline">\(\epsilon_i \stackrel{iid}{\sim} N(0, \sigma^2).\)</span> When <span class="math inline">\(k = 1\)</span>, MLR is reduced to SLR.</p>
<!-- ::: question -->
<!-- How many parameters are there in the model? -->
<!-- ::: -->
<!-- ## Sample MLR Model -->
<p>Given the training sample data <span class="math inline">\((x_{11}, \dots, x_{1k}, y_1), (x_{21}, \dots, x_{2k}, y_2), \dots, (x_{n1}, \dots, x_{nk}, y_n),\)</span> the sample MLR model is <span class="math display">\[\begin{align}
y_i &amp;= \beta_0 + \beta_1x_{i1} + \beta_2x_{i2} + \dots + \beta_k x_{ik} + \epsilon_i \\
&amp;= \beta_0 + \sum_{j=1}^k\beta_j x_{ij} + \epsilon_i, \quad i = 1, 2, \dots, n.
\end{align}\]</span></p>
<!-- Usually we save our data as a data matrix, or data frame in R -->
<!-- # ```{r} -->
<!-- # #| out-width: 48% -->
<!-- # knitr::include_graphics("./images/img-model/mlr_data_matrix.png") -->
<!-- # ``` -->
<!-- ::: notes -->
<!-- - Writing our data and model without using matrix starts getting tedious. -->
<!-- - Later we'll see our to write it in a more clean way using matrix notation. -->
<!-- - our mpg data set in the homework has this type of structure. -->
<!-- - In R we usually store this kind of data set in R structure call data frame. -->
<!-- ::: -->
<!-- ## Regression Hyperplane -->
<p>Now I’m gonna show you what a MLR looks like when we fit it to the data. If we have two predictors, we will have a sample regression <strong>plane</strong>. If we have more than two predictors in the model, we are not able to visualize it, but the idea is the same. We will have something called <strong>hyperplane</strong> or <strong>response surface</strong> that basically play the same role as the regression plane in 2D or regression line in 1D.</p>
<p>The plot on the right is the contour plot when we project the plot onto the <span class="math inline">\(X_1\)</span>-<span class="math inline">\(X_2\)</span> plane. You can see that basically the higher <span class="math inline">\(X_1\)</span> and/or the higher <span class="math inline">\(X_2\)</span>, the higher value of <span class="math inline">\(Y\)</span>. Moreover, you can see that the level curves are straight and parallel, meaning that the effect of <span class="math inline">\(X_1\)</span> on <span class="math inline">\(Y\)</span> does not change with the values of <span class="math inline">\(X_2\)</span> or the effect does not depend on the level of <span class="math inline">\(X_2\)</span>.</p>
<!-- - **SLR**: regression line -->
<!-- - **MLR: regression hyperplane or response surface** -->
<ul>
<li><span class="math inline">\(y = \beta_0 + \beta_1x_1 + \beta_{2}x_2 + \epsilon\)</span></li>
<li><span class="math inline">\(E(y \mid x_1, x_2) = 50 + 10x_1 + 7x_2\)</span></li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:110.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:110.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<!-- ::: notes -->
<!-- - https://cran.r-project.org/web/packages/rsm/vignettes/rsm-plots.pdf -->
<!-- - http://www.sthda.com/english/wiki/scatterplot3d-3d-graphics-r-software-and-data-visualization  -->
<!-- - https://stackoverflow.com/questions/18147595/plot-3d-plane-true-regression-surface -->
<!-- ::: -->
<!-- ## Response Surface : Interaction Model -->
<p>Remember in SLR, we can have a liner model that describes a nonlinear relationship. Same in MLR. We can have a linear model that generates a nonlinear response surface!</p>
<ul>
<li><span class="math inline">\(y = \beta_0 + \beta_1x_1 + \beta_{2}x_2 + \beta_{12}x_1x_2 + \epsilon\)</span></li>
<li>This is in fact a linear regression model: let <span class="math inline">\(\beta_3 = \beta_{12}, x_3 = x_1x_2\)</span>.</li>
<li><span class="math inline">\(E(y \mid x_1, x_2) = 50 + 10x_1 + 7x_2 + 5x_1x_2\)</span></li>
<li>😎 🤓 <strong>A linear model generates a nonlinear response surface!</strong>
</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:110.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:110.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<!-- ::: notes -->
<!-- ::: -->
<!-- ## Response Surface : 2nd Order with Interaction Model -->
<p>😎 🤓 A <strong>linear</strong> regression model can describe a <strong>complex nonlinear relationship</strong> between the response and predictors! The following is a 2nd order model with interaction.</p>
<ul>
<li><span class="math inline">\(y = \beta_0 + \beta_1x_1 + \beta_{2}x_2 + \beta_{11}x_1^2 + \beta_{22}x_2^2 + \beta_{12}x_1x_2 + \epsilon\)</span></li>
<li><span class="math inline">\(E(y) = 800+10x_1+7x_2 -8.5x_1^2-5x_2^2- 4x_1x_2\)</span></li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:110.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:110.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section><section id="estimation-of-model-parameters" class="level2" data-number="28.3"><h2 data-number="28.3" class="anchored" data-anchor-id="estimation-of-model-parameters">
<span class="header-section-number">28.3</span> Estimation of Model Parameters</h2>
<section id="least-squares-estimation-lse" class="level3" data-number="28.3.1"><h3 data-number="28.3.1" class="anchored" data-anchor-id="least-squares-estimation-lse">
<span class="header-section-number">28.3.1</span> Least Squares Estimation (LSE)</h3>
<p>As SLR, we can define the least-squares function as the sum of squares of epsilon. <!-- $$\begin{align} --> <!-- y_i &= \beta_0 + \beta_1x_{i1} + \beta_2x_{i2} + \dots + \beta_k x_{ik} + \epsilon_i \\ --> <!-- &= \beta_0 + \sum_{j=1}^k\beta_j x_{ij} + \epsilon_i, \quad i = 1, 2, \dots, n --> <!-- \end{align}$$ --> The least-squares function is <span class="math display">\[S(\alpha_0, \alpha_1, \dots, \alpha_k) = \sum_{i=1}^n\left(y_i - \alpha_0 - \sum_{j=1}^k\alpha_j x_{ij}\right)^2\]</span> The function <span class="math inline">\(S(\cdot)\)</span> must be minimized with respect to the coefficients, i.e., <span class="math display">\[(b_0, b_1, \dots, b_k) = \underset{{\alpha_0, \alpha_1, \dots, \alpha_k}}{\mathrm{arg \, min}}  S(\alpha_0, \alpha_1, \dots, \alpha_k)\]</span></p>
<p>We are going to choose the sample statistics <span class="math inline">\(b_0\)</span>, <span class="math inline">\(b_1\)</span>, …, <span class="math inline">\(b_k\)</span> as the estimates of <span class="math inline">\(\beta_0, \beta_1, \dots, \beta_k\)</span> so that <span class="math inline">\(S(.)\)</span> is minimized when <span class="math inline">\(b_0\)</span>, <span class="math inline">\(b_1\)</span>, …, <span class="math inline">\(b_k\)</span> are plugged in the function.</p>
<!-- ::: notes -->
<!-- ::: -->
<!-- ## Geometry of Least Square Estimation -->
<p>If we look at the geometry of least squares estimation of MLR, we have a visualization like this. Again, in SLR, different <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>s give us different sample regression lines. In MLR, suppose we have two predictors, and different <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_2\)</span> give us a different sample regression plane. Geometrically speaking, we are trying to find a sample regression plane such that the sum of the squared distance between the observations (denoted by those blue points) and the plane is minimized. For more than 2 predictor case, we are not able to visualize it because we live a 3D world, but the idea is exactly the same. And we called the regression plane a hyperplane.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- ::: notes -->
<!-- ::: -->
<!-- ## Least-squares Normal Equations-->
<p>Again similar to SLR, we can take derivative w.r.t <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, to the <span class="math inline">\(\beta_k\)</span>. And we are gonna have <span class="math inline">\(p = k + 1\)</span> equations with <span class="math inline">\(p\)</span> unknown parameters. So we can find one and only one solution to <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, to the <span class="math inline">\(\beta_k\)</span>, which are <span class="math inline">\(b_0\)</span>, <span class="math inline">\(b_1\)</span>, …, <span class="math inline">\(b_k\)</span>. And the <span class="math inline">\(p\)</span> equations are the least squares <strong>normal questions</strong>. The ordinary least squares estimators are the solutions to the normal equations. <!-- - You guys solve the equations when k = 1. --> <!-- - Do you think it is easy to solve the questions when the number of predictors is 2 or more than 2? --></p>
<p><span class="math display">\[\begin{align}
\left.\frac{\partial S}{\partial\alpha_0}\right\vert_{b_0, b_1, \dots, b_k} &amp;= -2 \sum_{i=1}^n\left(y_i - b_0 - \sum_{j=1}^k b_j x_{ij}\right) = 0\\
\left.\frac{\partial S}{\partial\alpha_j}\right\vert_{b_0, b_1, \dots, b_k} &amp;= -2 \sum_{i=1}^n\left(y_i - b_0 - \sum_{j=1}^k b_j x_{ij}\right)x_{ij} = 0, \quad j = 1, 2, \dots, k
\end{align}\]</span></p>
<!-- ::: question -->
<!-- 🍹 🍺 🍸  🥂  I buy you a drink if you solve the equations for $k \ge 2$ by hand without using matrix notations or operations! -->
<!-- ::: -->
<!-- ::: notes -->
<!-- - Here I am happy to treat you and buy you a drink if you can solve the equations for $k \ge 2$ by hand without using matrix notations or operations! -->
<!-- - Come to my office hours and show your work. And we go to a bar together. Sounds good? -->
<!-- - In fact, if you try, you are gonna deal with lots of algebra, but if we write the system of equations in a matrix form, the solution becomes very clean. -->
<!-- - That's see why. -->
<!-- ::: -->
<p>Based on the MLR model and assumptions, the LS estimator <span class="math inline">\({\bf b} = (b_0, b_1, \dots, b_k)'\)</span> is <strong>BLUE</strong>, <strong>B</strong>est <strong>L</strong>inear <strong>U</strong>nbiased <strong>E</strong>stimator. 👍</p>
<ul>
<li><p><span style="color:#DE3163"> <strong>Linear</strong> </span>: Each <span class="math inline">\(b_j\)</span> is a linear combination of <span class="math inline">\(y_1, \dots, y_n\)</span>.</p></li>
<li><p><span style="color:#DE3163"> <strong>Unbiased</strong> </span>: Each <span class="math inline">\(b_j\)</span> is normally distributed with mean <span class="math inline">\(\beta_j\)</span>.</p></li>
<li><p><span style="color:#DE3163"> <strong>Best</strong> </span>: Each <span class="math inline">\(b_j\)</span> has the minimum variance, comparing to all other unbiased estimator for <span class="math inline">\(\beta_j\)</span> that is a linear combo of <span class="math inline">\(y_1, \dots, y_n\)</span>.</p></li>
</ul>
<hr>
<p><span style="color:blue"> <strong>Example: Least Squares Estimation</strong> </span></p>
<!-- ## [R Lab]{.pink} [Delivery Time Data](./data/data-ex-3-1.csv) -->
<p>In this chapter, we use <a href="./data/data-ex-3-1.csv">Delivery Time Data</a> of Example 3.1 from <a href="https://www.wiley.com/en-us/Introduction+to+Linear+Regression+Analysis%2C+6th+Edition-p-9781119578758">Introduction to Linear Regression Analysis, 6th edition</a> to demo MLR.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">R</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Python</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load the data set</span></span>
<span><span class="va">delivery</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span>file <span class="op">=</span> <span class="st">"./data/data-ex-3-1.csv"</span>, header <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">delivery_data</span> <span class="op">&lt;-</span> <span class="va">delivery</span><span class="op">[</span>, <span class="op">-</span><span class="fl">1</span><span class="op">]</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">delivery_data</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"time"</span>, <span class="st">"cases"</span>, <span class="st">"distance"</span><span class="op">)</span></span>
<span><span class="va">delivery_data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   time cases distance
1  16.7     7      560
2  11.5     3      220
3  12.0     3      340
4  14.9     4       80
5  13.8     6      150
6  18.1     7      330
7   8.0     2      110
8  17.8     7      210
9  79.2    30     1460
10 21.5     5      605
11 40.3    16      688
12 21.0    10      215
13 13.5     4      255
14 19.8     6      462
15 24.0     9      448
16 29.0    10      776
17 15.3     6      200
18 19.0     7      132
19  9.5     3       36
20 35.1    17      770
21 17.9    10      140
22 52.3    26      810
23 18.8     9      450
24 19.8     8      635
25 10.8     4      150</code></pre>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>delivery_data <span class="op">=</span> pd.read_csv(<span class="st">'./data/delivery_data.csv'</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>delivery_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     time  cases  distance
0   16.68      7       560
1   11.50      3       220
2   12.03      3       340
3   14.88      4        80
4   13.75      6       150
5   18.11      7       330
6    8.00      2       110
7   17.83      7       210
8   79.24     30      1460
9   21.50      5       605
10  40.33     16       688
11  21.00     10       215
12  13.50      4       255
13  19.75      6       462
14  24.00      9       448
15  29.00     10       776
16  15.35      6       200
17  19.00      7       132
18   9.50      3        36
19  35.10     17       770
20  17.90     10       140
21  52.32     26       810
22  18.75      9       450
23  19.83      8       635
24  10.75      4       150</code></pre>
</div>
</div>
</div>
</div>
</div>
<ul>
<li><p><span class="math inline">\(y\)</span>: the amount of time required by the route driver to stock the vending machines with beverages</p></li>
<li><p><span class="math inline">\(x_1\)</span>: the number of cases stocked</p></li>
<li><p><span class="math inline">\(x_2\)</span>: the distance walked by the driver</p></li>
<li><p>Goal: fit a MLR model <span class="math inline">\(y = \beta_0 + \beta_1x_1 + \beta_2x_2 + \epsilon\)</span> to the amount of time required by the route driver to service the vending machines</p></li>
</ul>
<!-- ## [R Lab]{.pink} Scatterplot Matrix --><div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Always get to know your data set before you fit any statistical or machine learning model to the data.</p>
</div>
</div>
<p>Each plot shows the relationship between a pair of variables.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">R</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Python</a></li>
</ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/pairs.html">pairs</a></span><span class="op">(</span><span class="va">delivery_data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:78.0%"></p>
</figure>
</div>
</div>
</div>
<!-- ## [R Lab]{.pink} 3D Scatterplot -->
<p>Sometimes a 3D scatterplot is useful in visualizing the relationship between the response and the regressors when there are only two regressors.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mgp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">0.8</span>, <span class="fl">0</span><span class="op">)</span>, las <span class="op">=</span> <span class="fl">1</span>, mar <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">0</span>, <span class="fl">0</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">scatterplot3d</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/scatterplot3d/man/scatterplot3d.html">scatterplot3d</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">delivery_data</span><span class="op">$</span><span class="va">cases</span>, y <span class="op">=</span> <span class="va">delivery_data</span><span class="op">$</span><span class="va">distance</span>, z <span class="op">=</span> <span class="va">delivery_data</span><span class="op">$</span><span class="va">time</span>,</span>
<span>              xlab <span class="op">=</span><span class="st">"cases"</span>, ylab <span class="op">=</span> <span class="st">"distance"</span>, zlab <span class="op">=</span> <span class="st">"time"</span>,</span>
<span>              xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">30</span><span class="op">)</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">36</span>, <span class="fl">1640</span><span class="op">)</span>, zlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">8</span>, <span class="fl">80</span><span class="op">)</span>,</span>
<span>              box <span class="op">=</span> <span class="cn">TRUE</span>, color <span class="op">=</span> <span class="st">"blue"</span>, mar <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">0</span>, <span class="fl">2</span><span class="op">)</span>, angle <span class="op">=</span> <span class="fl">30</span>, pch <span class="op">=</span> <span class="fl">16</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
</div>
<p>To fit the MLR model, we again use <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>. In the <code>furmula</code> argument, we use <code>+</code> to add predictors. <code>coef(delivery_lm)</code> or <code>delivery_lm$coef</code> can be used to grab the LS estimates of coefficients.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">delivery_lm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">time</span> <span class="op">~</span> <span class="va">cases</span> <span class="op">+</span> <span class="va">distance</span>, data <span class="op">=</span> <span class="va">delivery_data</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">delivery_lm</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)       cases    distance 
     2.3412      1.6159      0.0144 </code></pre>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>pd.plotting.scatter_matrix(delivery_data, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">8</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>array([[&lt;Axes: xlabel='time', ylabel='time'&gt;,
        &lt;Axes: xlabel='cases', ylabel='time'&gt;,
        &lt;Axes: xlabel='distance', ylabel='time'&gt;],
       [&lt;Axes: xlabel='time', ylabel='cases'&gt;,
        &lt;Axes: xlabel='cases', ylabel='cases'&gt;,
        &lt;Axes: xlabel='distance', ylabel='cases'&gt;],
       [&lt;Axes: xlabel='time', ylabel='distance'&gt;,
        &lt;Axes: xlabel='cases', ylabel='distance'&gt;,
        &lt;Axes: xlabel='distance', ylabel='distance'&gt;]], dtype=object)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Sometimes a 3D scatterplot is useful in visualizing the relationship between the response and the regressors when there are only two regressors.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure()</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> fig.add_subplot(<span class="dv">111</span>, projection<span class="op">=</span><span class="st">'3d'</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>ax.scatter(delivery_data[<span class="st">'cases'</span>], </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>           delivery_data[<span class="st">'distance'</span>], </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>           delivery_data[<span class="st">'time'</span>])</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Cases'</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Distance'</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>ax.set_zlabel(<span class="st">'Time'</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-24-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To fit the MLR model, we again use <code>ols()</code>. In the <code>furmula</code> argument, we use <code>+</code> to add predictors. <code>delivery_ols.params</code> can be used to grab the LS estimates of coefficients.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.formula.api <span class="im">import</span> ols</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>delivery_ols <span class="op">=</span> ols(formula<span class="op">=</span><span class="st">'time ~ cases + distance'</span>, data<span class="op">=</span>delivery_data).fit()</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>delivery_ols.params</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Intercept    2.341231
cases        1.615907
distance     0.014385
dtype: float64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>There is another function <a href="https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.OLS.html"><code>OLS()</code></a> that takes response vector <code>y</code> and design matrix <code>X</code> as input arguments to fit the linear regression model.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> delivery_data[[<span class="st">'cases'</span>, <span class="st">'distance'</span>]]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)  <span class="co"># Adds a constant term to the predictor</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> delivery_data[<span class="st">'time'</span>]</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>delivery_OLS <span class="op">=</span> sm.OLS(y, X).fit()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</div>
</div>
<!-- ## [R Lab]{.pink} Multiple Linear Regression -->
<p><span class="math display">\[\hat{y} = 2.34 + 1.62x_1 + 0.014x_2\]</span> Interpretation of coefficients needs additional attention.</p>
<ul>
<li><p><span class="math inline">\(b_1\)</span>: <strong>All else held constant</strong>, for one case of product stocked increase, we expect the delivery time to be longer, <em>on average</em>, by 1.62 minutes.</p></li>
<li><p><span class="math inline">\(b_2\)</span>: <strong>All else held constant</strong>, one additional foot walked by the driver causes the delivery time, <em>on average</em>, to be 0.014 minutes longer.</p></li>
<li><p><span class="math inline">\(b_0\)</span>: The delivery time with no number of cases of product stocked and no distance walked by the driver is expected to be 2.34 minutes. (Make sense?!)</p></li>
</ul>
<p>When we interpret slopes or the effect of any predictor on the response in MLR, for example, <span class="math inline">\(x_1\)</span>, it needs to be measured on the same scale, meaning that all other predictors should not change because any change in them will change the response value too, and this response change is not due to <span class="math inline">\(x_1\)</span>, and not measured or explained by <span class="math inline">\(b_1\)</span>.</p>
<p>For regression we usually don’t pay much attention to <span class="math inline">\(\beta_0\)</span> because quite often, it does not have natural physical meaning. Still, depending on your research questions, you may be interested in the intercept term. For example, you may want to know your response value when your predictor, temperature, is at value zero. Moreover, it is quite often that we normalize/standardize our variables before we fit MLR. If that is the case, the intercept means the average response level when the predictors are at their average level.</p>
<!-- ## [R Lab]{.pink} Regression Plane -->
<p>The LS fitted regression plane is shown below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-27-5.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:82.0%"></p>
</figure>
</div>
</div>
</div>
</section><section id="estimation-of-sigma2" class="level3" data-number="28.3.2"><h3 data-number="28.3.2" class="anchored" data-anchor-id="estimation-of-sigma2">
<span class="header-section-number">28.3.2</span> Estimation of <span class="math inline">\(\sigma^2\)</span>
</h3>
<p>Same as SLR, the estimate of <span class="math inline">\(\sigma^2\)</span>, denoted as <span class="math inline">\(\hat{\sigma}^2\)</span> or <span class="math inline">\(s^2\)</span>, is the mean square residual of the model.</p>
<p>Remember that the sum of squares residual is <span class="math inline">\(SS_{res} = \sum_{i=1}^ne_i^2 = \sum_{i=1}^n(y_i - \hat{y}_i)^2\)</span>. Then the mean square residual is <span class="math inline">\(SS_{res}\)</span> divided by its degrees of freedom: <span class="math inline">\(MS_{res} = \frac{SS_{res}}{n - p}\)</span> with <span class="math inline">\(p = k + 1\)</span>. Note that the degrees of freedom is <span class="math inline">\(n - p\)</span> where <span class="math inline">\(p\)</span> is the number of beta coefficients in the model. When <span class="math inline">\(p = 2\)</span>, it goes back to the SLR case.</p>
<p><span class="math inline">\(S^2 = MS_{res}\)</span> is <em>unbiased</em> for <span class="math inline">\(\sigma^2\)</span>, i.e., <span class="math inline">\(E[MS_{res}] = \sigma^2\)</span>. Keep in mind that <span class="math inline">\(S^2 = MS_{res}\)</span> is a random variable. Before data are collected <span class="math inline">\(Y_i\)</span> and <span class="math inline">\(\hat{Y}_i\)</span> are assumed random variables, and <span class="math inline">\(S^2\)</span>, a function of random variables, will be a random variable too.</p>
<p><span class="math inline">\(\hat{\sigma}^2 = MS_{res}\)</span> is model dependent. Its value varies with change of the model. If our model is specified correctly, <span class="math inline">\(\hat{\sigma}^2\)</span> depends only on our data quality. If our data have lots of noise itself, there is nothing we can do.</p>
<p><span class="math inline">\(\hat{\sigma}^2\)</span> of SLR may be quite larger than the <span class="math inline">\(\hat{\sigma}^2\)</span> of MLR if the predictors in MLR capture a lots of variation of <span class="math inline">\(y\)</span> that cannot be explained by the only predictor in the SLR, and are treated as noises or unexplained variation. Remember <span class="math inline">\(S^2\)</span> measures the variation or the size of the <em>unexplained</em> noise about the fitted regression line/hyperplane, and we prefer a small residual mean square.</p>
<!-- ::: notes -->
<!-- - $SS_{res} = \sum_{i=1}^ne_i^2 = {\bf e'e} = {\bf (y-Xb)'(y-Xb)} = {\bf y'y - b'X'y} = \sum_{i=1}^n(y_i - \hat{y}_i)^2$. -->
<!-- - If our model is specified correctly, $\hat{\sigma}^2$ depends on our data quality. -->
<!-- - If our data have lots of noise itself, there is nothing we can do. -->
<!-- ::: -->
<hr>
<p><span style="color:blue"> <strong>Example: Estimation of <span class="math inline">\(\sigma^2\)</span></strong> </span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">R</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Python</a></li>
</ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<p>Here I show three methods to obtain the <span class="math inline">\(\sigma^2\)</span> estimate. The method 1 first compute the summary of the fitted result, which is saved as a list, then get the element <code>sigma</code> that is <span class="math inline">\(\hat{\sigma}\)</span>. If you look at the summary output, the value of <span class="math inline">\(\hat{\sigma}\)</span> is shown in the row: <code>Residual standard error: 3.26 on 22 degrees of freedom</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## method 1</span></span>
<span><span class="va">summ_delivery</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">delivery_lm</span><span class="op">)</span>  <span class="co">## check names(summ_delivery)</span></span>
<span><span class="va">summ_delivery</span><span class="op">$</span><span class="va">sigma</span> <span class="op">^</span> <span class="fl">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.6</code></pre>
</div>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">delivery_lm</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = time ~ cases + distance, data = delivery_data)

Residuals:
   Min     1Q Median     3Q    Max 
-5.788 -0.663  0.436  1.157  7.420 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.34123    1.09673    2.13  0.04417 *  
cases        1.61591    0.17073    9.46  3.3e-09 ***
distance     0.01438    0.00361    3.98  0.00063 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.26 on 22 degrees of freedom
Multiple R-squared:  0.96,  Adjusted R-squared:  0.956 
F-statistic:  261 on 2 and 22 DF,  p-value: 4.69e-16</code></pre>
</div>
</div>
<p>The second method simply uses the definition of <span class="math inline">\(MS_{res}\)</span>. We first calculate <span class="math inline">\(SS_{res}\)</span>, then divide it by <span class="math inline">\(n-3\)</span> because in this example, we have 2 predictors <span class="math inline">\((k = 2)\)</span>, and 3 coefficients <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\beta_2\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## method 2</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">delivery_lm</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span></span>
<span><span class="op">(</span><span class="va">SS_res</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">delivery_lm</span><span class="op">$</span><span class="va">residuals</span> <span class="op">*</span> <span class="va">delivery_lm</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 234</code></pre>
</div>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">SS_res</span> <span class="op">/</span> <span class="op">(</span><span class="va">n</span> <span class="op">-</span> <span class="fl">3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.6</code></pre>
</div>
</div>
<p>The third method also uses the definition of <span class="math inline">\(MS_{res}\)</span>. The difference is that here we use <span class="math inline">\(\sum_{i=1}^n(y_i - \hat{y}_i)^2\)</span> instead of <span class="math inline">\(\sum_{i=1}^ne_i^2\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## method 3</span></span>
<span><span class="op">(</span><span class="va">SS_res1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">delivery_data</span><span class="op">$</span><span class="va">time</span> <span class="op">-</span> <span class="va">delivery_lm</span><span class="op">$</span><span class="va">fitted.values</span><span class="op">)</span> <span class="op">^</span> <span class="fl">2</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 234</code></pre>
</div>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">SS_res1</span> <span class="op">/</span> <span class="op">(</span><span class="va">n</span> <span class="op">-</span> <span class="fl">3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.6</code></pre>
</div>
</div>
<!-- ::: notes -->
<!-- ```{r, eval=FALSE} -->
<!-- summ_delivery <- summary(delivery_lm) -->
<!-- summ_delivery$sigma ^ 2 -->
<!-- # ## Why this is SS_res? Check what crossprod() is doing! -->
<!-- # (SS_res1 <- crossprod(y) - crossprod(fitted_y, y)) -->
<!-- # SS_res1 / (n - 3) -->
<!-- ## Why this is SS_res? -->
<!-- n <- length(delivery_lm$residuals) -->
<!-- (SS_res <- sum(delivery_lm$residuals * delivery_lm$residuals)) -->
<!-- SS_res / (n - 3) -->
<!-- ``` -->
<!-- ::: -->
<!-- ### Confidence Interval and Prediction Interval -->
<!-- <h2> CI for Coefficients </h2> -->
<!-- <h2> CI for the Mean Response  </h2> -->
<!-- <h2> PI for New Observations  </h2> -->
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<p>Here I show three methods to obtain the <span class="math inline">\(\sigma^2\)</span> estimate. The method 1 obtains the mean square error of residual from the fitted object.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Method 1: Residual standard error</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>delivery_ols.mse_resid</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>10.624167155479675</code></pre>
</div>
</div>
<p>The second method simply uses the definition of <span class="math inline">\(MS_{res}\)</span>. We first calculate <span class="math inline">\(SS_{res}\)</span>, then divide it by <span class="math inline">\(n-3\)</span> because in this example, we have 2 predictors <span class="math inline">\((k = 2)\)</span>, and 3 coefficients <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\beta_2\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Method 2: Residual Sum of Squares (RSS) and variance estimation</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(delivery_ols.resid)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>SS_res <span class="op">=</span> np.<span class="bu">sum</span>(delivery_ols.resid <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>SS_res</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>233.73167742055284</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>SS_res <span class="op">/</span> (n <span class="op">-</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>10.624167155479675</code></pre>
</div>
</div>
<p>The third method also uses the definition of <span class="math inline">\(MS_{res}\)</span>. The difference is that here we use <span class="math inline">\(\sum_{i=1}^n(y_i - \hat{y}_i)^2\)</span> instead of <span class="math inline">\(\sum_{i=1}^ne_i^2\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Method 3: Another way to calculate RSS and variance estimation</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>SS_res1 <span class="op">=</span> np.<span class="bu">sum</span>((delivery_data[<span class="st">'time'</span>] <span class="op">-</span> delivery_ols.fittedvalues) <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>SS_res1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>233.73167742055284</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>SS_res1 <span class="op">/</span> (n <span class="op">-</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>10.624167155479675</code></pre>
</div>
</div>
</div>
</div>
</div>
</section><section id="wald-ci-for-coefficients" class="level3" data-number="28.3.3"><h3 data-number="28.3.3" class="anchored" data-anchor-id="wald-ci-for-coefficients">
<span class="header-section-number">28.3.3</span> Wald CI for Coefficients</h3>
<p>The <span class="math inline">\((1-\alpha)100\%\)</span> Wald CI for <span class="math inline">\(\beta_j\)</span>, <span class="math inline">\(j = 0, 1, \dots, k\)</span> is <span class="math display">\[\left(b_j- t_{\alpha/2, n-p}~se(b_j), \quad b_j + t_{\alpha/2, n-p}~ se(b_j)\right)\]</span> where <span class="math inline">\(se(b_j)\)</span> is the standard error of <span class="math inline">\(b_j\)</span>. The formula come from the fact that each of the statistics <span class="math inline">\(\frac{b_j - \beta_j}{se(b_j)}, j = 0, 1, 2, \dots, k\)</span> follows <span class="math inline">\(t_{n-p}\)</span> distribution. <span class="math inline">\(se(b_j)\)</span> is a function of <span class="math inline">\(\hat{\sigma}^2\)</span> and <span class="math inline">\(x_{ij}s\)</span>.</p>
<hr>
<p><span style="color:blue"> <strong>Example: Wald CI for Coefficients</strong> </span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">R</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Python</a></li>
</ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<p>We simply use <code><a href="https://rdrr.io/r/stats/confint.html">confint()</a></code>command with the fitted result put inside to obtain the CI for coefficients.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="op">(</span><span class="va">ci</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">delivery_lm</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              2.5 % 97.5 %
(Intercept) 0.06675 4.6157
cases       1.26182 1.9700
distance    0.00689 0.0219</code></pre>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>ci <span class="op">=</span> delivery_ols.conf_int()</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>ci</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  0         1
Intercept  0.066752  4.615710
cases      1.261825  1.969990
distance   0.006892  0.021878</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>These are <strong>marginal</strong> CIs separately for each <span class="math inline">\(b_j\)</span>. These interval estimates do not take correlation of coefficients into account. One coefficient may be higher when another is lower. We can only use the intervals one at a time when doing interval estimation. When we want to do interval estimation for several coefficients together at the same time, these intervals are not that accurate.</p>
<!-- ::: notes -->
<!-- - Each of the statistics $\frac{b_j - \beta_j}{\sqrt{\hat{\sigma}^2C_{jj}}}, j = 0, 1, 2, \dots, k$ follows $t_{n-p}$ distribution, where $\hat{\sigma}^2 = MS_{res}$, and $C_{jj}$ is the $j$-th diagonal element of ${\bf (X'X)}^{-1}$. -->
<!-- - The $(1-\alpha)100\%$ CI for $\beta_j$, $j = 0, 1, \dots, k$ is -->
<!-- $\left(b_j- t_{\alpha/2, n-p} \sqrt{\hat{\sigma}^2C_{jj}}, \quad b_j + t_{\alpha/2, n-p} \sqrt{\hat{\sigma}^2C_{jj}}\right)$ -->
<!-- ::: -->
<!-- ## Correlated Coefficients {visibility="hidden"} -->
<p>Covariance of random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, <span class="math inline">\(\cov(X, Y)\)</span> is defined as <span class="math display">\[\small \cov(X, Y) = E[(X - E(X))(Y - E(Y))]\]</span> <!-- :::  --></p>
<!-- ::: question -->
<!-- What is $\cov(X, X)$? -->
<!-- ::: -->
<div class="columns">
<div class="column" style="width:50%;">
<p>The covariance matrix of the coefficient vector <span class="math inline">\({\bf b} = (b_0, b_1, b_2)'\)</span> is <span class="math display">\[\scriptsize \begin{align} \cov({\bf b}) &amp;= \begin{bmatrix} \cov(b_0, b_0) &amp; \cov(b_0, b_1) &amp; \cov(b_0, b_2) \\ \cov(b_1, b_0) &amp; \cov(b_1, b_1) &amp; \cov(b_1, b_2) \\ \cov(b_2, b_0) &amp; \cov(b_2, b_1) &amp; \cov(b_2, b_2) \end{bmatrix} \end{align}\]</span></p>
</div><div class="column" style="width:50%;">
<p>The correlation matrix of the coefficient vector <span class="math inline">\({\bf b} = (b_0, b_1, b_2)'\)</span> is <span class="math display">\[\scriptsize \begin{align} \cor({\bf b}) &amp;= \begin{bmatrix} 1 &amp; r_{01} &amp; r_{02} \\ r_{10} &amp; 1 &amp; r_{12} \\ r_{20} &amp; r_{21} &amp; 1 \end{bmatrix} \end{align}\]</span></p>
</div>
</div>
<p><span style="color:blue"> In fact, all <span class="math inline">\(b_j\)</span> are correlated! </span></p>
<!-- ## Correlated Coefficients -->
<!-- :::: {.columns} -->
<!-- ::: {.column width="50%"} -->
<hr>
<p><span style="color:blue"> <strong>Example: Correlated Coefficients</strong> </span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">R</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">Python</a></li>
</ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<p>We use <code><a href="https://rdrr.io/r/stats/vcov.html">vcov()</a></code> to obtain the variance-covariance matrix of <span class="math inline">\(b_j\)</span>s. The square root of its diagonal terms are <span class="math inline">\(se(b_0)\)</span>, <span class="math inline">\(se(b_1)\)</span>, and <span class="math inline">\(se(b_2)\)</span> respectively.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## variance-covariance matrix</span></span>
<span><span class="op">(</span><span class="va">V</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/vcov.html">vcov</a></span><span class="op">(</span><span class="va">delivery_lm</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            (Intercept)     cases  distance
(Intercept)    1.202817 -0.047263 -8.89e-04
cases         -0.047263  0.029150 -5.08e-04
distance      -0.000889 -0.000508  1.31e-05</code></pre>
</div>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## standard error</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">V</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)       cases    distance 
    1.09673     0.17073     0.00361 </code></pre>
</div>
</div>
<!-- ::: -->
<!-- ::: {.column width="50%"} -->
<p>We can convert the covariance matrix into a correlation matrix using <code><a href="https://rdrr.io/r/stats/cor.html">cov2cor()</a></code>. Clearly <span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_2\)</span> are negatively correlated. The individual CI previously obtained ignores the correlation between <span class="math inline">\(b_j\)</span>s.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## correlation matrix</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cov2cor</a></span><span class="op">(</span><span class="va">V</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            (Intercept)  cases distance
(Intercept)       1.000 -0.252   -0.224
cases            -0.252  1.000   -0.824
distance         -0.224 -0.824    1.000</code></pre>
</div>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<p>We use <code>cov_params()</code> to obtain the variance-covariance matrix of <span class="math inline">\(b_j\)</span>s. The square root of its diagonal terms are <span class="math inline">\(se(b_0)\)</span>, <span class="math inline">\(se(b_1)\)</span>, and <span class="math inline">\(se(b_2)\)</span> respectively.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">## variance-covariance matrix</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>V <span class="op">=</span> delivery_ols.cov_params()</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>V</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Intercept     cases  distance
Intercept   1.202817 -0.047263 -0.000889
cases      -0.047263  0.029150 -0.000508
distance   -0.000889 -0.000508  0.000013</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">## standard error</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>np.sqrt(np.diag(V))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>array([1.09673017, 0.17073492, 0.00361309])</code></pre>
</div>
</div>
<p>We can convert the covariance matrix into a correlation matrix using <code>sm.stats.moment_helpers.cov2corr()</code>. Clearly <span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_2\)</span> are negatively correlated. The individual CI previously obtained ignores the correlation between <span class="math inline">\(b_j\)</span>s.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="co">## correlation matrix</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>sm.stats.moment_helpers.cov2corr(V)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>array([[ 1.        , -0.25240355, -0.22433649],
       [-0.25240355,  1.        , -0.824215  ],
       [-0.22433649, -0.824215  ,  1.        ]])</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>How do we specify a confidence level that applies <strong>simultaneously</strong> to a <strong>set</strong> of interval estimates? For example, a <span class="math inline">\(95\%\)</span> confidence “interval” for both <span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_2\)</span>?</p>
<!-- ## Confidence Region -->
<p>The <span class="math inline">\((1-\alpha)100\%\)</span> CI for a <strong>set</strong> of <span class="math inline">\(b_j\)</span>s will be an <strong>elliptically-shaped region</strong>! The blue region below is the 95% confidence region for <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span>. The black dashed lines indicate the 95% Wald CI for <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span>.</p>
<p>With repeated sampling, 95% of such ellipses will simultaneously include <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span>, if the fitted model is correct and normality holds. The orientation of the ellipse reflects the negative correlation between the estimates. Contrast the 95% confidence ellipse with the marginal 95% confidence intervals, also shown on the plot. Some points within the marginal intervals (red point) — with smaller values for both of the coefficients, for example — are implausible according to the joint region. Similarly, the joint region includes values of the coefficient for <code>cases</code> (black point), for example, that are excluded from the marginal interval.</p>
<!-- :::: {.columns} -->
<!-- ::: {.column width="50%"} -->
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb54"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mgp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2.8</span>, <span class="fl">0.9</span>, <span class="fl">0</span><span class="op">)</span>, mar <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">2</span>, <span class="fl">0</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">## confidence region</span></span>
<span><span class="fu">car</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Ellipses.html">confidenceEllipse</a></span><span class="op">(</span></span>
<span>    <span class="va">delivery_lm</span>, </span>
<span>    levels <span class="op">=</span> <span class="fl">0.95</span>, fill <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>    which.coef <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"cases"</span>, <span class="st">"distance"</span><span class="op">)</span>, </span>
<span>    main <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span></span>
<span>        <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"95% Confidence Region for "</span>, </span>
<span>              <span class="va">beta</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="st">" and "</span>,  <span class="va">beta</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span></span>
<span>        <span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span><span class="co">## marginal CI for cases</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span>v <span class="op">=</span> <span class="va">ci</span><span class="op">[</span><span class="fl">2</span>, <span class="op">]</span>, lty <span class="op">=</span> <span class="fl">2</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span>  </span>
<span><span class="co">## marginal CI for distance</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span>h <span class="op">=</span> <span class="va">ci</span><span class="op">[</span><span class="fl">3</span>, <span class="op">]</span>, lty <span class="op">=</span> <span class="fl">2</span>, lwd <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">1.4</span>, y <span class="op">=</span> <span class="fl">0.01</span>, col <span class="op">=</span> <span class="st">"red"</span>, cex <span class="op">=</span> <span class="fl">2</span>, pch <span class="op">=</span> <span class="fl">16</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">2</span>, y <span class="op">=</span> <span class="fl">0.008</span>, col <span class="op">=</span> <span class="st">"black"</span>, cex <span class="op">=</span> <span class="fl">2</span>, pch <span class="op">=</span> <span class="fl">16</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- ::: -->
<!-- ::: {.column width="50%"} -->
<!-- # ```{r} -->
<!-- # #| out-width: 100% -->
<!-- # par(mgp = c(2.8, 0.9, 0), mar = c(4, 4, 2, 0)) -->
<!-- # car::confidenceEllipse(delivery_lm, levels = 0.95, which.coef = c("cases", "distance"),  -->
<!-- #                        main = expression(paste("95% Confidence Region for ", beta[1], " and ",  beta[2]))) -->
<!-- # abline(v = ci[2, ], lty = 2, lwd = 2)  ## marginal CI for cases -->
<!-- # abline(h = ci[3, ], lty = 2, lwd = 2)  ## marginal CI for distance -->
<!-- # points(x = 1.4, y = 0.01, col = "red", cex = 2, pch = 16) -->
<!-- # points(x = 2, y = 0.008, col = "black", cex = 2, pch = 16) -->
<!-- # ``` -->
<!-- ::: -->
<!-- :::: -->
<!-- - Some points  within the marginal intervals are implausible according to the joint region. -->
<!-- - The joint region includes values of the coefficient for cases (black), for example, that are excluded from the marginal interval. -->
<!-- ::: notes -->
<!-- - Bonferroni -->
<!-- - Scheffe S-method -->
<!-- - maximum modulus t procedure -->
<!-- ::: -->
</section><section id="ci-for-the-mean-response-ey-mid-bf-x_0" class="level3" data-number="28.3.4"><h3 data-number="28.3.4" class="anchored" data-anchor-id="ci-for-the-mean-response-ey-mid-bf-x_0">
<span class="header-section-number">28.3.4</span> CI for the Mean Response <span class="math inline">\(E(y \mid {\bf x}_0)\)</span>
</h3>
<p>The fitted value at a point <span class="math inline">\({\bf x}_0 = (1, x_{01}, x_{02}, \dots, x_{0k})'\)</span> is <span class="math display">\[\hat{y}_0 = b_0 + b_1x_{01} + \cdots + b_kx_{0k}\]</span></p>
<p>This is an unbiased estimator for <span class="math inline">\(E(y \mid {\bf x}_0)\)</span>. <!-- - $\frac{\hat{y}_0 - E(y|{\bf x}_0)}{\sqrt{\hat{\sigma}^2{\bf x}_0'{\bf (X'X)}^{-1}{\bf x}_0}}\sim t_{n-p}$. --></p>
<p>The <span class="math inline">\((1-\alpha)100\%\)</span> CI for <span class="math inline">\(E(y \mid {\bf x}_0)\)</span> is <span class="math display">\[\left(\hat{y}_0 - t_{\alpha/2, n-p} ~ se(\hat{y}_0), \quad \hat{y}_0 + t_{\alpha/2, n-p} ~ se(\hat{y}_0)\right).\]</span> It is from the fact that <span class="math inline">\(\frac{\hat{y}_0 - E(y|{\bf x}_0)}{se(\hat{y}_0)}\sim t_{n-p}\)</span> where <span class="math inline">\(se(\hat{y}_0)\)</span> is a function of <span class="math inline">\(\hat{\sigma}\)</span>, <span class="math inline">\(x_{ij}\)</span>s, and <span class="math inline">\({\bf x}_0\)</span>.</p>
<hr>
<p><span style="color:blue"> <strong>Example: CI for the Mean Response</strong> </span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true">R</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false">Python</a></li>
</ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<p>We learned how to use <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> in the previous chapter. For MLR, we need to specify the 2 predictor values <code>cases = 8</code>, and <code>distance = 275</code>, and save it as a data frame in the <code>newdata</code> argument. Note that the name <code>cases</code> and <code>distance</code> should be exactly the same as their column name of the data <code>delivery_data</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">delivery_lm</span>,</span>
<span>        newdata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>cases <span class="op">=</span> <span class="fl">8</span>, distance <span class="op">=</span> <span class="fl">275</span><span class="op">)</span>,</span>
<span>        interval <span class="op">=</span> <span class="st">"confidence"</span>, level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   fit  lwr  upr
1 19.2 17.7 20.8</code></pre>
</div>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<p>We learned how to use <code>get_prediction()</code> in the previous chapter. For MLR, we need to specify the 2 predictor values <code>cases = 8</code>, and <code>distance = 275</code>, and save it as a DataFrame in the <code>exog</code> argument. Note that the name <code>cases</code> and <code>distance</code> should be exactly the same as their column name of the data <code>delivery_data</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>new_data <span class="op">=</span> pd.DataFrame({<span class="st">'cases'</span>: [<span class="dv">8</span>], <span class="st">'distance'</span>: [<span class="dv">275</span>]})</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>predict <span class="op">=</span> delivery_ols.get_prediction(exog<span class="op">=</span>new_data)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>predict.conf_int()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>array([[17.65389505, 20.79473705]])</code></pre>
</div>
</div>
</div>
</div>
</div>
<!-- ::: notes -->
<!-- - The fitted value at a point ${\bf x}_0 = (1, x_{01}, x_{02}, \dots, x_{0k})'$ is $\hat{y}_0 = {\bf x}_0'\bf b$. -->
<!-- - This is an unbiased estimator for $E(y \mid {\bf x}_0)$. -->
<!-- - $\frac{\hat{y}_0 - E(y|{\bf x}_0)}{\sqrt{\hat{\sigma}^2{\bf x}_0'{\bf (X'X)}^{-1}{\bf x}_0}}\sim t_{n-p}$. -->
<!-- - The $(1-\alpha)100\%$ CI for $E(y \mid {\bf x}_0)$ is -->
<!-- $\left(\hat{y}_0 - t_{\alpha/2, n-p} \sqrt{\hat{\sigma}^2{\bf x}_0'{\bf (X'X)}^{-1}{\bf x}_0}, \quad \hat{y}_0 + t_{\alpha/2, n-p} \sqrt{\hat{\sigma}^2{\bf x}_0'{\bf (X'X)}^{-1}{\bf x}_0}\right)$ -->
<!-- ```{r} -->
<!-- predict(delivery_lm, -->
<!--         newdata = data.frame(cases = 8, distance = 275), -->
<!--         interval = "confidence", level = 0.95) -->
<!-- ``` -->
<!-- ::: -->
</section><section id="pi-for-new-observations" class="level3" data-number="28.3.5"><h3 data-number="28.3.5" class="anchored" data-anchor-id="pi-for-new-observations">
<span class="header-section-number">28.3.5</span> PI for New Observations</h3>
<p>Often we also want to predict the future observation <span class="math inline">\(y_0\)</span> when <span class="math inline">\({\bf x} = {\bf x}_0\)</span>. A point estimate is <span class="math inline">\(\hat{y}_0 = b_0 + b_1x_{01} + \cdots + b_kx_{0k}\)</span>, same as the point estimate of the mean response. When we can only use one single value to predict the mean response or a new observation value, <span class="math inline">\(\hat{y}_0\)</span> is the best we can do. The <span class="math inline">\((1-\alpha)100\%\)</span> PI for <span class="math inline">\(y_0\)</span> is <span class="math display">\[\left(\hat{y}_0 - t_{\alpha/2, n-p} ~se(y_0 - \hat{y}_0), \quad \hat{y}_0 + t_{\alpha/2, n-p} ~se(y_0 - \hat{y}_0)\right)\]</span></p>
<hr>
<p><span style="color:blue"> <strong>Example: PI for New Observations</strong> </span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true">R</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false">Python</a></li>
</ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<p>When predicting a new observation with uncertainty, we use <code>interval = "predict"</code>. The interpretation is the same as the one in SLR.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">delivery_lm</span>,</span>
<span>        newdata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>cases <span class="op">=</span> <span class="fl">8</span>, distance <span class="op">=</span> <span class="fl">275</span><span class="op">)</span>,</span>
<span>        interval <span class="op">=</span> <span class="st">"predict"</span>, level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   fit  lwr  upr
1 19.2 12.3 26.2</code></pre>
</div>
</div>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<p>When predicting a new observation with uncertainty, we use <code>summary_frame()</code>, then grab ‘obs_ci_lower’ and ‘obs_ci_upper’ from the output. The interpretation is the same as the one in SLR.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>summary_frame <span class="op">=</span> predict.summary_frame(alpha<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>summary_frame[[<span class="st">'obs_ci_lower'</span>, <span class="st">'obs_ci_upper'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   obs_ci_lower  obs_ci_upper
0     12.284559     26.164073</code></pre>
</div>
</div>
</div>
</div>
</div>
<!-- ::: notes -->
<!-- - Predict the future observation $y_0$ when ${\bf x} = {\bf x}_0$. -->
<!-- - A point estimate is $\hat{y}_0 = {\bf x}_0'\bf b$. -->
<!-- - The $(1-\alpha)100\%$ PI for $y_0$ is -->
<!-- $\left(\hat{y}_0 - t_{\alpha/2, n-p} \sqrt{\hat{\sigma}^2\left(1+{\bf x}_0'{\bf (X'X)}^{-1}{\bf x}_0\right)}, \quad \hat{y}_0 + t_{\alpha/2, n-p} \sqrt{\hat{\sigma}^2\left(1+{\bf x}_0'{\bf (X'X)}^{-1}{\bf x}_0\right)}\right)$ -->
<!-- ```{r} -->
<!-- predict(delivery_lm, -->
<!--         newdata = data.frame(cases = 8, distance = 275), -->
<!--         interval = "predict", level = 0.95) -->
<!-- ``` -->
<!-- ::: -->
</section><section id="predictor-effect-plots" class="level3" data-number="28.3.6"><h3 data-number="28.3.6" class="anchored" data-anchor-id="predictor-effect-plots">
<span class="header-section-number">28.3.6</span> Predictor Effect Plots</h3>
<p>A complete picture of the regression surface requires drawing a <span class="math inline">\(p\)</span>-dimensional graph.</p>
<p><strong>Predictor effect plots</strong> look at 1 or 2D plots for each predictor.</p>
<p>To plot the predictor effect plot for <span class="math inline">\(x_j\)</span>, <span class="math inline">\(x_1\)</span> for example, we</p>
<ul>
<li><p>fix the values of all other predictors (<span class="math inline">\(x_2\)</span> in the example)</p></li>
<li><p>substitute these fixed values into the fitted regression equation.</p></li>
</ul>
<p>Usually we fix all other predictors (<span class="math inline">\(x_2\)</span> in the example) at their average. In our example, we have <span class="math inline">\(\hat{y} = 2.34 + 1.62 ~x_1 + 0.014 (409.28)\)</span>. Note that the slope of <span class="math inline">\(x_1\)</span> would be the <strong>same</strong> for <em>any</em> choice of fixed values of other predictors, while the intercept depends on the values of other predictors.</p>
<!-- ::: notes -->
<!-- - A complete picture of the regression surface generated by the fitted model requires drawing a $p$-dimensional graph. -->
<!-- - Fix $x_1$ at its average, $\hat{y} = 2.34 + 1.62 (8.76) + 0.014 ~x_2$ -->
<!-- - The slope would be the **same** for *any* choice of fixed values of other predictors. -->
<!-- ::: -->
<!-- ## [R Lab]{.pink} Predictor Effect Plots -->
<hr>
<p><span style="color:blue"> <strong>Example: Predictor Effect Plots</strong> </span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true">R</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false">Python</a></li>
</ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<p>The command <code><a href="https://rdrr.io/pkg/effects/man/predictorEffects.html">predictorEffects()</a></code> in the <code>effects</code> package is used to generate the predictor effect plots.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://www.r-project.org">effects</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu">effects</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/effects/man/predictorEffects.html">predictorEffects</a></span><span class="op">(</span>mod <span class="op">=</span> <span class="va">delivery_lm</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>The shaded area represents pointwise 95% confidence interval about the fitted line, without correction for simultaneous statistical inference. The short vertical lines at the bottom indicate the values of predictors. The interval length is larger when the predictor value is away from its average. Since our model is linear, the mean of time increases linearly as cases or distance increases.</p>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<p>So far to my knowledge there is no Python function for creating predictor effect plots. However, <code>statsmodels</code> does offer other useful <a href="https://www.statsmodels.org/stable/examples/notebooks/generated/regression_plots.html">regression plots</a>.</p>
</div>
</div>
</div>
<!-- - rug plot -->
<!-- -  -->
<!-- - Given x2 variable in the model, what is the effect on x1 on the response. -->
<!-- - Without correction for simultaneous statistical inference -->
<!-- - plot(effects::predictorEffects(mod = delivery_lm, confint = list(type = "Scheffe"))) -->
<!-- 'arg' should be one of “pointwise”, “Scheffe”, “scheffe” -->
<!-- ::: notes -->
<!-- ::: -->
</section></section><section id="hypothesis-testing" class="level2" data-number="28.4"><h2 data-number="28.4" class="anchored" data-anchor-id="hypothesis-testing">
<span class="header-section-number">28.4</span> Hypothesis Testing</h2>
<p>In this section we talk about two tests: Test for significance of regression and Tests on individual coefficients. In fact, one can test whether or not the coefficients form any linear combination relationship, called the <strong>general linear hypotheses</strong>. We leave this part of discussion in the Regression Analysis course.</p>
<!-- <h2> Test for Significance of Regression </h2> -->
<!-- <h2> Tests on Individual Coefficients </h2> -->
<!-- <h2> Tests on Subsets of Coefficients (Later) </h2> -->
<!-- ::: notes -->
<!-- - Test for Significance: test if there is any regressor that has a significant effect on predicting $Y$ or explaining the variation of $Y$. -->
<!-- - In a Test for Significance, we are looking all the regressors. -->
<!-- - Tests on Individual Coefficients: we are only interested in single one predictor's effect. -->
<!-- - But sometimes, we may be interested in a subset of Coefficients, not all, not single one, but two or three coefficients. And we'll see how to do this kind of test later. -->
<!-- - Finally, we'll learn the so-called General Linear Hypothesis that can perform a quite general test. -->
<!-- - The three tests above are in fact special case of the General Linear Hypothesis. -->
<!-- ::: -->
<section id="test-for-significance-of-regression" class="level3" data-number="28.4.1"><h3 data-number="28.4.1" class="anchored" data-anchor-id="test-for-significance-of-regression">
<span class="header-section-number">28.4.1</span> Test for Significance of Regression</h3>
<p><strong>Test for significance</strong> determines if there is a <strong>linear</strong> relationship between the response and <strong>any</strong> of the regressor variables. In other words, we are testing</p>
<p><span style="color:blue"> <span class="math inline">\(H_0: \beta_1 = \beta_2 = \cdots = \beta_k = 0 \quad H_1: \beta_j \ne 0 \text{ for at least one } j\)</span> </span></p>
<p>As long as there is one predictor has a significant impact on the response, <span class="math inline">\(H_0\)</span> should be rejected. When <span class="math inline">\(\beta_1 = \beta_2 = \cdots = \beta_k = 0\)</span>, it means that the regrssion model has no explanatory power on explaining any variation of the response from the regressors put in the regression model. The regression model is not helping at all. To interpret it more precisely, when we fail to <span class="math inline">\(H_0: \beta_1 = \beta_2 = \cdots = \beta_k = 0\)</span>, there are three possibilities. First, it could mean that all the predictors have no relationship with the response. Second, remember our model is a linear model, and <span class="math inline">\(\beta_j\)</span>s measure linear effect of <span class="math inline">\(x_j\)</span>s on <span class="math inline">\(y\)</span>. It may just mean there is no linear relationship between any <span class="math inline">\(x_j\)</span> and <span class="math inline">\(y\)</span> given all other regressors are in the model. Some other types of relationship may exist between the predictors and the response. Third, we make a Type II error that <span class="math inline">\(H_0\)</span> is actually false, and at least one regressor is linearly related to the response, again given all other predictors are in the model.</p>
<!-- - The $F$ test of ANOVA performs the test. -->
<!-- # ```{r} -->
<!-- # knitr::include_graphics("./images/img-model/anova_mlr.png") -->
<!-- # ``` -->
<!-- - $SS_T = {\bf y'y} - \frac{\left(\sum_{i=1}^n y_i \right)^2}{n}$, $SS_R = {\bf b'X'y}-\frac{\left(\sum_{i=1}^n y_i \right)^2}{n}$, $SS_{res} = {\bf y'y} - {\bf b'X'y}$ -->
<p>The test is usually conducted by checking the ANOVA table of MLR as shown below. When <span class="math inline">\(k=1\)</span>, it becomes the ANOVA table of SLR.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Source of Variation</th>
<th style="text-align: center;">SS</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">MS</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">
<span class="math inline">\(p\)</span>-value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Regression</td>
<td style="text-align: center;"><span class="math inline">\(SS_R\)</span></td>
<td style="text-align: center;"><span class="math inline">\(k\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_R\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{MS_R}{MS_{res}} = F_{test}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(P(F_{k, n-k-1} &gt; F_{test})\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Residual</td>
<td style="text-align: center;"><span class="math inline">\(SS_{res}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n-k-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{res}\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;"><span class="math inline">\(SS_{T}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n-1\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>We reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(F_{test} &gt; F_{\alpha, k, n - k - 1}\)</span>. In SLR, test for significance is the same as testing individual coefficient <span class="math inline">\(\beta_1 = 0\)</span> because there is only one predictor, and testing its corresponding coefficient is equivalent to testing all the coefficients.</p>
<p>We may reject the null when the truth is all beta’s are nonzero, or only one single beta is nonzero. And we may need further <em>post hoc</em> analysis to see which coefficients are nonzero.</p>
<p>If there is only one nonzero coefficient, and we reject the null, basically, the nearly all the variation of <span class="math inline">\(Y\)</span> is explained by the corresponding predictor that has the nonzero beta coefficient. We can still say the model is significant because that particular predictor has a significant effect on explaining <span class="math inline">\(y\)</span>.</p>
<!-- - Another way to represent SS_T -->
<!-- ::: notes -->
<!-- - In SLR, test for significance is the same as testing individual coefficient $\beta_1 = 0$. -->
<!-- - We may reject the null when the truth is all beta's are nonzero, or only one single beta is nonzero. -->
<!-- - If there is only one nonzero beta, and we reject the null, basically, the nearly all the variation of Y is explained by the corresponding predictor that has the nonzero beta. -->
<!-- - We can still say the model is significant because that particular predictor has a significant effect on explaining y. -->
<!-- - Another way to represent SS_T -->
<!-- ::: -->
<!-- ## [R Lab]{.pink} Test for Significance -->
<hr>
<p><span style="color:blue"> <strong>Example: Test for Significance</strong> </span></p>
<p><span style="color:blue"> <span class="math inline">\(H_0: \beta_{1} = \beta_{2} = 0 \quad H_1: \beta_j \ne 0 \text{ for at least one } j\)</span> </span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-9-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-1" role="tab" aria-controls="tabset-9-1" aria-selected="true">R</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-2" role="tab" aria-controls="tabset-9-2" aria-selected="false">Python</a></li>
</ul>
<div class="tab-content">
<div id="tabset-9-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-9-1-tab">
<p>If we check the summary of the fitted result, it shows some t values and p-values, but no ANOVA table shows up.</p>
<div class="cell" data-layout-align="center" data-output.lines="[9,10,11,12,13,14,15,16,17,18,19]">
<div class="sourceCode" id="cb64"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">summ_delivery</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="my_class800"><code>...
Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.34123    1.09673    2.13  0.04417 *  
cases        1.61591    0.17073    9.46  3.3e-09 ***
distance     0.01438    0.00361    3.98  0.00063 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.26 on 22 degrees of freedom
Multiple R-squared:  0.96,  Adjusted R-squared:  0.956 
F-statistic:  261 on 2 and 22 DF,  p-value: 4.69e-16
...</code></pre>
</div>
</div>
</div>
<div id="tabset-9-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-2-tab">
<p>If we check the summary of the fitted result, it shows some t values and p-values, but no ANOVA table shows up.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>delivery_ols.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>OLS Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>time</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.960</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>OLS</td>
<td data-quarto-table-cell-role="th">Adj. R-squared:</td>
<td>0.956</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>Least Squares</td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>261.2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Tue, 15 Oct 2024</td>
<td data-quarto-table-cell-role="th">Prob (F-statistic):</td>
<td>4.69e-16</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>10:36:45</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-63.415</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>25</td>
<td data-quarto-table-cell-role="th">AIC:</td>
<td>132.8</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>22</td>
<td data-quarto-table-cell-role="th">BIC:</td>
<td>136.5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>2</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true"><tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intercept</td>
<td>2.3412</td>
<td>1.097</td>
<td>2.135</td>
<td>0.044</td>
<td>0.067</td>
<td>4.616</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">cases</td>
<td>1.6159</td>
<td>0.171</td>
<td>9.464</td>
<td>0.000</td>
<td>1.262</td>
<td>1.970</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">distance</td>
<td>0.0144</td>
<td>0.004</td>
<td>3.981</td>
<td>0.001</td>
<td>0.007</td>
<td>0.022</td>
</tr>
</tbody></table>
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true"><tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Omnibus:</td>
<td>0.421</td>
<td data-quarto-table-cell-role="th">Durbin-Watson:</td>
<td>1.170</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Omnibus):</td>
<td>0.810</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>0.010</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Skew:</td>
<td>0.032</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.995</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>3.073</td>
<td data-quarto-table-cell-role="th">Cond. No.</td>
<td>873.</td>
</tr>
</tbody></table>
<br><br>Notes:<br>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
</div>
</div>
</div>
</div>
</div>
<p>How do we obtain the ANOVA Table?</p>
<!-- ## [R Lab]{.pink} Wrong ANOVA Table -->
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">Source of Variation</th>
<th style="text-align: center;">SS</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">MS</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">
<span class="math inline">\(p\)</span>-value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Regression</td>
<td style="text-align: center;"><span class="math inline">\(SS_R\)</span></td>
<td style="text-align: center;"><span class="math inline">\(k\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_R\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{MS_R}{MS_{res}} = F_{test}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(P(F_{k, n-k-1} &gt; F_{test})\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Residual</td>
<td style="text-align: center;"><span class="math inline">\(SS_{res}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n-k-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_{res}\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;"><span class="math inline">\(SS_{T}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n-1\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-10-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-1" role="tab" aria-controls="tabset-10-1" aria-selected="true">R</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-2" role="tab" aria-controls="tabset-10-2" aria-selected="false">Python</a></li>
</ul>
<div class="tab-content">
<div id="tabset-10-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-10-1-tab">
<p>We may think using <code>anova(delivery_lm)</code> as we do for SLR.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">delivery_lm</span><span class="op">)</span> <span class="co">## This is for sequential F-test</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: time
          Df Sum Sq Mean Sq F value  Pr(&gt;F)    
cases      1   5382    5382   506.6 &lt; 2e-16 ***
distance   1    168     168    15.8 0.00063 ***
Residuals 22    234      11                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</div>
<div id="tabset-10-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-2-tab">
<p>We may think using <code>sm.stats.anova_lm(delivery_ols)</code> as we do for SLR.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>sm.stats.anova_lm(delivery_ols)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            df       sum_sq      mean_sq           F        PR(&gt;F)
cases      1.0  5382.408797  5382.408797  506.619363  1.112549e-16
distance   1.0   168.402126   168.402126   15.850854  6.312469e-04
Residual  22.0   233.731677    10.624167         NaN           NaN</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Unfortunately, this ANOVA table is so called <strong>Type-I</strong> ANOVA table in literature for a <strong>sequential F-test</strong>, which is <em>NOT</em> what we want.</p>
<!-- # ```{r} -->
<!-- #  -->
<!-- # knitr::include_graphics("./images/img-model/anova_mlr.png") -->
<!-- # ``` -->
<!-- ## [R Lab]{.pink} ANOVA Table: Null vs. Full -->
<!-- ::: alert -->
<p>To obtain the correct ANOVA table, we need to view the test in a different way. Testing coefficients is like model comparison: We are comparing two models, the <strong>full model</strong> having all the predictors <span class="math inline">\(x_1, \dots, x_k\)</span> in the model with zero or nonzero <span class="math inline">\(\beta\)</span> coefficients with the <strong>null model</strong> under <span class="math inline">\(H_0\)</span>. Mathematically,</p>
<ul>
<li><p><strong>Full model</strong>: <span class="math inline">\(y = \beta_0 + \beta_1x_1 + \cdots + \beta_kx_k + \epsilon\)</span></p></li>
<li><p><strong>Null model</strong>: <span class="math inline">\(y = \beta_0 + \epsilon\)</span> because <span class="math inline">\(\beta_1 = \beta_2 = \cdots = \beta_k = 0\)</span> under <span class="math inline">\(H_0\)</span>. The null model is the model with the intercept only.</p></li>
</ul>
<p>The idea is that we are trying to see how close the full model fitting is close to the null model fitting. If <span class="math inline">\(H_0\)</span> is true, then using the full model will be more likely to have similar result to the null models result because the full model will have all the coefficients being negligibly zero. The two models are more likely to be indistinguishable. When <span class="math inline">\(H_0\)</span> is not true, and some <span class="math inline">\(\beta_j\)</span>s are away from zero, the two models will have pretty different fitting results.</p>
<!-- Compare the full model with the model under $H_0$**! -->
<!-- ::: -->
<!-- :::: {.columns} -->
<!-- ::: {.column width="50%"} -->
<p>In our example,</p>
<ul>
<li><p><strong>Full model</strong>: including both <code>cases</code> and <code>distance</code> predictors</p></li>
<li><p><strong>Null model</strong>: no predictors <span class="math inline">\((\beta_1 = \beta_2 = 0)\)</span></p></li>
</ul>
<p>The ANOVA table for the example is</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/img-model/anova_ex.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<!-- ::: -->
<!-- ::: {.column width="50%"} -->
<!-- ::: {.fragment} -->
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-11-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-1" role="tab" aria-controls="tabset-11-1" aria-selected="true">R</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-11-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-11-2" role="tab" aria-controls="tabset-11-2" aria-selected="false">Python</a></li>
</ul>
<div class="tab-content">
<div id="tabset-11-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-11-1-tab">
<p>To generate the ANOVA table using R, we first create the null model and save its fitted result. When there is no predictors in the model, we write <code>time ~ 1</code> where <code>1</code> represents the intercept term. Then we are comparing the two model fitted results using <code>anova(null_lm, delivery_lm)</code>.</p>
<div class="cell" data-layout-align="center" data-output.lines="[1,2,3,4,5,6,7]">
<div class="sourceCode" id="cb71"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## regression with intercept only</span></span>
<span><span class="va">null_lm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">time</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">delivery_data</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">null_lm</span>, <span class="va">delivery_lm</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>...
Analysis of Variance Table

Model 1: time ~ 1
Model 2: time ~ cases + distance
  Res.Df  RSS Df Sum of Sq   F  Pr(&gt;F)    
1     24 5785                             
2     22  234  2      5551 261 4.7e-16 ***
...</code></pre>
</div>
</div>
<!-- ::: -->
<!-- ::: -->
<!-- :::: -->
<p>Notice that the output is not exactly the same as the ANOVA table, but both are equivalent. We just need to carefully and correctly interpret the R output. The first row shows the <span class="math inline">\(SS_T\)</span> value in the <code>RSS</code> column. <code>RSS</code> is the residual sum of squares <span class="math inline">\(SS_{res}\)</span>. The first model (Model 1) is the null model. Because there is no predictors, all variation of <span class="math inline">\(y\)</span> is due to random errors, and therefore there is no <span class="math inline">\(SS_R\)</span>, and <span class="math inline">\(SS_{res} = SS_T\)</span>.</p>
<p>The second row provides information about <span class="math inline">\(SS_R\)</span> and <span class="math inline">\(SS_{res}\)</span> of the full model (Model 2). <span class="math inline">\(SS_R\)</span> is shown in the column <code>Sum of Sq</code>, and <span class="math inline">\(SS_{res}\)</span> again in the column <code>RSS</code>.</p>
<p>In Row 2, <code>Res.Df</code> is the residual degrees of freedom, and <code>Df</code> is the regression degrees of freedom. The value 24 in Row 1, the residual degrees of freedom of the null model, is worked as the <em>total</em> degrees of freedom, the same idea that its <span class="math inline">\(SS_{res}\)</span> works as <span class="math inline">\(SS_T\)</span>.</p>
</div>
<div id="tabset-11-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-11-2-tab">
<p>To generate the ANOVA table using Python, we first create the null model and save its fitted result. When there is no predictors in the model, we write <code>time ~ 1</code> where <code>1</code> represents the intercept term. Then we are comparing the two model fitted results using <code>sm.stats.anova_lm(null_ols, delivery_ols)</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co">## regression with intercept only</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>null_ols <span class="op">=</span> ols(<span class="st">'time ~ 1'</span>, data<span class="op">=</span>delivery_data).fit()</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>sm.stats.anova_lm(null_ols, delivery_ols)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   df_resid          ssr  df_diff      ss_diff           F        Pr(&gt;F)
0      24.0  5784.542600      0.0          NaN         NaN           NaN
1      22.0   233.731677      2.0  5550.810923  261.235109  4.687422e-16</code></pre>
</div>
</div>
<p>Notice that the output is not exactly the same as the ANOVA table, but both are equivalent. We just need to carefully and correctly interpret the Python output. The first row shows the <span class="math inline">\(SS_T\)</span> value in the <code>ssr</code> column. <code>ssr</code> is the sum of squares residual <span class="math inline">\(SS_{res}\)</span>. The first model (Model 1) is the null model. Because there is no predictors, all variation of <span class="math inline">\(y\)</span> is due to random errors, and therefore there is no <span class="math inline">\(SS_R\)</span>, and <span class="math inline">\(SS_{res} = SS_T\)</span>.</p>
<p>The second row provides information about <span class="math inline">\(SS_R\)</span> and <span class="math inline">\(SS_{res}\)</span> of the full model (Model 2). <span class="math inline">\(SS_R\)</span> is shown in the column <code>ss_diff</code>, and <span class="math inline">\(SS_{res}\)</span> again in the column <code>ssr</code>.</p>
<p>In Row 2, <code>df_resid</code> is the residual degrees of freedom, and <code>df_diff</code> is the regression degrees of freedom. The value 24 in Row 1, the residual degrees of freedom of the null model, is worked as the <em>total</em> degrees of freedom, the same idea that its <span class="math inline">\(SS_{res}\)</span> works as <span class="math inline">\(SS_T\)</span>.</p>
</div>
</div>
</div>
<p>The output does not provide the mean square information, but it can be easily calculated.</p>
<!-- - first row: info of $SS_T$ -->
<!-- - second row: info of $SS_R$ and $SS_{res}$ -->
<!-- - does not show MS -->
</section><section id="r2-and-adjusted-r2" class="level3" data-number="28.4.2"><h3 data-number="28.4.2" class="anchored" data-anchor-id="r2-and-adjusted-r2">
<span class="header-section-number">28.4.2</span> <span class="math inline">\(R^2\)</span> and Adjusted <span class="math inline">\(R^2\)</span>
</h3>
<p>We learn in SLR that <span class="math inline">\(R^2 = \frac{SS_R}{SS_T} = 1 - \frac{SS_{res}}{SS_T}\)</span>. The <span class="math inline">\(R^2\)</span> statistic can also be calculated and used in MLR. The size of <span class="math inline">\(R^2\)</span> assesses how well the regression model fits the data—the larger the <span class="math inline">\(R^2\)</span>, the better the fit. Specifically, <span class="math inline">\(R^2\)</span> measures the proportion of variability in <span class="math inline">\(Y\)</span> that is explained by the regression model or the <span class="math inline">\(k\)</span> predictors. It’s important to note that adding an additional predictor to the model <em>always increases <span class="math inline">\(R^2\)</span></em>. This happens because the model with <span class="math inline">\(k+1\)</span> predictors will have <span class="math inline">\(SS_R\)</span> that is greater than or at least equal to the <span class="math inline">\(SS_R\)</span> of the model with only <span class="math inline">\(k\)</span> predictors, provided that the <span class="math inline">\(k\)</span> predictors are included among the <span class="math inline">\(k+1\)</span> predictors in the larger model.</p>
<p>The model with one additional predictor <strong>always gets a higher <span class="math inline">\(R^2\)</span></strong> even the new predictor has no explanatory power or useless in predicting <span class="math inline">\(y\)</span>. This happens because the additional predictor may capture random noise in the data, leading to a decrease in <span class="math inline">\(SS_{res}\)</span>. If we rely solely on <span class="math inline">\(R^2\)</span> to compare models that include various predictors, we might always end up selecting the full model with all possible predictors, even if many of them contribute little or nothing to the actual fitting or prediction.</p>
<p>While this approach might yield a model that fits the current data very well, it poses significant risks if our goal is to predict new, unseen future data. Including too many variables in the regression model can lead to <strong>overfitting</strong>—a situation where the model fits the sample data exceptionally well but performs poorly when predicting the mean response or new response values for a different dataset. Overfitting results in a model that captures noise and idiosyncrasies of the sample data, rather than the underlying patterns, making it less generalizable and less reliable for future predictions.</p>
<p>A complex or a larger model has several other disadvantages. First, it’s more difficult to interpret your model and results. It reduces the interpretability. Second, the computing or running time is usually longer, and sometimes much longer depending on the order of complexity. Also, the data or the model itself may consume lots of memory spaces.</p>
<!-- - If we use $R^2$ as the measure of model fit, then we will tend to include lots of regressors in the model, and we will always choose the model that has the most predictors, even though lots of predictors have no or little contribution to the fitting or prediction. -->
<!-- - The idea is a little bit like overfitting in machine learning. -->
<blockquote class="blockquote">
<p><strong>Occam’s Razor: Don’t use a complex model if a simpler model can perform equally well!</strong></p>
</blockquote>
<p>There are other criterion or metrics for accessing model adequacy or model fit that may be better than <span class="math inline">\(R^2\)</span>, for example, <strong>adjusted <span class="math inline">\(R^2\)</span></strong>, <span class="math inline">\(R^2_{adj}\)</span>.</p>
<p><span class="math display">\[R^2_{adj} = 1 - \frac{SS_{res}/(n-p)}{SS_T/(n-1)}\]</span></p>
<p><span class="math inline">\(R^2_{adj}\)</span> applies a penalty (through <span class="math inline">\(p\)</span>) for number of variables included in the model. It is not the more the better anymore. Adjusted <span class="math inline">\(R^2\)</span> doesn’t increase if the new variable provide very little information for prediction. Adjusted <span class="math inline">\(R^2\)</span> will only increase on adding a variable to the model if the addition of the regressor reduces <span class="math inline">\(MS_{res}\)</span>. The new added variable must show that it can contribute to explaining the variation of <span class="math inline">\(y\)</span> sufficiently large, so that its contribution is bigger than the price we pay for hiring this guy. This makes adjusted <span class="math inline">\(R^2\)</span> a preferable metric for model selection in multiple regression models.</p>
<!-- ::: notes -->
<!-- - Adjusted $R^2$ will only increase on adding a variable to the model if the addition of the regressor reduces $MS_{res}$ -->
<!-- ::: -->
<!-- ## Adjusted $R^2$ Example -->
<ul>
<li><p>For a model with 3 predictors, <span class="math inline">\(SS_{res} = 90\)</span>, <span class="math inline">\(SS_T = 245\)</span>, and <span class="math inline">\(n = 15\)</span>. <span class="math display">\[R^2_{adj} = 1 - \frac{90/(15-4)}{245/(15-1)} = 0.53\]</span></p></li>
<li><p>The 4-th regressor is added into the model, and <span class="math inline">\(SS_{res} = 88\)</span> (always decreases). Then <span class="math display">\[R^2_{adj} = 1 - \frac{88/(15-5)}{245/(15-1)} = 0.49\]</span></p></li>
</ul>
<p>The new added regressor should have explanatory power for <span class="math inline">\(y\)</span> large enough, so that <span class="math inline">\(MS_{res}\)</span> is decreased. In this case, adding the 4th regressor does not decrease <span class="math inline">\(SS_{res}\)</span> enough to convince us to put it in the model.</p>
<!-- ## [R Lab]{.pink} $R^2$ and Adjusted $R^2$ -->
<hr>
<p><span style="color:blue"> <strong>Example: <span class="math inline">\(R^2\)</span> and Adjusted <span class="math inline">\(R^2\)</span></strong> </span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-12-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-1" role="tab" aria-controls="tabset-12-1" aria-selected="true">R</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-12-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-12-2" role="tab" aria-controls="tabset-12-2" aria-selected="false">Python</a></li>
</ul>
<div class="tab-content">
<div id="tabset-12-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-12-1-tab">
<p>To get <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span> in R, we check the summary output. They can also be extracted from the summary list.</p>
<div class="cell" data-layout-align="center" data-output.lines="[16,17,18]">
<div class="sourceCode" id="cb75"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">summ_delivery</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>...

Residual standard error: 3.26 on 22 degrees of freedom
Multiple R-squared:  0.96,  Adjusted R-squared:  0.956 
...</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb77"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">summ_delivery</span><span class="op">$</span><span class="va">r.squared</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.96</code></pre>
</div>
<div class="sourceCode" id="cb79"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">summ_delivery</span><span class="op">$</span><span class="va">adj.r.squared</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.956</code></pre>
</div>
</div>
</div>
<div id="tabset-12-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-12-2-tab">
<p>To get <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span> in Python, we check the summary output which is shown at the topright corner. They can also be extracted from the fitted object.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>delivery_ols.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>OLS Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>time</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.960</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>OLS</td>
<td data-quarto-table-cell-role="th">Adj. R-squared:</td>
<td>0.956</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>Least Squares</td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>261.2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Tue, 15 Oct 2024</td>
<td data-quarto-table-cell-role="th">Prob (F-statistic):</td>
<td>4.69e-16</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>10:36:46</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-63.415</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>25</td>
<td data-quarto-table-cell-role="th">AIC:</td>
<td>132.8</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>22</td>
<td data-quarto-table-cell-role="th">BIC:</td>
<td>136.5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>2</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true"><tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intercept</td>
<td>2.3412</td>
<td>1.097</td>
<td>2.135</td>
<td>0.044</td>
<td>0.067</td>
<td>4.616</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">cases</td>
<td>1.6159</td>
<td>0.171</td>
<td>9.464</td>
<td>0.000</td>
<td>1.262</td>
<td>1.970</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">distance</td>
<td>0.0144</td>
<td>0.004</td>
<td>3.981</td>
<td>0.001</td>
<td>0.007</td>
<td>0.022</td>
</tr>
</tbody></table>
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true"><tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Omnibus:</td>
<td>0.421</td>
<td data-quarto-table-cell-role="th">Durbin-Watson:</td>
<td>1.170</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Omnibus):</td>
<td>0.810</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>0.010</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Skew:</td>
<td>0.032</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.995</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>3.073</td>
<td data-quarto-table-cell-role="th">Cond. No.</td>
<td>873.</td>
</tr>
</tbody></table>
<br><br>Notes:<br>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>delivery_ols.rsquared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.9595937494832257</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>delivery_ols.rsquared_adj</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.9559204539817008</code></pre>
</div>
</div>
</div>
</div>
</div>
</section><section id="tests-on-individual-regression-coefficients" class="level3" data-number="28.4.3"><h3 data-number="28.4.3" class="anchored" data-anchor-id="tests-on-individual-regression-coefficients">
<span class="header-section-number">28.4.3</span> Tests on Individual Regression Coefficients</h3>
<p>This is the hypothesis test on any <strong>single</strong> regression coefficient:</p>
<p><span style="color:blue"> <span class="math inline">\(H_0: \beta_{j} = 0 \quad H_1: \beta_j \ne 0\)</span> </span></p>
<p>It is a <span class="math inline">\(t\)</span> test with the test statistic <span class="math inline">\(t_{test} = \frac{b_j}{se(b_j)}\)</span>. We reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(|t_{test}| &gt; t_{\alpha/2, n-k-1}\)</span>. This is a <strong>partial</strong> or <strong>marginal test</strong>: a test of the <strong>contribution of <span class="math inline">\(X_j\)</span> given ALL other regressors in the model</strong>.</p>
<p>We can also do a one-side test for sure. But I am not sure if there is a R function to do a one-sided test. But we can always compute the test statistic or the p-value ourselves.</p>
<!-- ## [R Lab]{.pink} Tests on Individual Coefficients -->
<hr>
<p><span style="color:blue"> <strong>Example: Tests on Individual Coefficients</strong> </span></p>
<p>Suppose we would like to assess the effect of <span class="math inline">\(x_2\)</span> (distance) given that <span class="math inline">\(x_1\)</span> (cases) is in the model.</p>
<p><span style="color:blue"> <span class="math inline">\(H_0: \beta_{2} = 0 \quad H_1: \beta_2 \ne 0\)</span> </span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-13-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-13-1" role="tab" aria-controls="tabset-13-1" aria-selected="true">R</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-13-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-13-2" role="tab" aria-controls="tabset-13-2" aria-selected="false">Python</a></li>
</ul>
<div class="tab-content">
<div id="tabset-13-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-13-1-tab">
<p>The marginal test results are shown in the summary of fitted result. The t test statistic value is 3.98, and p-value is close to zero, concluding that <span class="math inline">\(\beta_2 \ne 0\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb86"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">summ_delivery</span><span class="op">$</span><span class="va">coefficients</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)   2.3412    1.09673    2.13 4.42e-02
cases         1.6159    0.17073    9.46 3.25e-09
distance      0.0144    0.00361    3.98 6.31e-04</code></pre>
</div>
</div>
</div>
<div id="tabset-13-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-13-2-tab">
<p>The marginal test results are shown in the summary of fitted result. The t test statistic value is 3.98, and p-value is close to zero, concluding that <span class="math inline">\(\beta_2 \ne 0\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>delivery_ols.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>OLS Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>time</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.960</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>OLS</td>
<td data-quarto-table-cell-role="th">Adj. R-squared:</td>
<td>0.956</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>Least Squares</td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>261.2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Tue, 15 Oct 2024</td>
<td data-quarto-table-cell-role="th">Prob (F-statistic):</td>
<td>4.69e-16</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>10:36:46</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-63.415</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>25</td>
<td data-quarto-table-cell-role="th">AIC:</td>
<td>132.8</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>22</td>
<td data-quarto-table-cell-role="th">BIC:</td>
<td>136.5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>2</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true"><tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intercept</td>
<td>2.3412</td>
<td>1.097</td>
<td>2.135</td>
<td>0.044</td>
<td>0.067</td>
<td>4.616</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">cases</td>
<td>1.6159</td>
<td>0.171</td>
<td>9.464</td>
<td>0.000</td>
<td>1.262</td>
<td>1.970</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">distance</td>
<td>0.0144</td>
<td>0.004</td>
<td>3.981</td>
<td>0.001</td>
<td>0.007</td>
<td>0.022</td>
</tr>
</tbody></table>
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true"><tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Omnibus:</td>
<td>0.421</td>
<td data-quarto-table-cell-role="th">Durbin-Watson:</td>
<td>1.170</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Omnibus):</td>
<td>0.810</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>0.010</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Skew:</td>
<td>0.032</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.995</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>3.073</td>
<td data-quarto-table-cell-role="th">Cond. No.</td>
<td>873.</td>
</tr>
</tbody></table>
<br><br>Notes:<br>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
</div>
</div>
<p>Each piece of information can be obtained from the fiited object.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>delivery_ols.params</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Intercept    2.341231
cases        1.615907
distance     0.014385
dtype: float64</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>delivery_ols.bse</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Intercept    1.096730
cases        0.170735
distance     0.003613
dtype: float64</code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>delivery_ols.tvalues</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Intercept    2.134738
cases        9.464421
distance     3.981313
dtype: float64</code></pre>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>delivery_ols.pvalues</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Intercept    4.417012e-02
cases        3.254932e-09
distance     6.312469e-04
dtype: float64</code></pre>
</div>
</div>
</div>
</div>
</div>
<!-- :::  notes -->
<!-- ::: -->
</section></section><section id="inference-pitfalls" class="level2" data-number="28.5"><h2 data-number="28.5" class="anchored" data-anchor-id="inference-pitfalls">
<span class="header-section-number">28.5</span> Inference Pitfalls</h2>
<div class="danger">
<ul>
<li>The test <span class="math inline">\(H_0:\beta_j = 0\)</span> will always be rejected as long as the sample size is large enough, even <span class="math inline">\(x_j\)</span> has a very small effect on <span class="math inline">\(y\)</span>.
<ul>
<li>Consider the <strong>practical significance</strong> of the result, not just the statistical significance.</li>
<li>Use the confidence interval to draw conclusions instead of relying only p-values.</li>
</ul>
</li>
</ul>
</div>
<div class="danger">
<ul>
<li>If the sample size is small, there may not be enough evidence to reject <span class="math inline">\(H_0:\beta_j = 0\)</span>.
<ul>
<li>DON’T immediately conclude that the variable has no association with the response.</li>
<li>There may be a linear association that is just not strong enough to detect given your data, or there may be a non-linear association.</li>
</ul>
</li>
</ul>
</div>
<!-- ### Extrapolation {visibility="hidden"} -->
<ul>
<li>In MLR, it’s easy to inadvertently extrapolate since the regressors jointly define the region containing the data. We can define the smallest convex set containing all of the original <span class="math inline">\(n\)</span> regressor points, as the regressor variable hull. Any point outside the hull can be viewed as an extrapolate point. A point within the ranges of <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> may not be necessarily a interpolation point, as shown the blue point in the figure.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-mlr_files/figure-html/unnamed-chunk-64-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<!-- ::: notes -->
<!-- # ```{r} -->
<!-- # with(delivery_data, -->
<!-- #      car::dataEllipse(cases, distance, -->
<!-- #         levels = c(0.5, 0.75, 0.9, 0.95))) -->
<!-- #  -->
<!-- # ``` -->
<!-- ::: -->


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/chenghanyu-introstatsbook\.netlify\.app\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./model-reg.html" class="pagination-link" aria-label="Simple Linear Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./model-logistic.html" class="pagination-link" aria-label="Logistic Regression">
        <span class="nav-page-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Logistic Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2024, Dr.&nbsp;Cheng-Han Yu</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/chenghanyustats/introstatsbook/edit/main/model-mlr.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/chenghanyustats/introstatsbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
<li class="nav-item compact">
    <a class="nav-link" href="https://github.com/chenghanyustats/introstatsbook">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
</div>
  </div>
</footer>


</body></html>