<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="An introductory statistical data science book for STEM students.">
<title>Introduction to Statistics - 28&nbsp; Logistic Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./model-bayes.html" rel="next">
<link href="./model-mlr.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="custom.css">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./model.html">Statistical Models</a></li><li class="breadcrumb-item"><a href="./model-logistic.html"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Logistic Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Statistics</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/chenghanyustats/introstatsbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Introduction-to-Statistics.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistics and Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Science of Data and Data Science</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Collection and Data Type</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Tool foR Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./datasummary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summarizing Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-graphics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-numerics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Numerical Measures of Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-define.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Definition of Probability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-rule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability Rules and Bayes Formula</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-rv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-disc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Discrete Probability Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-cont.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Continuous Probability Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Random Sampling and Sampling Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-llnclt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Law of Large Numbers and Central Limit Theorem</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./infer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-ci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Point and Interval Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-bt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Bootstrapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-ht.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-twomean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Comparing Two Population Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-var.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Inference About Variances</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference About Proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-cat.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference about Categorical Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-p.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">The Issues of <span class="math inline">\(p\)</span>-value and Statistical Significance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Bayesian Thinking and Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-nonpar.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Nonparametric Tests</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-multicomp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Multiple Comparison*</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-twoway.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Two-Way ANOVA*</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-reg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Multiple Linear Regression*</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-logistic.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Bayesian Linear Regression*</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Survival Analysis</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">References</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a-r_prog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">R programming</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a-py_prog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Python Programming</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#regression-vs.-classification" id="toc-regression-vs.-classification" class="nav-link active" data-scroll-target="#regression-vs.-classification"><span class="header-section-number">28.1</span> Regression vs.&nbsp;Classification</a></li>
  <li><a href="#introduction-to-logistic-regression" id="toc-introduction-to-logistic-regression" class="nav-link" data-scroll-target="#introduction-to-logistic-regression"><span class="header-section-number">28.2</span> Introduction to Logistic Regression</a></li>
  <li><a href="#simple-logistic-regression-model" id="toc-simple-logistic-regression-model" class="nav-link" data-scroll-target="#simple-logistic-regression-model"><span class="header-section-number">28.3</span> Simple Logistic Regression Model</a></li>
  <li><a href="#logistic-regression-in-r" id="toc-logistic-regression-in-r" class="nav-link" data-scroll-target="#logistic-regression-in-r"><span class="header-section-number">28.4</span> Logistic Regression in R</a></li>
  <li><a href="#evaluation-metrics" id="toc-evaluation-metrics" class="nav-link" data-scroll-target="#evaluation-metrics"><span class="header-section-number">28.5</span> Evaluation Metrics</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">28.6</span> Exercises</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/chenghanyustats/introstatsbook/edit/main/model-logistic.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/chenghanyustats/introstatsbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./model.html">Statistical Models</a></li><li class="breadcrumb-item"><a href="./model-logistic.html"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Logistic Regression</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-model-logistic" class="quarto-section-identifier"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Logistic Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>We already finished the discussion of linear regression. There are a lot of different regression models and regression problems that can be discussed. If you want to learn more about regression, take regression analysis or machine learning courses. In this chapter, we will be switching to the topic of classification which is another huge and popular topic. Specifically, we talk about <strong>logistic regression</strong>. There are many other classification methods out there, for example K-nearest neighbors, generalized additive models, trees, random forests, boosting, support vector machines, etc. Each method has it own advantages and disadvantages, and no one method dominates all. If you are interested in classification and want to learn more about classification methods, take a statistical machine learning course.</p>
<section id="regression-vs.-classification" class="level2" data-number="28.1"><h2 data-number="28.1" class="anchored" data-anchor-id="regression-vs.-classification">
<span class="header-section-number">28.1</span> Regression vs.&nbsp;Classification</h2>
<p>Linear regression assumes that the response <span class="math inline">\(Y\)</span> is <em>numerical</em> (quantitative). In many situations, however, the response we would like to infer or predict on is <strong>categorical</strong> (qualitative), eye color, car brand, true vs.&nbsp;fake news for example.</p>
<p>A process of predicting categorical response is known as <strong>classification</strong>. There are many classification tools, or <strong>classifiers</strong> used to predict a categorical response. For instance, logistic regression is a classifier.</p>
<div class="columns">
<div class="column" style="width:49%;">
<p><strong>Normal vs.&nbsp;COVID vs.&nbsp;Smoker’s Lungs</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/img-model/covid_lung.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:2%;">

</div><div class="column" style="width:49%;">
<p><strong>Fake vs.&nbsp;Fact</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/img-model/fake_news.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<hr>
<p><span style="color:blue"> <strong>Regression Function <span class="math inline">\(f(x)\)</span> vs.&nbsp;Classifier <span class="math inline">\(C(x)\)</span></strong> </span></p>
<p>Like regression, we have our predictor inputs <span class="math inline">\(X_1, \dots, X_p\)</span>, through a classifier <span class="math inline">\(C(x)\)</span> that takes all the predictors and then generate a predicted value of <span class="math inline">\(y\)</span>, which is categorical. For example, we collect a person’s nationality, race, hair color, build a classifier, then predict his eye color.</p>
<p>Here, the classifier <span class="math inline">\(C(x)\)</span> in classification problem is analogous to the regression function <span class="math inline">\(f(x) = \beta_0 + \beta_1X_1 + \cdots + \beta_pX_p\)</span> in the regression problem. The classifier <span class="math inline">\(C(x)\)</span> is used to predict a categorical variable <span class="math inline">\(y\)</span> and regression function <span class="math inline">\(f(x)\)</span> is used to predict the value of a numerical variable <span class="math inline">\(y\)</span>.</p>
<p>In machine learning, it usually separates regression and classification apart, one for numerical response, the other for categorical response. But the term regression in general means any relationship between response variables and predictors, including both numerical and categorical responses. So the definition of regression in machine learning is a little bit narrow scoped. A regression model in general can deal with either numerical response or the regression problem in machine learning, or categorical response or the classification problem. That’s why we can use a logistic <em>regression</em> to do <em>classification</em> problems.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="./images/img-model/regression.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-classification-regression" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-classification-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/img-model/classification.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-classification-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;28.1: Difference between classification and regression (https://daviddalpiaz.github.io/r4sl/classification-overview.html)
</figcaption></figure>
</div>
</div>
</div>
<hr>
<p><span style="color:blue"> <strong>Classification Example</strong> </span></p>
<ul>
<li>Predict whether people will default on their credit card payment, where <span class="math inline">\((Y)\)</span> is <code>yes</code> or <code>no</code>, based on their monthly credit card balance, <span class="math inline">\((X)\)</span>.</li>
<li>We use the sample data <span class="math inline">\(\{(x_1, y_1), \dots, (x_n, y_n)\}\)</span> to build a classifier.</li>
</ul>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-credit-boxplot" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-credit-boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="model-logistic_files/figure-html/fig-credit-boxplot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-credit-boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;28.2: Boxplot of Default vs.&nbsp;Balance
</figcaption></figure>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/img-model/credit_card.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<hr>
<p><span style="color:blue"> <strong>Why Not Linear Regression?</strong> </span></p>
<p>Before we jump into logistic regression, one question is, why not just fit a linear regression model? That is, we define 0 as not default and 1 as default, and treat 0 and 1 as numerical values, and run a linear regression model, like</p>
<p><span class="math inline">\(Y = \beta_0 + \beta_1X + \epsilon\)</span>, <span class="math inline">\(\, X =\)</span> credit card balance, and</p>
<p><span class="math display">\[Y =\begin{cases}
    0  &amp; \quad \text{if not default}\\
    1  &amp; \quad \text{if default}
     \end{cases}\]</span></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What is the problem with this dummy variable approach?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>In fact, the predicted valued of <span class="math inline">\(Y\)</span>, <span class="math inline">\(\hat{Y} = b_0 + b_1X\)</span>, estimates <span class="math inline">\(P(Y = 1 \mid X) = P(default \mid balance)\)</span> which is actually what we want. So what’s the issue of linear regression? Look at the figure below. You can see that this is not like usual scatter plot when <span class="math inline">\(y\)</span> is numerical, this scatter plot is pretty strange that <span class="math inline">\(y\)</span> is either 0 or 1, the red and green points. This blue line is our linear regression line. Any point on the line is the estimated probability of default given a value of <span class="math inline">\(X\)</span>. Do you see any issues of using linear regression to fit this type of data?</p>
<!-- -  estimates $P(Y = 1 \mid X) = P(default = yes \mid balance)$ -->
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-simple-regression" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-simple-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="model-logistic_files/figure-html/fig-simple-regression-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:72.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simple-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;28.3: Graphical illustration of why a simple linear regression model won’t work for Default ~ Balance
</figcaption></figure>
</div>
</div>
</div>
<!-- - **Some estimates might be outside $[0, 1]$**, which doesn't make sense given that $Y$ is a probability. -->
<p>First, probability is always between 0 and 1, but some estimates here are outside the <span class="math inline">\([0, 1]\)</span> interval. For example, when the credit card balance is below 500, the estimated probability of default is negative, which is not allowed mathematically.</p>
<p>Also, we assume the probability of default is linearly increasing with credit card balance, which is generally not true in reality.</p>
<p>In addition, the dummy variable approach <span class="math inline">\((Y = 0, 1)\)</span> cannot be easily extended to <span class="math inline">\(Y\)</span> with more than two categories. If we have 3 categories with nominal level of measurements, like car brand and eye color, coding the categories with 1, 2, 3 forces them to be ordered, the forces them to have the same difference. It does not make sense.</p>
<p>As a result, we need to use a model that is appropriate for categorical responses, like logistic regression.</p>
<hr>
<p><span style="color:blue"> <strong>Why Logistic Regression?</strong> </span></p>
<p>Some classification methods, logistic regression for example, first predict the <strong>probability</strong> of each category of <span class="math inline">\(Y\)</span>. Then, the logistic regression predicts the probability of <code>default</code> using an <span style="color:blue"><strong>S-shaped</strong> curve</span>.</p>
<p>You can see the estimated probability curve is always between 0 and 1 and higher balance leads to higher chance of default. If our cut-off or threshold probability is 0.5, <span class="math inline">\(y\)</span> will be labeled as default when the balance is over about 2000 dollars. Our goal is to learn how to generate this predicted probability curve using logistic regression.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-logistic-reg" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-logistic-reg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="model-logistic_files/figure-html/fig-logistic-reg-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-logistic-reg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;28.4: Graphical illustration of why a logistic regression model works better for Default ~ Balance
</figcaption></figure>
</div>
</div>
</div>
</section><section id="introduction-to-logistic-regression" class="level2" data-number="28.2"><h2 data-number="28.2" class="anchored" data-anchor-id="introduction-to-logistic-regression">
<span class="header-section-number">28.2</span> Introduction to Logistic Regression</h2>
<p><span style="color:blue"> <strong>Binary Responses</strong> </span></p>
<p>The story starts with the binary response. The idea is that we treat each default <span class="math inline">\((y = 1)\)</span> and not default <span class="math inline">\((y = 0)\)</span>, as success and failure arising from separate <strong>Bernoulli</strong> trials.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What is a Bernoulli trial?
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>A Bernoulli trial is a special case of a binomial trial when the number of trials is <span class="math inline">\(m = 1\)</span>.
<ul>
<li>There are <strong>exactly two</strong> possible outcomes, “success” and “failure”.</li>
<li>The probability of success, <span class="math inline">\(\pi\)</span>, is <strong>constant</strong>.</li>
</ul>
</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In the default credit card example,
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Do we have exactly two outcomes?</li>
<li>Do we have constant probability? <span class="math inline">\(P(y_1 = 1) = P(y_2 = 1) = \cdots = P(y_n = 1) = \pi?\)</span>
</li>
</ul>
</div>
</div>
<p><span style="color:red"> <strong><em>Nonconstant Probability</em></strong></span></p>
<div class="columns">
<div class="column" style="width:49%;">
<ul>
<li><p>Two outcomes: Default <span class="math inline">\((y = 1)\)</span> and Not Default <span class="math inline">\((y = 0)\)</span></p></li>
<li><p>The probability of success, <span class="math inline">\(\pi\)</span>, <em>changes with</em> the value of predictor, <span class="math inline">\(X\)</span>!</p></li>
<li><p>With a different value of <span class="math inline">\(x_i\)</span>, each Bernoulli trial outcome, <span class="math inline">\(y_i\)</span>, has a <em>different</em> probability of success, <span class="math inline">\(\pi_i\)</span>.</p></li>
</ul>
</div><div class="column" style="width:2%;">

</div><div class="column" style="width:49%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="model-logistic_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<p><span class="math display">\[ y_i \mid x_i \stackrel{indep}{\sim} \text{Bernoulli}(\pi(x_i)) = binomial(m=1,\pi = \pi(x_i)) \]</span></p>
<ul>
<li>
<span class="math inline">\(X =\)</span> <code>balance</code>. <span class="math inline">\(x_1 = 2000\)</span> has a larger <span class="math inline">\(\pi_1 = \pi(2000)\)</span> than <span class="math inline">\(\pi_2 = \pi(500)\)</span> with <span class="math inline">\(x_2 = 500\)</span> because credit cards with a higher balance are more likely to default.</li>
</ul>
<p>The idea of nonconstant probability in logistic regression is similar to the idea of different mean response value in linear regression. In linear regression, the mean response level is linearly affected by the predictor’s value, <span class="math inline">\(E(Y \mid X) = \beta_0 + \beta_1X\)</span>. In logistic regression, <span class="math inline">\(\pi(x) = P(Y = 1 \mid X = x)\)</span> is a function of <span class="math inline">\(X\)</span>. In our example, the higher value of <span class="math inline">\(X\)</span>, the higher value of <span class="math inline">\(\pi\)</span>, although their relationship is not linear. The fact that the regressor <span class="math inline">\(X\)</span> affects the mean response level or the probability of the response belonging to some category is the reason why we use regression. Through the relationship between the response and regressors, knowing <span class="math inline">\(X\)</span> better helps us know the value of <span class="math inline">\(Y\)</span>.</p>
<p>Because of this Bernoulli assumption, the logistic regression is also called <strong>binomial</strong> regression.</p>
<hr>
<p><span style="color:blue"> <strong>Logistic Regression</strong> </span></p>
<p>Now it’s time to see what the logistic regression is. <strong>Logistic regression</strong> models a <strong>binary</strong> response <span class="math inline">\((Y)\)</span> using predictors <span class="math inline">\(X_1, \dots, X_k\)</span>.</p>
<ul>
<li>
<span class="math inline">\(k = 1\)</span>: simple logistic regression</li>
<li>
<span class="math inline">\(k &gt; 1\)</span>: multiple logistic regression</li>
</ul>
<p>But remember, we are not predicting <span class="math inline">\(Y\)</span> directly. Instead, our goal is to use predictors <span class="math inline">\(X_1, \dots, X_k\)</span> to estimate the probability of success <span class="math inline">\(\pi\)</span> of the Bernoulli variable <span class="math inline">\(Y\)</span>. And if <span class="math inline">\(\pi &gt; threshold\)</span>, say 0.5, <span class="math inline">\(\hat{Y} = 1\)</span>, if <span class="math inline">\(\pi &lt; threshold\)</span>, <span class="math inline">\(\hat{Y} = 0\)</span>. <strong>But how?</strong></p>
<p>Now that it’s not good to use <span class="math inline">\(y = 0, 1\)</span> in the regression, and predicting a probability having value between 0 and 1 sounds difficult. How about this. we transform <span class="math inline">\(\pi \in (0, 1)\)</span> into another variable say <span class="math inline">\(\eta \in (-\infty, \infty)\)</span> living on the whole real line. So that we can reasonably fit a linear regression on <span class="math inline">\(\eta\)</span> because the linear predictor could be any value.</p>
<p>In the logistic regression, we use the <strong>logit function</strong>:</p>
<p><span style="color:red"> <strong><em><span class="math inline">\(\eta = logit(\pi) = \ln\left(\frac{\pi}{1-\pi}\right)\)</span></em></strong> </span></p>
<p>which is in fact the log odds. This transformation is monotone. The higher <span class="math inline">\(\pi\)</span> is, the larger <span class="math inline">\(\eta\)</span> is. When <span class="math inline">\(\pi\)</span> approaches to zero, <span class="math inline">\(\eta\)</span> approaches to <span class="math inline">\(-\infty\)</span>, and when <span class="math inline">\(\pi\)</span> approaches to 1, <span class="math inline">\(\eta\)</span> approaches to <span class="math inline">\(\infty\)</span>.</p>
<!-- - **Transform $\pi \in (0, 1)$ into another variable $\eta \in (-\infty, \infty)$. Then fit a linear regression on $\eta$.** -->
<!-- - **Logit function:** For $0 < \pi < 1$ -->
<!-- $$\eta = logit(\pi) = \ln\left(\frac{\pi}{1-\pi}\right)$$ -->
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-logit-function" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-logit-function-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="model-logistic_files/figure-html/fig-logit-function-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:72.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-logit-function-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;28.5: Graphical illustration of the logit function
</figcaption></figure>
</div>
</div>
</div>
<p>Then we can assume <span class="math inline">\(\eta\)</span> is a <em>linear</em> function of <span class="math inline">\(x\)</span>:</p>
<p><span class="math display">\[\eta(x) =\ln \left( \frac{\pi(x)}{1 - \pi(x)} \right)= \beta_0 + \beta_1x\]</span> By doing so, we connect <span class="math inline">\(x\)</span> and <span class="math inline">\(\pi\)</span> (and <span class="math inline">\(\eta\)</span>) together, and we can learn how <span class="math inline">\(x\)</span> affect <span class="math inline">\(\pi\)</span> (and <span class="math inline">\(\eta\)</span>) through the coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</p>
<p>Well, the question is, if we obtain the <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> estimates, and therefore obtain <span class="math inline">\(\eta\)</span> estimated value, how do we obtain <span class="math inline">\(\pi(x)\)</span>, our real interest? We can consider transform <span class="math inline">\(\eta\)</span> back to <span class="math inline">\(\pi\)</span> using the inverse function of the logit function, which is the <strong>logistic</strong> function.</p>
<!-- <span style="color:red"> ***Logistic Function $\pi = logistic(\eta) = \frac{\exp(\eta)}{1+\exp(\eta)}$*** </span> -->
<p>So the <em>logit</em> function <span class="math inline">\(\eta = logit(\pi) = \ln\left(\frac{\pi}{1-\pi}\right)\)</span> takes a value <span class="math inline">\(\pi \in (0, 1)\)</span> and maps it to a value <span class="math inline">\(\eta \in (-\infty, \infty)\)</span>. But the logistic function denoted as <span style="color:red"> <span class="math display">\[\pi = logistic(\eta) = \frac{\exp(\eta)}{1+\exp(\eta)} = \frac{1}{1+\exp(-\eta)} \in (0, 1)\]</span> </span> takes a value <span class="math inline">\(\eta \in (-\infty, \infty)\)</span> and maps it to a value <span class="math inline">\(\pi \in (0, 1)\)</span>.</p>
<p>So once <span class="math inline">\(\eta\)</span> is estimated by the linear predictor, we use the logistic function to transform <span class="math inline">\(\eta\)</span> back to the probability. The figure below shows a logistic function. This logistic function is a function of <span class="math inline">\(x\)</span>, and it describes the probability <span class="math inline">\(\pi\)</span>. This S-shaped curve is what we want to estimate given the data, and we use this curve to do classification on <span class="math inline">\(y\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-logistic-function" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-logistic-function-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="model-logistic_files/figure-html/fig-logistic-function-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:72.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-logistic-function-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;28.6: Graphical illustration of the logistic function
</figcaption></figure>
</div>
</div>
</div>
</section><section id="simple-logistic-regression-model" class="level2" data-number="28.3"><h2 data-number="28.3" class="anchored" data-anchor-id="simple-logistic-regression-model">
<span class="header-section-number">28.3</span> Simple Logistic Regression Model</h2>
<p>To sum up, here shows a simple logistic regression model: For <span class="math inline">\(i = 1, \dots, n\)</span> and with one predictor <span class="math inline">\(X\)</span>,</p>
<p><span class="math display">\[(Y_i \mid X = x_i) \stackrel{indep}{\sim} \text{Bernoulli}(\pi(x_i))\]</span> <span class="math display">\[\text{logit}(\pi_i) = \ln \left( \frac{\pi(x_i)}{1 - \pi(x_i)} \right) = \eta_i = \beta_0+\beta_1 x_{i}\]</span></p>
<p>Each <span class="math inline">\(Y_i\)</span> is a Bernoulli variable with the probability of success <span class="math inline">\(\pi_i(x_i)\)</span> which depends on its corresponding regressor <span class="math inline">\(x_i\)</span> value. The nonlinear relationship between <span class="math inline">\(\pi_i(x_i)\)</span> and <span class="math inline">\(x_i\)</span> is described through a linear relationship on its logit transformation. Put it another way, we have <span class="math display">\[\small \pi_i = \frac{\exp(\beta_0+\beta_1 x_{i})}{1+\exp(\beta_0+\beta_1 x_{i})} = \frac{\exp(\eta_i)}{1 + \exp(\eta_i)}\]</span></p>
<p>Once we get the estimates <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span>, we can simply plug them into the logistic function to get the estimated probability <span class="math inline">\(\hat{\pi}_i\)</span>.</p>
<p><span class="math display">\[\small \hat{\pi}_i = \frac{\exp(\hat{\beta}_0+\hat{\beta}_1 x_{i} )}{1+\exp(\hat{\beta}_0+\hat{\beta}_1 x_{i})}\]</span> If we consider a sequence of possible values of <span class="math inline">\(x_i\)</span>, and their estimated probability <span class="math inline">\(\hat{\pi}_i\)</span>, the collection of <span class="math inline">\(\{ x_i \}\)</span> and <span class="math inline">\(\{ \hat{\pi}_i \}\)</span> will give us the S-shaped probability curve.</p>
<hr>
<p><span style="color:blue"> <strong>Probability Curve</strong> </span></p>
<div class="columns">
<div class="column" style="width:49%;">
<ul>
<li><p>The relationship between <span class="math inline">\(\pi(x)\)</span> and <span class="math inline">\(x\)</span> is not linear! <span class="math display">\[\pi(x) = \frac{\exp(\beta_0+\beta_1 x)}{1+\exp(\beta_0+\beta_1 x)}\]</span></p></li>
<li><p>Because of the S-shaped curve, the amount that <span class="math inline">\(\pi(x)\)</span> changes due to a one-unit change in <span class="math inline">\(x\)</span> depends on the current value of <span class="math inline">\(x\)</span>. <span class="math inline">\(\pi(x = 2000)\)</span> would change much larger than <span class="math inline">\(\pi(x = 1000)\)</span> with one-unit change in <span class="math inline">\(x\)</span>.</p></li>
<li><p>Regardless of the value of <span class="math inline">\(x\)</span>, if <span class="math inline">\(\beta_1 &gt; 0\)</span>, increasing <span class="math inline">\(x\)</span> will increase <span class="math inline">\(\pi(x)\)</span> because the slope of the S-shape curve is positive.</p></li>
</ul>
</div><div class="column" style="width:2%;">

</div><div class="column" style="width:49%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="model-logistic_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<hr>
<p><span style="color:blue"> <strong>Interpretation of Coefficients</strong> </span></p>
<ul>
<li><p>The ratio <span class="math inline">\(\frac{\pi}{1-\pi} \in (0, \infty)\)</span> is called the <strong>odds</strong> of having <span class="math inline">\(y=1\)</span>.</p></li>
<li><p>Example: If 1 in 5 people will default, the odds is 1/4 since <span class="math inline">\(\pi = 0.2\)</span> implies an odds of <span class="math inline">\(0.2/(1−0.2) = 1/4\)</span>.</p></li>
</ul>
<p><span class="math display">\[\ln \left( \frac{\pi(x)}{1 - \pi(x)} \right)= \beta_0 + \beta_1x\]</span></p>
<ul>
<li>Increasing <span class="math inline">\(x\)</span> by one unit changes the <strong>log-odds</strong> by <span class="math inline">\(\beta_1\)</span>, or it multiplies the odds by <span class="math inline">\(e^{\beta_1}\)</span>.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p><span class="math inline">\(\beta_1\)</span> does <em>not</em> correspond to the change in <span class="math inline">\(\pi(x)\)</span> associated with a one-unit increase in <span class="math inline">\(x\)</span>.</p></li>
<li><p><span class="math inline">\(\beta_1\)</span> is the change in <strong>log odds</strong> associated with one-unit increase in <span class="math inline">\(x\)</span>.</p></li>
</ul>
</div>
</div>
</section><section id="logistic-regression-in-r" class="level2" data-number="28.4"><h2 data-number="28.4" class="anchored" data-anchor-id="logistic-regression-in-r">
<span class="header-section-number">28.4</span> Logistic Regression in R</h2>
<div class="columns">
<div class="column" style="width:49%;">
<p>We use the <code>body</code> data to demonstrate the implementation of logistic regression. The response variable is <code>GENDER</code>, and the predictor is <code>HEIGHT</code>. We would like to use logistic regression to predict whether a person is male or female using the height information of that person.</p>
<p>In the data,</p>
<ul>
<li><p><code>GENDER = 1</code> if male</p></li>
<li><p><code>GENDER = 0</code> if female</p></li>
</ul>
<p>The unit of <code>HEIGHT</code> is centimeter (cm) (1 cm = 0.3937 in).</p>
</div><div class="column" style="width:2%;">

</div><div class="column" style="width:49%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/img-model/height.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">body</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.table</a></span><span class="op">(</span><span class="st">"./data/body.txt"</span>, header <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">body</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  AGE GENDER PULSE SYSTOLIC DIASTOLIC HDL LDL WHITE  RED PLATE WEIGHT HEIGHT
1  43      0    80      100        70  73  68   8.7 4.80   319   98.6  172.0
2  57      1    84      112        70  35 116   4.9 4.73   187   96.9  186.0
3  38      0    94      134        94  36 223   6.9 4.47   297  108.2  154.4
4  80      1    74      126        64  37  83   7.5 4.32   170   73.1  160.5
5  34      1    50      114        68  50 104   6.1 4.95   140   83.1  179.0
6  77      1    60      134        60  55  75   5.7 3.95   192   86.5  166.7
  WAIST ARM_CIRC  BMI
1 120.4     40.7 33.3
2 107.8     37.0 28.0
3 120.3     44.3 45.4
4  97.2     30.3 28.4
5  95.1     34.0 25.9
6 112.0     31.4 31.1</code></pre>
</div>
</div>
<p>Again, we are not using gender to predict someone’s height, which is usually done by linear regression. Instead, our response variable is a binary categorical variable, and we are doing classification with a numeric predictor.</p>
<hr>
<p><span style="color:blue"> <strong>Data Summary</strong> </span></p>
<p>A basic data summary by gender tells us that height plays a role in distinguish male from female, so using height to classify gender would be helpful.</p>
<!-- ::::{.columns} -->
<!-- :::{.column width="49%"} -->
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">body</span><span class="op">$</span><span class="va">GENDER</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
147 153 </code></pre>
</div>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">body</span><span class="op">[</span><span class="va">body</span><span class="op">$</span><span class="va">GENDER</span> <span class="op">==</span> <span class="fl">1</span>, <span class="op">]</span><span class="op">$</span><span class="va">HEIGHT</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  155.0   169.1   173.8   174.1   179.4   193.3 </code></pre>
</div>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">body</span><span class="op">[</span><span class="va">body</span><span class="op">$</span><span class="va">GENDER</span> <span class="op">==</span> <span class="fl">0</span>, <span class="op">]</span><span class="op">$</span><span class="va">HEIGHT</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  134.5   156.5   162.2   161.7   166.8   181.4 </code></pre>
</div>
</div>
<!-- ::: -->
<!-- :::{.column width="2%"} -->
<!-- ::: -->
<!-- :::{.column width="49%"} -->
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">body</span><span class="op">$</span><span class="va">HEIGHT</span> <span class="op">~</span> <span class="va">body</span><span class="op">$</span><span class="va">GENDER</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="model-logistic_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<!-- ::: -->
<!-- :::: -->
<hr>
<p><span style="color:blue"> <strong>Model Fitting</strong> </span></p>
<p>We use the function <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> in R to fit a logistic regression model. “glm” means <strong>g</strong>eneralized <strong>l</strong>inear <strong>m</strong>odel (GLM). Linear regression is a linear model, and it is a normal model because the response variable is normally distributed given <span class="math inline">\(x\)</span>. The models for non-normal response variables generalizes the linear regression model, and hence belong to GLM. The logistic regression whose response is Bernoulli or binomial distributed is a GLM. There are other GLMs such as Poisson regression and gamma regression. They are often discussed in the second course of Linear Models or a separate Generalized Linear Models course.</p>
<p>In the function, we use the same formula syntax as <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>, and one additional job we need to do is specify the family of the GLM. <code>family = "binomial"</code> should be used because the logistic regression is a binomial regression.</p>
<div class="cell" data-highlight.output="[10,11,12]" data-output.lines="-1">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">logit_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">GENDER</span> <span class="op">~</span> <span class="va">HEIGHT</span>, data <span class="op">=</span> <span class="va">body</span>, family <span class="op">=</span> <span class="st">"binomial"</span><span class="op">)</span></span>
<span><span class="op">(</span><span class="va">summ_logit_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">logit_fit</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = GENDER ~ HEIGHT, family = "binomial", data = body)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -40.54809    4.63084  -8.756   &lt;2e-16 ***
HEIGHT        0.24173    0.02758   8.764   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 415.77  on 299  degrees of freedom
Residual deviance: 251.50  on 298  degrees of freedom
AIC: 255.5

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p><br></p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">summ_logit_fit</span><span class="op">$</span><span class="va">coefficients</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate Std. Error   z value     Pr(&gt;|z|)
(Intercept) -40.5480864 4.63083742 -8.756102 2.021182e-18
HEIGHT        0.2417325 0.02758399  8.763507 1.892674e-18</code></pre>
</div>
</div>
<p>Based on the fitted result, we learn that <span class="math display">\[\hat{\eta}(x) = \ln \left( \frac{\hat{\pi}(x)}{1 - \hat{\pi}(x)}\right) = \ln (\text{odds}_{x}) =  \hat{\beta}_0 + \hat{\beta}_1x = -40.55 + 0.24 \times \text{HEIGHT}\]</span></p>
<!-- - $\hat{\eta}(x) = \hat{\beta}_0 + \hat{\beta}_1x$ -->
<p>Since <span class="math inline">\(\hat{\eta}(x+1) = \hat{\beta}_0 + \hat{\beta}_1(x+1)\)</span>, <span class="math inline">\(\hat{\eta}(x+1) - \hat{\eta}(x) = \hat{\beta}_1 = \ln(\text{odds}_{x+1}) - \ln(\text{odds}_{x}) = \ln \left( \frac{\text{odds}_{x+1}}{\text{odds}_{x}} \right)\)</span></p>
<p>A one centimeter increase in <code>HEIGHT</code> increases the <em>log odds</em> of being male by 0.24 units.</p>
<p>The <strong>odds ratio</strong>, <span class="math inline">\(\widehat{OR} = \frac{\text{odds}_{x+1}}{\text{odds}_{x}} = e^{\hat{\beta}_1} = e^{0.24} = 1.273\)</span>. Therefore, the odds of being male increases by 27.3% with an additional one centimeter of <code>HEIGHT</code>.</p>
<hr>
<p><span style="color:blue"> <strong>Prediction</strong> </span></p>
<p>Knowing how the predictor affects the chance of response belonging to some category is one goal. But in classification, we usually focus more on prediction. For example, we may want to know <em>Pr(GENDER = 1) when <code>HEIGHT</code> is 170 cm</em>.</p>
<!-- <span style="color:red"> ***Pr(GENDER = 1) When HEIGHT is 170 cm*** </span> -->
<!-- $$\log\left(\frac{\hat{\pi}}{1-\hat{\pi}}\right) = -40.55+0.24 \times 170$$ -->
<p>Once we obtain the coefficient estimates and the predictor value, we just need to plug them into the logistic function to obtain the probability we want.</p>
<p><span class="math display">\[ \hat{\pi}(x = 170) = \frac{\exp(\hat{\beta}_0+\hat{\beta}_1 x)}{1+\exp(\hat{\beta}_0+\hat{\beta}_1 x)} = \frac{\exp(-40.55+0.24 \times 170)}{1+\exp(-40.55+0.24 \times 170)} = 0.633 = 63.3\%\]</span></p>
<p>Through the formula, we learn that from our model, when a person is 170cm tall, the probability that this person is male is about 63/3%.</p>
<p><code>predict(logit_fit, type = "response")</code> gives us a vector of <span class="math inline">\(\hat{\pi}(x_i)\)</span> of all responses in the data. When <code>type = "link"</code>, <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> gives us <span class="math inline">\(\hat{\eta}(x_i)\)</span> because in literature, <span class="math inline">\(\eta(x) = \ln \left( \frac{\hat{\pi}(x)}{1 - \hat{\pi}(x)}\right)\)</span> is called the <strong>link function</strong>. To predict a specific probability at some <span class="math inline">\(x\)</span> value, we use <code>newdata = data.frame(HEIGHT = 170)</code>. Remember the variable name should be exactly the same as the name in the original data set.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pi_hat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">logit_fit</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></span>
<span><span class="va">eta_hat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">logit_fit</span>, type <span class="op">=</span> <span class="st">"link"</span><span class="op">)</span>  <span class="co">## default gives us b0 + b1*x</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">logit_fit</span>, newdata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>HEIGHT <span class="op">=</span> <span class="fl">170</span><span class="op">)</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1 
0.6333105 </code></pre>
</div>
</div>
<p><span style="color:red"> <strong><em>Probability Curve</em></strong> </span></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What is the probability of being male when the <code>HEIGHT</code> is 160 cm? What about when the <code>HEIGHT</code>is 180 cm?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">logit_fit</span>, newdata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>HEIGHT <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">160</span>, <span class="fl">170</span>, <span class="fl">180</span><span class="op">)</span><span class="op">)</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3 
0.1334399 0.6333105 0.9509103 </code></pre>
</div>
</div>
<p>The blue S-shaped curve is the estimated probability curve. It can be plotted using <code>pi_hat</code>.</p>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="model-logistic_files/figure-html/default-predict-viz-1.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<ul>
<li><strong><span style="color:pink"> 160 cm, Pr(male) = 0.13</span></strong></li>
<li><strong><span style="color:gold"> 170 cm, Pr(male) = 0.63</span></strong></li>
<li><strong><span style="color:green"> 180 cm, Pr(male) = 0.95</span></strong></li>
</ul>
</div>
</div>
</section><section id="evaluation-metrics" class="level2" data-number="28.5"><h2 data-number="28.5" class="anchored" data-anchor-id="evaluation-metrics">
<span class="header-section-number">28.5</span> Evaluation Metrics</h2>
<!-- <span style="color:blue"> **Sensitivity and Specificity** </span> -->
<p>Having probabilities is just a intermediate step. Most of the time our final goal is to classify our response, doing a binary decision. Given a predicted probability, we may correctly classify the label, or mis-classify the label. To know whether or not our model does a good job on classification, we need some evaluation metrics.</p>
<p>First, we can use a tool called a <strong>confusion matrix</strong> to display all possible outcomes in a binary classification scenario. In this context, let’s designate 0 as Negative and 1 as Positive, regardless of what these values represent. If the actual truth is 0 and we classify the response as 0, this outcome is a True Negative (TN), meaning we made a correct decision. However, if we classify the response as 1 instead, we commit an error, resulting in a False Positive (FP). In this case, the true condition is Negative, but our model incorrectly predicts it as Positive.</p>
<p>Similarly, if the truth is 1 and we correctly predict it as 1, the classification is accurate and is called a True Positive (TP). However, if we incorrectly label a response as Negative when it is actually Positive, we make a False Negative (FN).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead><tr class="header">
<th></th>
<th>0</th>
<th>1</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Labeled 0</strong></td>
<td><strong>True Negative (TN)</strong></td>
<td><strong>False Negative (FN)</strong></td>
</tr>
<tr class="even">
<td><strong>Labeled 1</strong></td>
<td><strong>False Positive (FP)</strong></td>
<td><strong>True Positive (TP)</strong></td>
</tr>
</tbody>
</table>
<p>A good classifier accurately identifies a high number of TNs and TPs while minimizing FNs and FPs. Commonly used performance measures include Sensitivity (True Positive Rate), Specificity (True Negative Rate), and Accuracy.</p>
<ul>
<li><p><strong>Sensitivity (True Positive Rate, TPR)</strong> <span class="math inline">\(= P( \text{Labeled 1} \mid \text{1}) = \frac{TP}{TP+FN}\)</span> measures the classifier’s ability to correctly identify positive cases or make correct discoveries when the actual responses are truly Positive. It reflects how well the model detects actual positives.</p></li>
<li><p><strong>Specificity (True Negative Rate, TNR)</strong> <span class="math inline">\(= P( \text{Labeled 0} \mid \text{0}) = \frac{TN}{FP+TN}\)</span> measures the percentage of correctly labeled negatives among the actual negative responses. It indicates how effectively the model avoids false alarms by accurately identifying negatives.</p></li>
<li><p><strong>Accuracy</strong> <span class="math inline">\(= \frac{TP + TN}{TP+FN+FP+TN}\)</span> considers both negatives and positives, measuring the overall proportion of correct classifications across the entire dataset. It provides a general assessment of the classifier’s performance by accounting for the total number of correct predictions out of all predictions made. <!-- - **F1 score** $= \frac{2TP}{2TP+FP+FN}$ --></p></li>
<li><p>More on <a href="https://en.wikipedia.org/wiki/Sensitivity_and_specificity">Wiki page</a></p></li>
</ul>
<hr>
<p><span style="color:blue"> <strong>Example: Confusion Matrix</strong> </span></p>
<p>To produce a confusion matrix, we need two things: the true response labels, and the classification from the model. In the example, the true labels are just <code>body$GENDER</code> data. For the classification result, we need to make a binary decision from the estimated probabilities obtained from the model. Here we use 0.5 as the threshold. If <span class="math inline">\(\hat{\pi}(x) &gt; 0.5\)</span>, then we label the response as 1, and 0 otherwise. We then can simply use <code><a href="https://rdrr.io/r/base/table.html">table()</a></code> function to generate a confusion matrix.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prob</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">logit_fit</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></span>
<span></span>
<span><span class="co">## true observations</span></span>
<span><span class="va">gender_true</span> <span class="op">&lt;-</span> <span class="va">body</span><span class="op">$</span><span class="va">GENDER</span></span>
<span></span>
<span><span class="co">## predicted labels</span></span>
<span><span class="va">gender_predict</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">prob</span> <span class="op">&gt;</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">*</span> <span class="fl">1</span></span>
<span></span>
<span><span class="co">## confusion matrix</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">gender_predict</span>, <span class="va">gender_true</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              gender_true
gender_predict   0   1
             0 118  29
             1  29 124</code></pre>
</div>
</div>
<p>The true positive rate is 124/(124+29) = 0.81, and the true negative rate is 118/(118+29) = 0.803. The overall accuracy is (124 + 118) /(124 + 29 + 29 + 118) = 0.807. <!-- -------------------------------------------------------------------- --></p>
<!-- <span style="color:blue"> **Receiver Operating Characteristic (ROC) Curve** </span> -->
<p>A commonly used visualization tool for assessing the classification performance is the <strong>receiver operating characteristic (ROC) curve</strong>. <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> This curve plots True Positive Rate (Sensitivity) vs.&nbsp;False Positive Rate (1 - Specificity). The confusion matrix provides the classification result for a single threshold, typically 0.5 in many cases. However, by adjusting the threshold, we can obtain different classification outcomes. For example, if <span class="math inline">\(\hat{\pi}(x) = 0.57\)</span>, and the cutoff is set at 0.5, <span class="math inline">\(\hat{y} = 1\)</span> (Positive). However, if we increase the cutoff to 0.6, <span class="math inline">\(\hat{y} = 0\)</span> (Negative). The ROC curve helps visualize how the classifier’s performance changes across various thresholds, allowing us to evaluate its overall effectiveness.</p>
<p>The ROC curve effectively illustrates how sensitivity and specificity change across every possible cutoff value between 0 and 1. When the cutoff is small, it becomes more likely that <span class="math inline">\(\hat{\pi}(x) &gt; cutoff\)</span>, resulting in more Positives and fewer Negatives. As a result, sensitivity increases (TP <span class="math inline">\(\uparrow\)</span> and FN <span class="math inline">\(\downarrow\)</span>) while specificity decreases (TN <span class="math inline">\(\downarrow\)</span> and FP <span class="math inline">\(\uparrow\)</span>), causing 1 - specificity to rise. Conversely, when the cutoff is large, it is more likely that <span class="math inline">\(\hat{\pi}(x) &lt; cutoff\)</span>, resulting in fewer Positives and more Negatives. This leads to a decrease in sensitivity (TP <span class="math inline">\(\downarrow\)</span> and FN <span class="math inline">\(\uparrow\)</span>) and an increase in specificity (TN <span class="math inline">\(\uparrow\)</span> and FP <span class="math inline">\(\downarrow\)</span>), so 1 - specificity is lower.</p>
<p>This dynamic explains why the two endpoints of the ROC curve are positioned at the top-right and bottom-left corners of the graph. The top-right corner represents a scenario with high sensitivity and low specificity (low cutoff), while the bottom-left corner represents high specificity and low sensitivity (high cutoff).</p>
<p>The ideal classification result occurs when TPR is 1 and FPR is 0, corresponding to the top-left point of the ROC plot. A superior ROC curve would closely resemble a right-angle shape (red-dashed), with the “knee” of the curve near this perfect point. Building on this concept, a commonly used performance measure derived from the ROC curve is the <strong>Area Under the Curve</strong> (AUC). The AUC quantifies the overall ability of the model to distinguish between classes. The larger the AUC, the better the classification performance, with a value of 1 representing perfect classification and a value of 0.5 indicating no better than random chance (black-dashed).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-roc-curve" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-roc-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="model-logistic_files/figure-html/fig-roc-curve-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-roc-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;28.7: ROC curve for Gender ~ Height
</figcaption></figure>
</div>
</div>
</div>
</section><section id="exercises" class="level2" data-number="28.6"><h2 data-number="28.6" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">28.6</span> Exercises</h2>
<ol type="1">
<li>The following logistic regression equation is used for predicting whether a bear is male or female. The value of <span class="math inline">\(\pi\)</span> is the probability that the bear is male. <span class="math display">\[\log\left(\frac{\pi}{1-\pi}\right) = 2.3 - 0.0573 (\text{Length}) + 0.00842(\text{Weight})\]</span>
<ol type="a">
<li>Identify the predictor and response variables. Which of these are dummy variables?</li>
<li>Given that the variable <code>Length</code>is in the model, does a heavier weight increase or decrease the probability that the bear is a male? Please explain.</li>
<li>The given regression equation has an overall p-value of 0.218. What does that suggest about the quality of predictions made using the regression equation?</li>
<li>Use a length of 60 in. and a weight of 300 lb to find the probability that the bear is a male. Also, what is the probability that the bear is a female?</li>
</ol>
</li>
</ol>


</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>R packages for ROC curves: <a href="http://ipa-tys.github.io/ROCR/">ROCR</a> and <a href="https://web.expasy.org/pROC/">pROC</a>, <a href="https://yardstick.tidymodels.org/">yardstick of Tidymodels</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/chenghanyu-introstatsbook\.netlify\.app\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./model-mlr.html" class="pagination-link" aria-label="Multiple Linear Regression*">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Multiple Linear Regression*</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./model-bayes.html" class="pagination-link" aria-label="Bayesian Linear Regression*">
        <span class="nav-page-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Bayesian Linear Regression*</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2024, Dr.&nbsp;Cheng-Han Yu</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/chenghanyustats/introstatsbook/edit/main/model-logistic.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/chenghanyustats/introstatsbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
<li class="nav-item compact">
    <a class="nav-link active" href="https://github.com/chenghanyustats/introstatsbook" aria-current="page">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
</div>
  </div>
</footer>


</body></html>