<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="An comprehensive introductory statistical data science book.">
<title>Introduction to Statistics - 11&nbsp; Sampling Distribution</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./prob-llnclt.html" rel="next">
<link href="./prob-cont.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Sampling Distribution</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Statistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/chenghanyustats/introstatsbook" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="" title="Share" id="sidebar-tool-dropdown-0" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-share"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-0">
<li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
            <i class="bi bi-bi-twitter pe-1"></i>
          Twitter
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
            <i class="bi bi-bi-facebook pe-1"></i>
          Facebook
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
            <i class="bi bi-bi-linkedin pe-1"></i>
          LinkedIn
          </a>
        </li>
    </ul>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./intro.html" class="sidebar-item-text sidebar-link">Statistics and Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-stats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Science of Data and Data Science</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-r.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Tool foR Data</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./datasummary.html" class="sidebar-item-text sidebar-link">Summarizing Data</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-graphics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-numerics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Sample Statistics</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./prob.html" class="sidebar-item-text sidebar-link">Probability</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-define.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Definition of Probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-rule.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Probability Rules</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-rv.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Random Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-disc.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Discrete Probability Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-cont.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Continuous Probability Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-samdist.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Sampling Distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prob-llnclt.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Law of Large Numbers and Central Limit Theorem</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./infer.html" class="sidebar-item-text sidebar-link">Statistical Inference</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-ci.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Confidence Interval</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-bt.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Bootstrapping</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-ht.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-twomean.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Comparing Two Population Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-var.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Inference About Variances</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-prop.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference About Proportions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-cat.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference about Categorical Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-bayes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Bayesian Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infer-nonpar.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Nonparametric Inference</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./model.html" class="sidebar-item-text sidebar-link">Statistical Models</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-anova.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Analysis of Variance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-reg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-logistic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Logistic Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-bayes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Bayesian Linear Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Survival Analysis</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="toc-section-number">11.1</span>  Introduction</a></li>
  <li><a href="#sampling-distribution" id="toc-sampling-distribution" class="nav-link" data-scroll-target="#sampling-distribution"><span class="toc-section-number">11.2</span>  Sampling Distribution</a></li>
  <li><a href="#standardization-of-sample-mean" id="toc-standardization-of-sample-mean" class="nav-link" data-scroll-target="#standardization-of-sample-mean"><span class="toc-section-number">11.3</span>  Standardization of Sample Mean</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="toc-section-number">11.4</span>  Exercises</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/chenghanyustats/introstatsbook/edit/main/prob-samdist.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/chenghanyustats/introstatsbook/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-prob-samdist" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Sampling Distribution</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>When we do statistical inference, we assume each data point in the sample is drawn from the target population whose characteristic we focus is assumed to follow some probability distribution that is unknown to us. For example, suppose we would like to do inference about Marquette students’ mean height. We assume the student height follows a normal distribution <span class="math inline">\(N(\mu, \sigma^2)\)</span> with <span class="math inline">\(\mu\)</span> being unknown to us (<span class="math inline">\(\mu\)</span> is what we would like to infer for). We collect our sample data, and assume each data point comes from the assumed distribution <span class="math inline">\(N(\mu, \sigma^2)\)</span>.</p>
<p>The sampling distribution is an important concept that connects probability and statistics together. We use the sampling distribution quite often, at least at the introductory level, to do statistical inference, and that’s why we need to learn what it is before doing statistical inference.</p>
<div class="cell">

</div>
<div class="cell">

</div>
<section id="introduction" class="level2" data-number="11.1"><h2 data-number="11.1" class="anchored" data-anchor-id="introduction">
<span class="header-section-number">11.1</span> Introduction</h2>
<p><span style="color:blue"> <strong>Parameter</strong> </span></p>
<p><strong>Parameters</strong> in a probability distribution are the values describing the entire distribution. For example,</p>
<ul>
<li><span style="color:blue"> Binomial: two parameters, <span class="math inline">\(n\)</span> and <span class="math inline">\(\pi\)</span> </span></li>
<li><span style="color:blue"> Poisson: one parameter, <span class="math inline">\(\lambda\)</span> </span></li>
<li><span style="color:blue"> Normal: two parameters, <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> </span></li>
</ul>
<p>As long as we know the values of the parameters of some distribution, we are able to calculate any probability of the distribution, and describe the distribution exactly. The entire distribution is controlled solely by the few parameters.</p>
<p>In statistics, we usually assume our target population follows some distribution, but <em>its parameters are unknown to us</em>. For example, we may assume human weight follows <span class="math inline">\(N(\mu, \sigma^2)\)</span> although we are not quite sure what its mean and/or variance is. We may think the number of snowstorms in one year in the US follows <span class="math inline">\(Poisson(\lambda)\)</span> although we have no idea of the mean number of occurrences.</p>
<div class="columns">
<div class="column" style="width:50%;">
<center>
<span style="color:blue"> Human weight <span class="math inline">\(\sim N(\mu, \sigma^2)\)</span> </span>
</center>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/img-prob/weight.jpeg" class="img-fluid figure-img" width="2816"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<center>
<span style="color:blue"> # of snowstorms <span class="math inline">\(\sim Poisson(\lambda)\)</span> </span>
</center>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/img-prob/storm.jpeg" class="img-fluid figure-img" width="1968"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<!-- One advantage of assuming  -->
<hr>
<p><span style="color:blue"> <strong>Treat Each Data Point as a Random Variable</strong> </span></p>
<!-- Previously when we talk about probability distributions, we usually assume there is a random variable that follows some distribution, right? For example, from binomial, poisson, normal -->
<p>A statistical data analysis more or less involves some probability. How do we bring probability into the analysis? How is the data related to probability? Here we are going to learn some insight about it. Suppose in order to do a data analysis and inference about some population characteristic, the population mean for example, we collect a sample data of size <span class="math inline">\(n\)</span>, a data set having <span class="math inline">\(n\)</span> data points or values.</p>
<p>Here is how the probability comes into play. First, we assume the target population follows some probability distribution, say <span class="math inline">\(N(\mu, \sigma^2)\)</span>. Then we treat each data point as a random variable whose realized value, the value shown in our collected data set, is drawn from the population distribution.</p>
<p>Take Marquette students weight for example. Suppose the weight follows <span class="math inline">\(N(\mu, \sigma^2)\)</span>. Suppose we decide to collect ten data points, so <span class="math inline">\(n = 10\)</span>. Now <em>before</em> we actually collect the data, the ten data points are all random variables that follow <span class="math inline">\(N(\mu, \sigma^2)\)</span>. If we write the ten variables as <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2, \dots, X_{10}\)</span>, then we have <span class="math inline">\(X_i \sim N(\mu, \sigma^2), i = 1, 2, \dots, 10.\)</span> Notice that <span class="math inline">\(X_1, X_2, \dots, X_{10}\)</span> all follow the same distribution because they all come from the same population. Now, <em>after</em> we collect our data, we have the realized value of those ten random variables. For example, out data set may look like</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>134 110 177 183 144 150 95 200 145 189</code></pre>
</div>
</div>
<p>So the realized value of <span class="math inline">\(X_1\)</span> is 134, the realized value of <span class="math inline">\(X_2\)</span> is 110, and so on. Each data value is drawn from the population.</p>
<!-- - $n$ random variables: $X_1, X_2, \dots, X_n$. -->
<!-- - Assume $X_1, X_2, \dots, X_n$ follow the **same** distribution. -->
<!-- - View $X_i$ as *a data point to be drawn* from a population with some distribution, say $N(\mu, \sigma^2)$. -->
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sampling" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="prob-samdist_files/figure-html/fig-sampling-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;11.1: Illustration of sampling from a population</figcaption><p></p>
</figure>
</div>
</div>
</div>
In statistics, we usually assume that <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> are <strong>independent</strong>, meaning that the value of <span class="math inline">\(X_i\)</span> is not affected by any other <span class="math inline">\(X_j, j\ne i\)</span>. With the same distribution, <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> are <em><strong>i</strong>ndependent and <strong>i</strong>dentically <strong>d</strong>istributed</em> , or <strong>iid</strong>, denoted as
<center>
<span style="color:blue"> <span class="math inline">\(X_1, X_2, \dots, X_n \stackrel{iid}{\sim} N(\mu, \sigma^2).\)</span> </span>
</center>
<p>Then we call such sample data <span class="math inline">\((X_1, X_2, \dots, X_n)\)</span> a <strong>random sample</strong> of size <span class="math inline">\(n\)</span> from the population.</p>
<p><!-- + <span style="color:blue"> Example: $X_1, X_2, \dots, X_{50}$ are randomly selected SAT scores from the SAT score population that follows $N(1100, 200^2)$ </span> --></p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>
<em>Before</em> we actually collect the data, the data <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> are random variables from the population distribution <span class="math inline">\(N(\mu, \sigma^2)\)</span>.</li>
<li>Once we collect the data, we know the <em>realized</em> value of these random variables: <span class="math inline">\(x_1, x_2, \dots, x_n\)</span>.</li>
</ul>
</div>
</div>
</section><section id="sampling-distribution" class="level2" data-number="11.2"><h2 data-number="11.2" class="anchored" data-anchor-id="sampling-distribution">
<span class="header-section-number">11.2</span> Sampling Distribution</h2>
<p>Any value computed from a sample <span class="math inline">\((X_1, X_2, \dots, X_n)\)</span> is called a <strong>(sample) statistic</strong>.</p>
<ul>
<li><span style="color:blue"> The sample mean <span class="math inline">\(\frac{1}{n}\sum_{i=1}^n X_i\)</span> is a statistic. </span></li>
<li><span style="color:blue"> Sample variance <span class="math inline">\(\frac{\sum_{i=1}^n \left(X_i - \overline{X}\right)^2}{n-1}\)</span> is also a statistic. </span></li>
</ul>
<p>Since <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> are random variables, any transformation or function of <span class="math inline">\((X_1, X_2, \dots, X_n)\)</span> or its statistics is also a random variable. The probability distribution of a statistic is called the <strong>sampling distribution</strong> of that statistic. It is the probability distribution of that statistic if we <em><strong>were to repeatedly</strong> draw samples of the same size from the population</em>.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Does the sample mean <span class="math inline">\(\overline{X} = \frac{1}{n}\sum_{i=1}^n X_i\)</span> have a sampling distribution?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Yes, because sample mean is a statistic, and it is a random variable! Keep in mind that before we get the realized values of data, data points are random variables. Because <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> are random, <span class="math inline">\(\frac{1}{n}\sum_{i=1}^n X_i\)</span> is random too. The reason why we can calculate sample mean and same variance in <a href="data-numerics.html"><span>Chapter&nbsp;5</span></a> is because we get the realized values of data. They are actual numbers, so we can do calculations.</p>
</div>
</div>
<hr>
<p><span style="color:blue"> <strong>Sampling Distribution of Sample Mean</strong> </span></p>
<p>Since <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> are random, if we repeat the sampling couple of times, every time we will be getting different realized values.</p>
<p>The following table shows 5 replicates of sample data of size 10. The first data set has 10 realized values <code>117 169 111 190  98  94 127 105  93 187</code>. If we were to collect another data set, the first realized value of <span class="math inline">\(X_1\)</span> could be any other number from the population, not necessarily to be <code>117</code> because again <span class="math inline">\(X_1\)</span> is a random variable. In our example <span class="math inline">\(x_1 = 192\)</span> in the second data set. The idea applies to <span class="math inline">\(X_2\)</span> to <span class="math inline">\(X_{10}\)</span>. Now because every time we collect a new data set we get different realized values <span class="math inline">\(x_1, x_2, \dots, x_{10}\)</span>, the realized value of sample mean will vary from sample to sample as well. The first data set gets the sample mean 129.1, the second one 153.2, and so on. This shows why the sample mean is random by nature, and its value varies according to a distribution that is its sampling distribution.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>           x1  x2  x3  x4  x5  x6  x7  x8  x9 x10  mean
Dataset-1 117 169 111 190  98  94 127 105  93 187 129.1
Dataset-2 192 175 179 159 168 167 103 145 151  93 153.2
Dataset-3  93 110 129 173 145 156 189 184 182  94 145.5
Dataset-4 155 136 129 173 137  92 176 130 189 161 147.8
Dataset-5 121 131 132  91 168 143 138 191 145 140 140.0</code></pre>
</div>
</div>
<p><a href="#fig-sampling-distribution">Figure&nbsp;<span>11.2</span></a> illustrates how we collect the sample of sample means that represents its sampling distribution. In short, if we were able to collect lots of samples of size <span class="math inline">\(n\)</span>, and get the sample mean for each sample of size <span class="math inline">\(n\)</span>, the histogram of those sample means gives us a pretty good understanding of what the sampling distribution of the sample mean looks like.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sampling-distribution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="./images/img-prob/sampling_dist_mean.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;11.2: Sampling distribution of sample means (Biostatistics for the Biological and Health Sciences p.241)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The following histogram shows the sampling distribution of the sample mean for the sample of size 10 when the sampling are repeated 1000 times. That is, we have 1000 <span class="math inline">\(\overline{x}\)</span>s, each being computed from <span class="math inline">\(\frac{1}{10}\sum_{i=1}^{10}x_{i}\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="prob-samdist_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The concept is a little abstract, and you may need time to digest it. The applet <a href="https://www.statcrunch.com/applets/type3&amp;samplingdist">Sampling Distribution Applet</a> provides animation of how the sampling distribution is formed. I highly recommend that you play with it, and figure out the entire building process.</p>
<div class="callout-note callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
What are the differences between the sampling distribution of <span class="math inline">\(\overline{X}\)</span> and the population distribution each individual random variable, <span class="math inline">\(X_i\)</span>, is drawn from?
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>This is an important question. So far we know each data point or random variable <span class="math inline">\(X_i, i = 1, \dots, n\)</span> is drawn from the population distribution. The sample mean <span class="math inline">\(\overline{X}\)</span> is also a random variable following its sampling distribution. Fo r any population distribution, not necessarily normal, <span class="math inline">\(\overline{X}\)</span> has the following two properties:</p>
<ul>
<li>
<em>The sample mean <span class="math inline">\((\overline{X})\)</span> is <span style="color:red"> <strong>less variable</strong> </span> than an individual observation <span class="math inline">\(X_i\)</span></em>. Although <span class="math inline">\(\overline{X}\)</span> and <span class="math inline">\(X_i\)</span> are both random variables, the sampling distribution of <span class="math inline">\(\overline{X}\)</span> has smaller variance than <span class="math inline">\(X_i\)</span>. Intuitively, <span class="math inline">\(\overline{X}\)</span> is the average of bunch of <span class="math inline">\(X_i\)</span>s. Averaging is washing the extreme values out, resulting in values similar to each other.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>data 1: 30 40 50 60 70</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>data 2: 0 5 50 95 100</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>data 3: 0 5 10 15 220</code></pre>
</div>
</div>
<p>The three data sets all have <span class="math inline">\(x_1, \dots, x_5\)</span>. Clearly, <span class="math inline">\(X_i\)</span> could generate pretty small or large values. However, when all five <span class="math inline">\(x_1, \dots, x_5\)</span> are averaged, the extreme values are combined together, moving toward to some value in between. In this example, all three data sets have the sample mean <span class="math inline">\(50\)</span> with even no variation at all. The sample mean is much more stable than individual <span class="math inline">\(X_i\)</span>, especially when the sample size <span class="math inline">\(n\)</span> is large.</p>
<ul>
<li><em>The sample mean <span class="math inline">\((\overline{X})\)</span> is <span style="color:red"> <strong>more normal</strong> </span> than an individual observation <span class="math inline">\(X_i\)</span>.</em></li>
</ul>
<p>The population distribution <span class="math inline">\(X_i\)</span> is drawn from is not necessarily a normal distribution, and it can be any distribution that is not bell-shaped or not unimodal. However, the sampling distribution will always look more like a normal distribution than the assumed population distribution. This sounds unreal, but it is true. The important central limit theorem proves this, and we will talk about it in <a href="prob-llnclt.html"><span>Chapter&nbsp;12</span></a>.</p>
<p>Suppose <span class="math inline">\((X_1, \dots, X_n)\)</span> is the random sample from a population distribution with mean <span class="math inline">\(\mu\)</span>, and standard deviation <span class="math inline">\(\sigma\)</span>. Can we know the mean and variance of the sampling distribution of the sample mean <span class="math inline">\(\overline{X} = \frac{\sum_{i=1}^nX_i}{n}\)</span>, denoted by <span class="math inline">\(\mu_{\overline{X}}\)</span> and <span class="math inline">\(\sigma_{\overline{X}}\)</span> respectively? The answer is yes. In fact,</p>
<ul>
<li><p><span style="color:blue"> <span class="math inline">\(\mu_{\overline{X}} = \mu\)</span> </span>. The mean of <span class="math inline">\(\mu_{\overline{X}}\)</span> is equal to the population mean <span class="math inline">\(\mu\)</span>, i.e., <span class="math inline">\(E(\overline{X}) = \mu\)</span>.</p></li>
<li><p><span style="color:blue"> <span class="math inline">\(\sigma_{\overline{X}} = \frac{\sigma}{\sqrt{n}}\)</span> </span>. The standard deviation of <span class="math inline">\(\overline{X}\)</span> is not equal to the population standard deviation <span class="math inline">\(\sigma\)</span>. It is actually <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span> that is smaller than <span class="math inline">\(\sigma\)</span>. This is consistent with the property that <span class="math inline">\(\overline{X}\)</span> is less variable than an individual variable <span class="math inline">\(X_i\)</span> we learned before. Notice that the variation of <span class="math inline">\(\overline{X}\)</span> is getting smaller as the sample size <span class="math inline">\(n\)</span> get large. <span class="math inline">\(\sigma_{\overline{X}}\)</span> is also known as the <strong>standard error</strong> of <span class="math inline">\(\overline{X}\)</span>.</p></li>
</ul>
<p>If the population distribution is <span style="color:blue"> <span class="math inline">\(N(\mu, \sigma^2)\)</span> </span>, then the sampling distribution of <span class="math inline">\(\overline{X}\)</span> is also normally distributed: <span style="color:blue"> <span class="math inline">\(N\left(\mu, \frac{\sigma^2}{n} \right)\)</span> </span>.</p>
<p><a href="#fig-sampling-dist-normal">Figure&nbsp;<span>11.3</span></a> depicts that the sampling distributions of the sample mean are less variable than the population distribution (black colored). As the sample size <span class="math inline">\(n\)</span> increases from 2 (red), 4 (blue), to 8 (green), its corresponding sampling distribution is getting less variable, with smaller chance to have extreme values. Since the population distribution is normally distributed, so is the sampling distribution. The population distribution and the sampling distribution have the same mean, both centered at one.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sampling-dist-normal" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="prob-samdist_files/figure-html/fig-sampling-dist-normal-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;11.3: Comparison between sampling distributions and the population distribution.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><span style="color:red"> <strong><em>Example: Rolling a Die</em></strong> </span></p>
<p>Let’s see how we get a sampling distribution through an example. Suppose one rolls a fair die 3 times 🎲🎲 🎲 independently to obtain 3 values from the “population” <span class="math inline">\(\{1, 2, 3, 4, 5, 6\}\)</span>. Well if we let <span class="math inline">\(X_i, i = 1, 2, 3\)</span> be the number showing up for the <span class="math inline">\(i\)</span>th roll, then each <span class="math inline">\(X_i\)</span> follows the discrete uniform distribution <span class="math inline">\(P(X_i = 1) = P(X_i = 2) = \cdots = P(X_i = 6) = 1/6\)</span> because <span class="math inline">\(X_i\)</span> is a discrete random variable and a fair die is rolled. The population mean is <span class="math inline">\((1+2+3+4+5+6)/6 = 3.5.\)</span> <a href="#fig-die-pop">Figure&nbsp;<span>11.4</span></a> shows the population distribution.</p>
<p>To obtain the sampling distribution of the sample mean, we first repeat the process 10,000 times, and get 10,000 corresponding sample means.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>          x1 x2 x3     mean
Dataset-1  6  3  2 3.666667
Dataset-2  4  2  5 3.666667
Dataset-3  3  2  6 3.666667</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>. . . . . .</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>              x1 x2 x3     mean
Dataset-9998   5  4  6 5.000000
Dataset-9999   4  1  1 2.000000
Dataset-10000  4  6  1 3.666667</code></pre>
</div>
</div>
<p>Then plot the histogram of those sampling means. <a href="#fig-die-sample">Figure&nbsp;<span>11.5</span></a> shows the histogram of those 10000 sample means which can be treated as the sampling distribution of the sample mean. What do we see from the plots? First, since the population distribution is discrete, so is the sampling distribution. Second, both have the identical mean 3.5. <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Third, the sampling distribution look more like a normal distribution.</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-die-pop" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="prob-samdist_files/figure-html/fig-die-pop-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;11.4: Population distribution is discrete uniformly distributed.</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-die-sample" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="prob-samdist_files/figure-html/fig-die-sample-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;11.5: Sampling distribution is more normal-like.</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section><section id="standardization-of-sample-mean" class="level2" data-number="11.3"><h2 data-number="11.3" class="anchored" data-anchor-id="standardization-of-sample-mean">
<span class="header-section-number">11.3</span> Standardization of Sample Mean</h2>
<p>Any random variable can be standardized. For a single random variable <span class="math inline">\(X \sim N(\mu, \sigma^2)\)</span>, we have <span class="math inline">\(Z = \frac{X - \mu}{\sigma} \sim N(0, 1)\)</span>. For the sample mean of <span class="math inline">\(n\)</span> variables, we know <span class="math inline">\(\overline{X} \sim N(\mu_{\overline{X}}, \sigma^2_{\overline{X}}) = N(\mu, \frac{\sigma^2}{n})\)</span>. To standardize <span class="math inline">\(\overline{X}\)</span>, and make a new standard normal variable from it, we just subtract it from its own mean and divided by it own standard deviation:</p>
<p><span style="color:blue"> <span class="math display">\[Z = \frac{\overline{X} - \mu_{\overline{X}}}{\sigma_{\overline{X}}} = \frac{\overline{X} - \mu}{\sigma/\sqrt{n}} \sim N(0, 1)\]</span></span></p>
<p>Again, since <span class="math inline">\(\overline{X}\)</span> is a random variable, its transformation is also a random variable. <span class="math inline">\(\frac{\overline{X} - \mu}{\sigma/\sqrt{n}}\)</span> is a standard normal variable.</p>
<p><span style="color:blue"> <strong>Example: Psychomotor Retardation</strong> </span></p>
<div class="columns">
<div class="column" style="width:80%;">
<p>Suppose psychomotor retardation scores for a group of patients have a normal distribution with a mean of 930 and a standard deviation of 130.</p>
<ul>
<li>What is the probability that the <em>mean</em> retardation score of a random sample of 20 patients was between 900 and 960?</li>
</ul>
</div><div class="column" style="width:20%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./images/img-prob/depression.jpeg" class="img-fluid figure-img" width="1544"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>First, from the question assume that <span class="math inline">\((X_1, \dots, X_{20})\)</span> forms a random sample, and <span class="math inline">\(X_1, \dots, X_{20} \stackrel{iid}{\sim} N(930, 130^2)\)</span>. Then <span class="math inline">\(\overline{X} = \frac{\sum_{i=1}^{20}X_i}{20} \sim N\left(930, \frac{130^2}{20} \right)\)</span>.</p>
<p>What we want to compute is <span class="math inline">\(P(900 &lt; \overline{X} &lt; 960)\)</span>. We can first standardize <span class="math inline">\(\overline{X}\)</span> and represent the probability using standard normal <span class="math inline">\(Z\)</span>: <span class="math display">\[\small \begin{align}
P(900 &lt; \overline{X} &lt; 960) &amp;= P\left( \frac{900-930}{130/\sqrt{20}} &lt; \frac{\overline{X}-930}{130/\sqrt{20}} &lt; \frac{960-930}{130/\sqrt{20}}\right)=P(-1.03 &lt; Z &lt; 1.03)\\
&amp;=P(Z &lt; 1.03) - P(Z &lt; -1.03)
  \end{align}\]</span></p>
<p>Finally we just need to find <span class="math inline">\(P(Z &lt; 1.03)\)</span> and <span class="math inline">\(P(Z &lt; -1.03)\)</span> using R:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="op">(</span><span class="fl">960</span><span class="op">-</span><span class="fl">930</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="fl">130</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">20</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.032031</code></pre>
</div>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="op">(</span><span class="fl">900</span><span class="op">-</span><span class="fl">930</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="fl">130</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">20</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.032031</code></pre>
</div>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fl">1.032031</span><span class="op">)</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1.032031</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6979424</code></pre>
</div>
</div>
<p>If we don’t do standardization, remember to use values in the original scale, and specify the mean and standard deviation. Keep in mind the standard deviation is <span class="math inline">\(\sigma_{\overline{X}} = 130/\sqrt{20}\)</span>, not <span class="math inline">\(130\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## P(Xbar &lt; 960) - P(Xbar &lt; 900)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fl">960</span>, mean <span class="op">=</span> <span class="fl">930</span>, sd <span class="op">=</span> <span class="fl">130</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">20</span><span class="op">)</span><span class="op">)</span> <span class="op">-</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fl">900</span>, mean <span class="op">=</span> <span class="fl">930</span>, sd <span class="op">=</span> <span class="fl">130</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">20</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6979426</code></pre>
</div>
</div>
<p>The probability that the mean psychomotor retardation score of a random sample of 20 patients is between 900 and 960 is about 70%.</p>
</section><section id="exercises" class="level2" data-number="11.4"><h2 data-number="11.4" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">11.4</span> Exercises</h2>
<ol type="1">
<li>Head lengths of Virginia possums follow a normal distribution with mean 104 mm and standard deviation 6 mm.
<ol type="a">
<li>What is the sampling distribution of the sample mean of the head length when the sample size <span class="math inline">\(n = 18\)</span>?</li>
</ol>
</li>
<li>Assume that females have pulse rates that are normally distributed with a mean of 76.0 beats per minute and a standard deviation of 11.5 beats per minute.
<ol type="a">
<li>If 1 adult female is randomly selected, find the probability that her pulse rate is less than 81 beats per minute.</li>
<li>If 18 adult female are randomly selected, find the probability that their mean pulse rate is less than 81 beats per minute.</li>
</ol>
</li>
</ol>


</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>The average or the empirical mean of those 10000 <span class="math inline">\(\overline{x}\)</span>s would not be exactly equal to, but very close to the population mean 3.5. In fact, the average is 3.5001. As we discussed, theoretically it is true that <span class="math inline">\(E(\overline{X}) = \mu = 3.5\)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./prob-cont.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Continuous Probability Distributions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./prob-llnclt.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Law of Large Numbers and Central Limit Theorem</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Copyright 2023, Dr.&nbsp;Cheng-Han Yu</div>   
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
<li class="nav-item compact">
    <a class="nav-link active" href="https://github.com/chenghanyustats/introstatsbook" aria-current="page">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
</div>
  </div>
</footer>


</body></html>